// This file is generated by Sapper — do not edit it!
export const timestamp = 1540469747484;

export const files = [
	".DS_Store",
	"base.css",
	"favicon.ico",
	"manifest.json",
	"paprika-logo-192.png",
	"paprika-logo-512.png",
	"ress.css"
];
export { files as assets }; // legacy

export const shell = [
	"client/81bdc354040f24941b3d/contributors_$slug.contributors_$slug.js",
	"client/81bdc354040f24941b3d/$slug.$slug.js",
	"client/81bdc354040f24941b3d/archive.archive.js",
	"client/81bdc354040f24941b3d/archive__layout.archive__layout.js",
	"client/81bdc354040f24941b3d/archive_articles.archive_articles.js",
	"client/81bdc354040f24941b3d/archive_contributors.archive_contributors.js",
	"client/81bdc354040f24941b3d/archive_folds.archive_folds.js",
	"client/81bdc354040f24941b3d/articles.articles.js",
	"client/81bdc354040f24941b3d/articles_$slug.articles_$slug.js",
	"client/81bdc354040f24941b3d/contributors.contributors.js",
	"client/81bdc354040f24941b3d/about.about.js",
	"client/81bdc354040f24941b3d/contributors_$slug~folds_$slug~index.contributors_$slug~folds_$slug~index.js",
	"client/81bdc354040f24941b3d/0.0.js",
	"client/81bdc354040f24941b3d/folds.folds.js",
	"client/81bdc354040f24941b3d/folds_$slug.folds_$slug.js",
	"client/81bdc354040f24941b3d/index.index.js",
	"client/81bdc354040f24941b3d/main.js",
	"client/81bdc354040f24941b3d/search.search.js",
	"client/81bdc354040f24941b3d/support.support.js",
	"client/81bdc354040f24941b3d/vendors~folds.vendors~folds.js",
	"client/81bdc354040f24941b3d/vendors~search.vendors~search.js"
];

export const routes = [
	{ pattern: /^\/?$/ },
	{ pattern: /^\/contributors\/?$/ },
	{ pattern: /^\/contributors\/([^\/]+?)\/?$/ },
	{ pattern: /^\/articles\/?$/ },
	{ pattern: /^\/articles\/([^\/]+?)\/?$/ },
	{ pattern: /^\/archive\/?$/ },
	{ pattern: /^\/archive\/contributors\/?$/ },
	{ pattern: /^\/archive\/articles\/?$/ },
	{ pattern: /^\/archive\/folds\/?$/ },
	{ pattern: /^\/support\/?$/ },
	{ pattern: /^\/search\/?$/ },
	{ pattern: /^\/about\/?$/ },
	{ pattern: /^\/folds\/?$/ },
	{ pattern: /^\/folds\/([^\/]+?)\/?$/ },
	{ pattern: /^\/([^\/]+?)\/?$/ }
];