(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["$slug"],{

/***/ "./src/routes/[slug].html":
/*!********************************!*\
  !*** ./src/routes/[slug].html ***!
  \********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/shared.js */ "./node_modules/svelte/shared.js");
/* src/routes/[slug].html generated by Svelte v2.9.9 */


function preload({ params, query }) {
  return this.redirect(301, `articles/${params.slug}`)
};

const file = "src/routes/[slug].html";

function create_main_fragment(component, ctx) {

	return {
		c: svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["noop"],

		l: svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["noop"],

		m: svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["noop"],

		p: svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["noop"]
	};
}

function Slug(options) {
	this._debugName = '<Slug>';
	if (!options || (!options.target && !options.root)) throw new Error("'target' is a required option");
	Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options);
	this._state = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])({}, options.data);
	this._intro = true;

	this._fragment = create_main_fragment(this, this._state);

	if (options.target) {
		var nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(options.target);
		options.hydrate ? this._fragment.l(nodes) : this._fragment.c();
		nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
		this._mount(options.target, options.anchor);
	}
}

Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])(Slug.prototype, svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["protoDev"]);

Slug.prototype._checkReadOnly = function _checkReadOnly(newState) {
};

Slug.preload = preload;

if (true) {
	const { configure, register, reload } = __webpack_require__(/*! ./node_modules/svelte-loader/lib/hot-api.js */ "./node_modules/svelte-loader/lib/hot-api.js");

	module.hot.accept();

	if (!module.hot.data) {
		// initial load
		configure({});
		Slug = register("src/routes/[slug].html", Slug);
	} else {
		// hot update
		Slug = reload("src/routes/[slug].html", Slug);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Slug);


/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL1tzbHVnXS5odG1sIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7OztnQkFFVyxDQUFDLEVBQUUsTUFBTSxFQUFFLEtBQUssRUFBRSxFQUFFO0FBQzNCLEVBQUUsT0FBTyxJQUFJLENBQUMsUUFBUSxDQUFDLEdBQUcsRUFBRSxDQUFDLFNBQVMsRUFBRSxNQUFNLENBQUMsSUFBSSxDQUFDLENBQUMsQ0FBQztBQUN0RCxDQUFDIiwiZmlsZSI6IjgxYmRjMzU0MDQwZjI0OTQxYjNkLyRzbHVnLiRzbHVnLmpzIiwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgZXhwb3J0IGRlZmF1bHQge1xuICAgIHByZWxvYWQoeyBwYXJhbXMsIHF1ZXJ5IH0pIHtcbiAgICAgIHJldHVybiB0aGlzLnJlZGlyZWN0KDMwMSwgYGFydGljbGVzLyR7cGFyYW1zLnNsdWd9YClcbiAgICB9XG4gIH1cbjwvc2NyaXB0PiJdLCJzb3VyY2VSb290IjoiIn0=