(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["about"],{

/***/ "./components/Title.html":
/*!*******************************!*\
  !*** ./components/Title.html ***!
  \*******************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/shared.js */ "./node_modules/svelte/shared.js");
/* components/Title.html generated by Svelte v2.9.9 */


const file = "components/Title.html";

function add_css() {
	var style = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("style");
	style.id = 'svelte-quv5ds-style';
	style.textContent = "h1.svelte-quv5ds{font-size:3rem;line-height:0.9;font-weight:400;margin-bottom:3rem}@media(min-width: 768px){h1.svelte-quv5ds{font-size:4rem}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiVGl0bGUuaHRtbCIsInNvdXJjZXMiOlsiVGl0bGUuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyI8ZGl2IGNsYXNzPVwiYzEyIHoyXCI+XG4gIDxoMSBjbGFzcz1cImNvMiBjOCBzbS1jbzQgc20tYzRcIj57QGh0bWwgdGl0bGV9PC9oMT5cbjwvZGl2PlxuXG48c3R5bGU+XG4gIGgxIHtcbiAgICBmb250LXNpemU6IDNyZW07XG4gICAgbGluZS1oZWlnaHQ6IDAuOTtcbiAgICBmb250LXdlaWdodDogNDAwO1xuICAgIG1hcmdpbi1ib3R0b206IDNyZW07XG4gIH1cbiAgQG1lZGlhIChtaW4td2lkdGg6IDc2OHB4KSB7XG4gICAgaDEge1xuICAgICAgZm9udC1zaXplOiA0cmVtO1xuICAgIH1cbiAgfVxuPC9zdHlsZT4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBS0UsRUFBRSxjQUFDLENBQUMsQUFDRixTQUFTLENBQUUsSUFBSSxDQUNmLFdBQVcsQ0FBRSxHQUFHLENBQ2hCLFdBQVcsQ0FBRSxHQUFHLENBQ2hCLGFBQWEsQ0FBRSxJQUFJLEFBQ3JCLENBQUMsQUFDRCxNQUFNLEFBQUMsWUFBWSxLQUFLLENBQUMsQUFBQyxDQUFDLEFBQ3pCLEVBQUUsY0FBQyxDQUFDLEFBQ0YsU0FBUyxDQUFFLElBQUksQUFDakIsQ0FBQyxBQUNILENBQUMifQ== */";
	Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(style, document.head);
}

function create_main_fragment(component, ctx) {
	var div, h1;

	return {
		c: function create() {
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			h1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h1");
			this.h()
		},

		l: function claim(nodes) {
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			h1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "H1", { class: true }, false);
			var h1_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);

			h1_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			div_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			h1.className = "co2 c8 sm-co4 sm-c4 svelte-quv5ds";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(h1, file, 1, 2, 23);
			div.className = "c12 z2";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div, file, 0, 0, 0);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(div, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(h1, div);
			h1.innerHTML = ctx.title;
		},

		p: function update(changed, ctx) {
			if (changed.title) {
				h1.innerHTML = ctx.title;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(div);
			}
		}
	};
}

function Title(options) {
	this._debugName = '<Title>';
	if (!options || (!options.target && !options.root)) throw new Error("'target' is a required option");
	Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options);
	this._state = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])({}, options.data);
	if (!('title' in this._state)) console.warn("<Title> was created without expected data property 'title'");
	this._intro = true;

	if (!document.getElementById("svelte-quv5ds-style")) add_css();

	this._fragment = create_main_fragment(this, this._state);

	if (options.target) {
		var nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(options.target);
		options.hydrate ? this._fragment.l(nodes) : this._fragment.c();
		nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
		this._mount(options.target, options.anchor);
	}
}

Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])(Title.prototype, svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["protoDev"]);

Title.prototype._checkReadOnly = function _checkReadOnly(newState) {
};

if (true) {
	const { configure, register, reload } = __webpack_require__(/*! ./node_modules/svelte-loader/lib/hot-api.js */ "./node_modules/svelte-loader/lib/hot-api.js");

	module.hot.accept();

	if (!module.hot.data) {
		// initial load
		configure({});
		Title = register("components/Title.html", Title);
	} else {
		// hot update
		Title = reload("components/Title.html", Title);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Title);


/***/ }),

/***/ "./src/routes/about.html":
/*!*******************************!*\
  !*** ./src/routes/about.html ***!
  \*******************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/shared.js */ "./node_modules/svelte/shared.js");
/* harmony import */ var _components_Title_html__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../../components/Title.html */ "./components/Title.html");
/* src/routes/about.html generated by Svelte v2.9.9 */



async function preload({ params, query }) {
  const maskFields = 'content/rendered,' +
    'meta(' +
      'coordinating_editors(title/rendered,slug),' +
      'publishers(title/rendered,slug),' +
      'web_editor(title/rendered,slug),' +
      'graphic_design_liason(title/rendered,slug),' +
      'site_design(title/rendered,slug),' +
      'site_development(title/rendered,slug)' +
    ')'
  const res = await this.fetch(`/about.json?fields=${maskFields}`)
  if (!res.ok) {
    const message = await res.text()
    return this.error(res.status, message);
  }
  const data = await res.json()
  return { page: data }
};

const file = "src/routes/about.html";

function create_main_fragment(component, ctx) {
	var text, text_1, div, div_1, ul, li, a, text_2, li_1, a_1, text_3, li_2, a_2, text_4, text_6, div_2, raw_value = ctx.page.content.rendered, text_8, div_3, text_9, text_10, text_11, text_12, text_13;

	var title_initial_data = { title: "About" };
	var title = new _components_Title_html__WEBPACK_IMPORTED_MODULE_1__["default"]({
		root: component.root,
		store: component.store,
		data: title_initial_data
	});

	var if_block = (ctx.page.meta.coordinating_editors) && create_if_block(component, ctx);

	var if_block_1 = (ctx.page.meta.publishers) && create_if_block_1(component, ctx);

	var if_block_2 = (ctx.page.meta.web_editor) && create_if_block_2(component, ctx);

	var if_block_3 = (ctx.page.meta.graphic_design_liason) && create_if_block_3(component, ctx);

	var if_block_4 = (ctx.page.meta.site_design) && create_if_block_4(component, ctx);

	var if_block_5 = (ctx.page.meta.site_development) && create_if_block_5(component, ctx);

	return {
		c: function create() {
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n\n");
			title._fragment.c();
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n");
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			div_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("ul");
			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("li");
			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("a");
			text_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("About");
			li_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("li");
			a_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("a");
			text_3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("Support");
			li_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("li");
			a_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("a");
			text_4 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("Search");
			text_6 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n  ");
			div_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			text_8 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n  ");
			div_3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			if (if_block) if_block.c();
			text_9 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n    ");
			if (if_block_1) if_block_1.c();
			text_10 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n    ");
			if (if_block_2) if_block_2.c();
			text_11 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n    ");
			if (if_block_3) if_block_3.c();
			text_12 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n    ");
			if (if_block_4) if_block_4.c();
			text_13 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n    ");
			if (if_block_5) if_block_5.c();
			this.h()
		},

		l: function claim(nodes) {
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(nodes, "\n\n");
			title._fragment.l(nodes);
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(nodes, "\n");

			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			div_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "DIV", { class: true }, false);
			var div_1_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div_1);

			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_1_nodes, "UL", {}, false);
			var ul_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(ul_nodes, "LI", {}, false);
			var li_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(li);

			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(li_nodes, "A", { rel: true, href: true }, false);
			var a_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			text_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(a_nodes, "About");
			a_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			li_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);

			li_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(ul_nodes, "LI", {}, false);
			var li_1_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(li_1);

			a_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(li_1_nodes, "A", { rel: true, href: true }, false);
			var a_1_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(a_1);

			text_3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(a_1_nodes, "Support");
			a_1_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			li_1_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);

			li_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(ul_nodes, "LI", {}, false);
			var li_2_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(li_2);

			a_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(li_2_nodes, "A", { rel: true, href: true }, false);
			var a_2_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(a_2);

			text_4 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(a_2_nodes, "Search");
			a_2_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			li_2_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			ul_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			div_1_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_6 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_nodes, "\n  ");

			div_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "DIV", { class: true }, false);
			var div_2_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div_2);

			div_2_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_8 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_nodes, "\n  ");

			div_3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "DIV", { class: true }, false);
			var div_3_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div_3);

			if (if_block) if_block.l(div_3_nodes);
			text_9 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_3_nodes, "\n    ");
			if (if_block_1) if_block_1.l(div_3_nodes);
			text_10 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_3_nodes, "\n    ");
			if (if_block_2) if_block_2.l(div_3_nodes);
			text_11 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_3_nodes, "\n    ");
			if (if_block_3) if_block_3.l(div_3_nodes);
			text_12 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_3_nodes, "\n    ");
			if (if_block_4) if_block_4.l(div_3_nodes);
			text_13 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_3_nodes, "\n    ");
			if (if_block_5) if_block_5.l(div_3_nodes);
			div_3_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			div_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			document.title = "About";
			a.rel = "prefetch";
			a.href = "/about";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(a, file, 8, 10, 144);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(li, file, 8, 6, 140);
			a_1.rel = "prefetch";
			a_1.href = "/support";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(a_1, file, 9, 10, 201);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(li_1, file, 9, 6, 197);
			a_2.rel = "prefetch";
			a_2.href = "/search";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(a_2, file, 10, 10, 262);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(li_2, file, 10, 6, 258);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(ul, file, 7, 4, 129);
			div_1.className = "dn sm-db c2 p1";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div_1, file, 6, 2, 96);
			div_2.className = "c12 sm-c4 p1";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div_2, file, 13, 2, 332);
			div_3.className = "c12 sm-c4 p1";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div_3, file, 16, 2, 404);
			div.className = "x xw";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div, file, 5, 0, 75);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(text, target, anchor);
			title._mount(target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(text_1, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(div, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(div_1, div);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(ul, div_1);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(li, ul);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(a, li);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_2, a);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(li_1, ul);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(a_1, li_1);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_3, a_1);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(li_2, ul);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(a_2, li_2);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_4, a_2);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_6, div);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(div_2, div);
			div_2.innerHTML = raw_value;
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_8, div);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(div_3, div);
			if (if_block) if_block.m(div_3, null);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_9, div_3);
			if (if_block_1) if_block_1.m(div_3, null);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_10, div_3);
			if (if_block_2) if_block_2.m(div_3, null);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_11, div_3);
			if (if_block_3) if_block_3.m(div_3, null);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_12, div_3);
			if (if_block_4) if_block_4.m(div_3, null);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_13, div_3);
			if (if_block_5) if_block_5.m(div_3, null);
		},

		p: function update(changed, ctx) {
			if ((changed.page) && raw_value !== (raw_value = ctx.page.content.rendered)) {
				div_2.innerHTML = raw_value;
			}

			if (ctx.page.meta.coordinating_editors) {
				if (if_block) {
					if_block.p(changed, ctx);
				} else {
					if_block = create_if_block(component, ctx);
					if_block.c();
					if_block.m(div_3, text_9);
				}
			} else if (if_block) {
				if_block.d(1);
				if_block = null;
			}

			if (ctx.page.meta.publishers) {
				if (if_block_1) {
					if_block_1.p(changed, ctx);
				} else {
					if_block_1 = create_if_block_1(component, ctx);
					if_block_1.c();
					if_block_1.m(div_3, text_10);
				}
			} else if (if_block_1) {
				if_block_1.d(1);
				if_block_1 = null;
			}

			if (ctx.page.meta.web_editor) {
				if (if_block_2) {
					if_block_2.p(changed, ctx);
				} else {
					if_block_2 = create_if_block_2(component, ctx);
					if_block_2.c();
					if_block_2.m(div_3, text_11);
				}
			} else if (if_block_2) {
				if_block_2.d(1);
				if_block_2 = null;
			}

			if (ctx.page.meta.graphic_design_liason) {
				if (if_block_3) {
					if_block_3.p(changed, ctx);
				} else {
					if_block_3 = create_if_block_3(component, ctx);
					if_block_3.c();
					if_block_3.m(div_3, text_12);
				}
			} else if (if_block_3) {
				if_block_3.d(1);
				if_block_3 = null;
			}

			if (ctx.page.meta.site_design) {
				if (if_block_4) {
					if_block_4.p(changed, ctx);
				} else {
					if_block_4 = create_if_block_4(component, ctx);
					if_block_4.c();
					if_block_4.m(div_3, text_13);
				}
			} else if (if_block_4) {
				if_block_4.d(1);
				if_block_4 = null;
			}

			if (ctx.page.meta.site_development) {
				if (if_block_5) {
					if_block_5.p(changed, ctx);
				} else {
					if_block_5 = create_if_block_5(component, ctx);
					if_block_5.c();
					if_block_5.m(div_3, null);
				}
			} else if (if_block_5) {
				if_block_5.d(1);
				if_block_5 = null;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(text);
			}

			title.destroy(detach);
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(text_1);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(div);
			}

			if (if_block) if_block.d();
			if (if_block_1) if_block_1.d();
			if (if_block_2) if_block_2.d();
			if (if_block_3) if_block_3.d();
			if (if_block_4) if_block_4.d();
			if (if_block_5) if_block_5.d();
		}
	};
}

// (21:8) {#each page.meta.coordinating_editors as editor}
function create_each_block(component, ctx) {
	var li, a, raw_value = ctx.editor.title.rendered, a_href_value;

	return {
		c: function create() {
			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("li");
			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("a");
			this.h()
		},

		l: function claim(nodes) {
			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "LI", {}, false);
			var li_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(li);

			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(li_nodes, "A", { rel: true, href: true }, false);
			var a_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			a_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			li_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			a.rel = "prefetch";
			a.href = a_href_value = "/contributors/" + ctx.editor.slug;
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(a, file, 21, 14, 590);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(li, file, 21, 10, 586);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(li, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(a, li);
			a.innerHTML = raw_value;
		},

		p: function update(changed, ctx) {
			if ((changed.page) && raw_value !== (raw_value = ctx.editor.title.rendered)) {
				a.innerHTML = raw_value;
			}

			if ((changed.page) && a_href_value !== (a_href_value = "/contributors/" + ctx.editor.slug)) {
				a.href = a_href_value;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(li);
			}
		}
	};
}

// (18:4) {#if page.meta.coordinating_editors}
function create_if_block(component, ctx) {
	var h3, text, text_1, ul;

	var each_value = ctx.page.meta.coordinating_editors;

	var each_blocks = [];

	for (var i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(component, get_each_context(ctx, each_value, i));
	}

	return {
		c: function create() {
			h3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h3");
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("Coordinating Editors");
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n      ");
			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("ul");

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}
			this.h()
		},

		l: function claim(nodes) {
			h3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "H3", {}, false);
			var h3_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(h3);

			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(h3_nodes, "Coordinating Editors");
			h3_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(nodes, "\n      ");

			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "UL", {}, false);
			var ul_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(ul_nodes);
			}

			ul_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(h3, file, 18, 6, 478);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(ul, file, 19, 6, 514);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(h3, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text, h3);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(text_1, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(ul, target, anchor);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(ul, null);
			}
		},

		p: function update(changed, ctx) {
			if (changed.page) {
				each_value = ctx.page.meta.coordinating_editors;

				for (var i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(changed, child_ctx);
					} else {
						each_blocks[i] = create_each_block(component, child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(ul, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}
				each_blocks.length = each_value.length;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(h3);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(text_1);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(ul);
			}

			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["destroyEach"])(each_blocks, detach);
		}
	};
}

// (29:8) {#each page.meta.publishers as publisher}
function create_each_block_1(component, ctx) {
	var li, a, raw_value = ctx.publisher.title.rendered, a_href_value;

	return {
		c: function create() {
			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("li");
			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("a");
			this.h()
		},

		l: function claim(nodes) {
			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "LI", {}, false);
			var li_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(li);

			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(li_nodes, "A", { rel: true, href: true }, false);
			var a_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			a_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			li_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			a.rel = "prefetch";
			a.href = a_href_value = "/contributors/" + ctx.publisher.slug;
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(a, file, 29, 14, 852);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(li, file, 29, 10, 848);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(li, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(a, li);
			a.innerHTML = raw_value;
		},

		p: function update(changed, ctx) {
			if ((changed.page) && raw_value !== (raw_value = ctx.publisher.title.rendered)) {
				a.innerHTML = raw_value;
			}

			if ((changed.page) && a_href_value !== (a_href_value = "/contributors/" + ctx.publisher.slug)) {
				a.href = a_href_value;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(li);
			}
		}
	};
}

// (26:4) {#if page.meta.publishers}
function create_if_block_1(component, ctx) {
	var h3, text, text_1, ul;

	var each_value_1 = ctx.page.meta.publishers;

	var each_blocks = [];

	for (var i = 0; i < each_value_1.length; i += 1) {
		each_blocks[i] = create_each_block_1(component, get_each_context_1(ctx, each_value_1, i));
	}

	return {
		c: function create() {
			h3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h3");
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("Publishers");
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n      ");
			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("ul");

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}
			this.h()
		},

		l: function claim(nodes) {
			h3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "H3", {}, false);
			var h3_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(h3);

			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(h3_nodes, "Publishers");
			h3_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(nodes, "\n      ");

			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "UL", {}, false);
			var ul_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(ul_nodes);
			}

			ul_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(h3, file, 26, 6, 757);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(ul, file, 27, 6, 783);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(h3, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text, h3);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(text_1, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(ul, target, anchor);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(ul, null);
			}
		},

		p: function update(changed, ctx) {
			if (changed.page) {
				each_value_1 = ctx.page.meta.publishers;

				for (var i = 0; i < each_value_1.length; i += 1) {
					const child_ctx = get_each_context_1(ctx, each_value_1, i);

					if (each_blocks[i]) {
						each_blocks[i].p(changed, child_ctx);
					} else {
						each_blocks[i] = create_each_block_1(component, child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(ul, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}
				each_blocks.length = each_value_1.length;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(h3);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(text_1);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(ul);
			}

			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["destroyEach"])(each_blocks, detach);
		}
	};
}

// (37:8) {#each page.meta.web_editor as editor}
function create_each_block_2(component, ctx) {
	var li, a, raw_value = ctx.editor.title.rendered, a_href_value;

	return {
		c: function create() {
			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("li");
			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("a");
			this.h()
		},

		l: function claim(nodes) {
			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "LI", {}, false);
			var li_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(li);

			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(li_nodes, "A", { rel: true, href: true }, false);
			var a_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			a_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			li_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			a.rel = "prefetch";
			a.href = a_href_value = "/contributors/" + ctx.editor.slug;
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(a, file, 37, 14, 1117);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(li, file, 37, 10, 1113);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(li, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(a, li);
			a.innerHTML = raw_value;
		},

		p: function update(changed, ctx) {
			if ((changed.page) && raw_value !== (raw_value = ctx.editor.title.rendered)) {
				a.innerHTML = raw_value;
			}

			if ((changed.page) && a_href_value !== (a_href_value = "/contributors/" + ctx.editor.slug)) {
				a.href = a_href_value;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(li);
			}
		}
	};
}

// (34:4) {#if page.meta.web_editor}
function create_if_block_2(component, ctx) {
	var h3, text, text_1, ul;

	var each_value_2 = ctx.page.meta.web_editor;

	var each_blocks = [];

	for (var i = 0; i < each_value_2.length; i += 1) {
		each_blocks[i] = create_each_block_2(component, get_each_context_2(ctx, each_value_2, i));
	}

	return {
		c: function create() {
			h3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h3");
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("Web Editor");
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n      ");
			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("ul");

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}
			this.h()
		},

		l: function claim(nodes) {
			h3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "H3", {}, false);
			var h3_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(h3);

			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(h3_nodes, "Web Editor");
			h3_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(nodes, "\n      ");

			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "UL", {}, false);
			var ul_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(ul_nodes);
			}

			ul_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(h3, file, 34, 6, 1025);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(ul, file, 35, 6, 1051);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(h3, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text, h3);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(text_1, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(ul, target, anchor);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(ul, null);
			}
		},

		p: function update(changed, ctx) {
			if (changed.page) {
				each_value_2 = ctx.page.meta.web_editor;

				for (var i = 0; i < each_value_2.length; i += 1) {
					const child_ctx = get_each_context_2(ctx, each_value_2, i);

					if (each_blocks[i]) {
						each_blocks[i].p(changed, child_ctx);
					} else {
						each_blocks[i] = create_each_block_2(component, child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(ul, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}
				each_blocks.length = each_value_2.length;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(h3);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(text_1);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(ul);
			}

			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["destroyEach"])(each_blocks, detach);
		}
	};
}

// (45:8) {#each page.meta.graphic_design_liason as designer}
function create_each_block_3(component, ctx) {
	var li, a, raw_value = ctx.designer.title.rendered, a_href_value;

	return {
		c: function create() {
			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("li");
			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("a");
			this.h()
		},

		l: function claim(nodes) {
			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "LI", {}, false);
			var li_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(li);

			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(li_nodes, "A", { rel: true, href: true }, false);
			var a_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			a_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			li_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			a.rel = "prefetch";
			a.href = a_href_value = "/contributors/" + ctx.designer.slug;
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(a, file, 45, 14, 1413);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(li, file, 45, 10, 1409);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(li, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(a, li);
			a.innerHTML = raw_value;
		},

		p: function update(changed, ctx) {
			if ((changed.page) && raw_value !== (raw_value = ctx.designer.title.rendered)) {
				a.innerHTML = raw_value;
			}

			if ((changed.page) && a_href_value !== (a_href_value = "/contributors/" + ctx.designer.slug)) {
				a.href = a_href_value;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(li);
			}
		}
	};
}

// (42:4) {#if page.meta.graphic_design_liason}
function create_if_block_3(component, ctx) {
	var h3, text, text_1, ul;

	var each_value_3 = ctx.page.meta.graphic_design_liason;

	var each_blocks = [];

	for (var i = 0; i < each_value_3.length; i += 1) {
		each_blocks[i] = create_each_block_3(component, get_each_context_3(ctx, each_value_3, i));
	}

	return {
		c: function create() {
			h3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h3");
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("Graphic Designer Liason");
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n      ");
			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("ul");

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}
			this.h()
		},

		l: function claim(nodes) {
			h3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "H3", {}, false);
			var h3_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(h3);

			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(h3_nodes, "Graphic Designer Liason");
			h3_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(nodes, "\n      ");

			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "UL", {}, false);
			var ul_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(ul_nodes);
			}

			ul_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(h3, file, 42, 6, 1295);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(ul, file, 43, 6, 1334);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(h3, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text, h3);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(text_1, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(ul, target, anchor);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(ul, null);
			}
		},

		p: function update(changed, ctx) {
			if (changed.page) {
				each_value_3 = ctx.page.meta.graphic_design_liason;

				for (var i = 0; i < each_value_3.length; i += 1) {
					const child_ctx = get_each_context_3(ctx, each_value_3, i);

					if (each_blocks[i]) {
						each_blocks[i].p(changed, child_ctx);
					} else {
						each_blocks[i] = create_each_block_3(component, child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(ul, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}
				each_blocks.length = each_value_3.length;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(h3);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(text_1);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(ul);
			}

			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["destroyEach"])(each_blocks, detach);
		}
	};
}

// (53:8) {#each page.meta.site_design as designer}
function create_each_block_4(component, ctx) {
	var li, a, raw_value = ctx.designer.title.rendered, a_href_value;

	return {
		c: function create() {
			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("li");
			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("a");
			this.h()
		},

		l: function claim(nodes) {
			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "LI", {}, false);
			var li_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(li);

			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(li_nodes, "A", { rel: true, href: true }, false);
			var a_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			a_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			li_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			a.rel = "prefetch";
			a.href = a_href_value = "/contributors/" + ctx.designer.slug;
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(a, file, 53, 14, 1681);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(li, file, 53, 10, 1677);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(li, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(a, li);
			a.innerHTML = raw_value;
		},

		p: function update(changed, ctx) {
			if ((changed.page) && raw_value !== (raw_value = ctx.designer.title.rendered)) {
				a.innerHTML = raw_value;
			}

			if ((changed.page) && a_href_value !== (a_href_value = "/contributors/" + ctx.designer.slug)) {
				a.href = a_href_value;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(li);
			}
		}
	};
}

// (50:4) {#if page.meta.site_design}
function create_if_block_4(component, ctx) {
	var h3, text, text_1, ul;

	var each_value_4 = ctx.page.meta.site_design;

	var each_blocks = [];

	for (var i = 0; i < each_value_4.length; i += 1) {
		each_blocks[i] = create_each_block_4(component, get_each_context_4(ctx, each_value_4, i));
	}

	return {
		c: function create() {
			h3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h3");
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("Site Design");
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n      ");
			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("ul");

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}
			this.h()
		},

		l: function claim(nodes) {
			h3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "H3", {}, false);
			var h3_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(h3);

			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(h3_nodes, "Site Design");
			h3_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(nodes, "\n      ");

			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "UL", {}, false);
			var ul_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(ul_nodes);
			}

			ul_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(h3, file, 50, 6, 1585);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(ul, file, 51, 6, 1612);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(h3, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text, h3);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(text_1, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(ul, target, anchor);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(ul, null);
			}
		},

		p: function update(changed, ctx) {
			if (changed.page) {
				each_value_4 = ctx.page.meta.site_design;

				for (var i = 0; i < each_value_4.length; i += 1) {
					const child_ctx = get_each_context_4(ctx, each_value_4, i);

					if (each_blocks[i]) {
						each_blocks[i].p(changed, child_ctx);
					} else {
						each_blocks[i] = create_each_block_4(component, child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(ul, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}
				each_blocks.length = each_value_4.length;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(h3);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(text_1);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(ul);
			}

			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["destroyEach"])(each_blocks, detach);
		}
	};
}

// (61:8) {#each page.meta.site_development as developer}
function create_each_block_5(component, ctx) {
	var li, a, raw_value = ctx.developer.title.rendered, a_href_value;

	return {
		c: function create() {
			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("li");
			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("a");
			this.h()
		},

		l: function claim(nodes) {
			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "LI", {}, false);
			var li_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(li);

			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(li_nodes, "A", { rel: true, href: true }, false);
			var a_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			a_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			li_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			a.rel = "prefetch";
			a.href = a_href_value = "/contributors/" + ctx.developer.slug;
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(a, file, 61, 14, 1965);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(li, file, 61, 10, 1961);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(li, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(a, li);
			a.innerHTML = raw_value;
		},

		p: function update(changed, ctx) {
			if ((changed.page) && raw_value !== (raw_value = ctx.developer.title.rendered)) {
				a.innerHTML = raw_value;
			}

			if ((changed.page) && a_href_value !== (a_href_value = "/contributors/" + ctx.developer.slug)) {
				a.href = a_href_value;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(li);
			}
		}
	};
}

// (58:4) {#if page.meta.site_development}
function create_if_block_5(component, ctx) {
	var h3, text, text_1, ul;

	var each_value_5 = ctx.page.meta.site_development;

	var each_blocks = [];

	for (var i = 0; i < each_value_5.length; i += 1) {
		each_blocks[i] = create_each_block_5(component, get_each_context_5(ctx, each_value_5, i));
	}

	return {
		c: function create() {
			h3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h3");
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("Site Development");
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n      ");
			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("ul");

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}
			this.h()
		},

		l: function claim(nodes) {
			h3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "H3", {}, false);
			var h3_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(h3);

			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(h3_nodes, "Site Development");
			h3_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(nodes, "\n      ");

			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "UL", {}, false);
			var ul_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(ul_nodes);
			}

			ul_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(h3, file, 58, 6, 1858);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(ul, file, 59, 6, 1890);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(h3, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text, h3);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(text_1, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(ul, target, anchor);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(ul, null);
			}
		},

		p: function update(changed, ctx) {
			if (changed.page) {
				each_value_5 = ctx.page.meta.site_development;

				for (var i = 0; i < each_value_5.length; i += 1) {
					const child_ctx = get_each_context_5(ctx, each_value_5, i);

					if (each_blocks[i]) {
						each_blocks[i].p(changed, child_ctx);
					} else {
						each_blocks[i] = create_each_block_5(component, child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(ul, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}
				each_blocks.length = each_value_5.length;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(h3);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(text_1);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(ul);
			}

			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["destroyEach"])(each_blocks, detach);
		}
	};
}

function get_each_context(ctx, list, i) {
	const child_ctx = Object.create(ctx);
	child_ctx.editor = list[i];
	child_ctx.each_value = list;
	child_ctx.editor_index = i;
	return child_ctx;
}

function get_each_context_1(ctx, list, i) {
	const child_ctx = Object.create(ctx);
	child_ctx.publisher = list[i];
	child_ctx.each_value_1 = list;
	child_ctx.publisher_index = i;
	return child_ctx;
}

function get_each_context_2(ctx, list, i) {
	const child_ctx = Object.create(ctx);
	child_ctx.editor = list[i];
	child_ctx.each_value_2 = list;
	child_ctx.editor_index_1 = i;
	return child_ctx;
}

function get_each_context_3(ctx, list, i) {
	const child_ctx = Object.create(ctx);
	child_ctx.designer = list[i];
	child_ctx.each_value_3 = list;
	child_ctx.designer_index = i;
	return child_ctx;
}

function get_each_context_4(ctx, list, i) {
	const child_ctx = Object.create(ctx);
	child_ctx.designer = list[i];
	child_ctx.each_value_4 = list;
	child_ctx.designer_index_1 = i;
	return child_ctx;
}

function get_each_context_5(ctx, list, i) {
	const child_ctx = Object.create(ctx);
	child_ctx.developer = list[i];
	child_ctx.each_value_5 = list;
	child_ctx.developer_index = i;
	return child_ctx;
}

function About(options) {
	this._debugName = '<About>';
	if (!options || (!options.target && !options.root)) throw new Error("'target' is a required option");
	Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options);
	this._state = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])({}, options.data);
	if (!('page' in this._state)) console.warn("<About> was created without expected data property 'page'");
	this._intro = true;

	if (!options.root) {
		this._oncreate = [];
		this._beforecreate = [];
		this._aftercreate = [];
	}

	this._fragment = create_main_fragment(this, this._state);

	if (options.target) {
		var nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(options.target);
		options.hydrate ? this._fragment.l(nodes) : this._fragment.c();
		nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
		this._mount(options.target, options.anchor);

		this._lock = true;
		Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["callAll"])(this._beforecreate);
		Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["callAll"])(this._oncreate);
		Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["callAll"])(this._aftercreate);
		this._lock = false;
	}
}

Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])(About.prototype, svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["protoDev"]);

About.prototype._checkReadOnly = function _checkReadOnly(newState) {
};

About.preload = preload;

if (true) {
	const { configure, register, reload } = __webpack_require__(/*! ./node_modules/svelte-loader/lib/hot-api.js */ "./node_modules/svelte-loader/lib/hot-api.js");

	module.hot.accept();

	if (!module.hot.data) {
		// initial load
		configure({});
		About = register("src/routes/about.html", About);
	} else {
		// hot update
		About = reload("src/routes/about.html", About);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (About);


/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9jb21wb25lbnRzL1RpdGxlLmh0bWwiLCJ3ZWJwYWNrOi8vLy4vc3JjL3JvdXRlcy9hYm91dC5odG1sIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3NCQUN5QyxLQUFLOzs7Ozt1QkFBTCxLQUFLOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7c0JDd0U3QixDQUFDLEVBQUUsTUFBTSxFQUFFLEtBQUssRUFBRSxFQUFFO0FBQ2pDLEVBQUUsTUFBTSxVQUFVLEdBQUcsbUJBQW1CO0FBQ3hDLElBQUksT0FBTztBQUNYLE1BQU0sNENBQTRDO0FBQ2xELE1BQU0sa0NBQWtDO0FBQ3hDLE1BQU0sa0NBQWtDO0FBQ3hDLE1BQU0sNkNBQTZDO0FBQ25ELE1BQU0sbUNBQW1DO0FBQ3pDLE1BQU0sdUNBQXVDO0FBQzdDLElBQUksR0FBRztBQUNQLEVBQUUsTUFBTSxHQUFHLEdBQUcsTUFBTSxJQUFJLENBQUMsS0FBSyxDQUFDLENBQUMsbUJBQW1CLEVBQUUsVUFBVSxDQUFDLENBQUMsQ0FBQztBQUNsRSxFQUFFLElBQUksQ0FBQyxHQUFHLENBQUMsRUFBRSxFQUFFO0FBQ2YsSUFBSSxNQUFNLE9BQU8sR0FBRyxNQUFNLEdBQUcsQ0FBQyxJQUFJLEVBQUU7QUFDcEMsSUFBSSxPQUFPLElBQUksQ0FBQyxLQUFLLENBQUMsR0FBRyxDQUFDLE1BQU0sRUFBRSxPQUFPLENBQUMsQ0FBQztBQUMzQyxHQUFHO0FBQ0gsRUFBRSxNQUFNLElBQUksR0FBRyxNQUFNLEdBQUcsQ0FBQyxJQUFJLEVBQUU7QUFDL0IsRUFBRSxPQUFPLEVBQUUsSUFBSSxFQUFFLElBQUksRUFBRTtBQUN2QixDQUFDOzs7Ozt1SEE1RU0sSUFBSSxDQUFDLE9BQU8sQ0FBQyxRQUFROzs7Ozs7Ozs7cUJBR3ZCLElBQUksQ0FBQyxJQUFJLENBQUMsb0JBQW9COzt1QkFROUIsSUFBSSxDQUFDLElBQUksQ0FBQyxVQUFVOzt1QkFRcEIsSUFBSSxDQUFDLElBQUksQ0FBQyxVQUFVOzt1QkFRcEIsSUFBSSxDQUFDLElBQUksQ0FBQyxxQkFBcUI7O3VCQVEvQixJQUFJLENBQUMsSUFBSSxDQUFDLFdBQVc7O3VCQVFyQixJQUFJLENBQUMsSUFBSSxDQUFDLGdCQUFnQjs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt3REEzQ3hCLElBQUksQ0FBQyxPQUFPLENBQUMsUUFBUTs7OztXQUd2QixJQUFJLENBQUMsSUFBSSxDQUFDLG9CQUFvQjs7Ozs7Ozs7Ozs7OztXQVE5QixJQUFJLENBQUMsSUFBSSxDQUFDLFVBQVU7Ozs7Ozs7Ozs7Ozs7V0FRcEIsSUFBSSxDQUFDLElBQUksQ0FBQyxVQUFVOzs7Ozs7Ozs7Ozs7O1dBUXBCLElBQUksQ0FBQyxJQUFJLENBQUMscUJBQXFCOzs7Ozs7Ozs7Ozs7O1dBUS9CLElBQUksQ0FBQyxJQUFJLENBQUMsV0FBVzs7Ozs7Ozs7Ozs7OztXQVFyQixJQUFJLENBQUMsSUFBSSxDQUFDLGdCQUFnQjs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs0QkFwQ3VDLE1BQU0sQ0FBQyxLQUFLLENBQUMsUUFBUTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7a0RBQTFDLE1BQU0sQ0FBQyxJQUFJOzs7Ozs7Ozs7Ozs7d0RBQVUsTUFBTSxDQUFDLEtBQUssQ0FBQyxRQUFROzs7O2lGQUExQyxNQUFNLENBQUMsSUFBSTs7Ozs7Ozs7Ozs7Ozs7Ozs7c0JBRGpELElBQUksQ0FBQyxJQUFJLENBQUMsb0JBQW9COzs7O2dDQUFuQzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3FCQUFLLElBQUksQ0FBQyxJQUFJLENBQUMsb0JBQW9COzttQ0FBbkM7Ozs7Ozs7Ozs7Ozs7OztvQ0FBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OzRCQVNtRSxTQUFTLENBQUMsS0FBSyxDQUFDLFFBQVE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2tEQUFoRCxTQUFTLENBQUMsSUFBSTs7Ozs7Ozs7Ozs7O3dEQUFVLFNBQVMsQ0FBQyxLQUFLLENBQUMsUUFBUTs7OztpRkFBaEQsU0FBUyxDQUFDLElBQUk7Ozs7Ozs7Ozs7Ozs7Ozs7O3dCQURwRCxJQUFJLENBQUMsSUFBSSxDQUFDLFVBQVU7Ozs7a0NBQXpCOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7dUJBQUssSUFBSSxDQUFDLElBQUksQ0FBQyxVQUFVOztxQ0FBekI7Ozs7Ozs7Ozs7Ozs7OztzQ0FBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OzRCQVNnRSxNQUFNLENBQUMsS0FBSyxDQUFDLFFBQVE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2tEQUExQyxNQUFNLENBQUMsSUFBSTs7Ozs7Ozs7Ozs7O3dEQUFVLE1BQU0sQ0FBQyxLQUFLLENBQUMsUUFBUTs7OztpRkFBMUMsTUFBTSxDQUFDLElBQUk7Ozs7Ozs7Ozs7Ozs7Ozs7O3dCQURqRCxJQUFJLENBQUMsSUFBSSxDQUFDLFVBQVU7Ozs7a0NBQXpCOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7dUJBQUssSUFBSSxDQUFDLElBQUksQ0FBQyxVQUFVOztxQ0FBekI7Ozs7Ozs7Ozs7Ozs7OztzQ0FBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OzRCQVNrRSxRQUFRLENBQUMsS0FBSyxDQUFDLFFBQVE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2tEQUE5QyxRQUFRLENBQUMsSUFBSTs7Ozs7Ozs7Ozs7O3dEQUFVLFFBQVEsQ0FBQyxLQUFLLENBQUMsUUFBUTs7OztpRkFBOUMsUUFBUSxDQUFDLElBQUk7Ozs7Ozs7Ozs7Ozs7Ozs7O3dCQURuRCxJQUFJLENBQUMsSUFBSSxDQUFDLHFCQUFxQjs7OztrQ0FBcEM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt1QkFBSyxJQUFJLENBQUMsSUFBSSxDQUFDLHFCQUFxQjs7cUNBQXBDOzs7Ozs7Ozs7Ozs7Ozs7c0NBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs0QkFTa0UsUUFBUSxDQUFDLEtBQUssQ0FBQyxRQUFROzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztrREFBOUMsUUFBUSxDQUFDLElBQUk7Ozs7Ozs7Ozs7Ozt3REFBVSxRQUFRLENBQUMsS0FBSyxDQUFDLFFBQVE7Ozs7aUZBQTlDLFFBQVEsQ0FBQyxJQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozt3QkFEbkQsSUFBSSxDQUFDLElBQUksQ0FBQyxXQUFXOzs7O2tDQUExQjs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3VCQUFLLElBQUksQ0FBQyxJQUFJLENBQUMsV0FBVzs7cUNBQTFCOzs7Ozs7Ozs7Ozs7Ozs7c0NBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs0QkFTbUUsU0FBUyxDQUFDLEtBQUssQ0FBQyxRQUFROzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztrREFBaEQsU0FBUyxDQUFDLElBQUk7Ozs7Ozs7Ozs7Ozt3REFBVSxTQUFTLENBQUMsS0FBSyxDQUFDLFFBQVE7Ozs7aUZBQWhELFNBQVMsQ0FBQyxJQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozt3QkFEcEQsSUFBSSxDQUFDLElBQUksQ0FBQyxnQkFBZ0I7Ozs7a0NBQS9COzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7dUJBQUssSUFBSSxDQUFDLElBQUksQ0FBQyxnQkFBZ0I7O3FDQUEvQjs7Ozs7Ozs7Ozs7Ozs7O3NDQUFBIiwiZmlsZSI6IjgxYmRjMzU0MDQwZjI0OTQxYjNkL2Fib3V0LmFib3V0LmpzIiwic291cmNlc0NvbnRlbnQiOlsiPGRpdiBjbGFzcz1cImMxMiB6MlwiPlxuICA8aDEgY2xhc3M9XCJjbzIgYzggc20tY280IHNtLWM0XCI+e0BodG1sIHRpdGxlfTwvaDE+XG48L2Rpdj5cblxuPHN0eWxlPlxuICBoMSB7XG4gICAgZm9udC1zaXplOiAzcmVtO1xuICAgIGxpbmUtaGVpZ2h0OiAwLjk7XG4gICAgZm9udC13ZWlnaHQ6IDQwMDtcbiAgICBtYXJnaW4tYm90dG9tOiAzcmVtO1xuICB9XG4gIEBtZWRpYSAobWluLXdpZHRoOiA3NjhweCkge1xuICAgIGgxIHtcbiAgICAgIGZvbnQtc2l6ZTogNHJlbTtcbiAgICB9XG4gIH1cbjwvc3R5bGU+IiwiPHN2ZWx0ZTpoZWFkPlxuXHQ8dGl0bGU+QWJvdXQ8L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cblxuPFRpdGxlIHRpdGxlPVwiQWJvdXRcIi8+XG48ZGl2IGNsYXNzPVwieCB4d1wiPlxuICA8ZGl2IGNsYXNzPVwiZG4gc20tZGIgYzIgcDFcIj5cbiAgICA8dWw+XG4gICAgICA8bGk+PGEgcmVsPVwicHJlZmV0Y2hcIiBocmVmPVwiL2Fib3V0XCI+QWJvdXQ8L2E+PC9saT5cbiAgICAgIDxsaT48YSByZWw9XCJwcmVmZXRjaFwiIGhyZWY9XCIvc3VwcG9ydFwiPlN1cHBvcnQ8L2E+PC9saT5cbiAgICAgIDxsaT48YSByZWw9XCJwcmVmZXRjaFwiIGhyZWY9XCIvc2VhcmNoXCI+U2VhcmNoPC9hPjwvbGk+XG4gICAgPC91bD5cbiAgPC9kaXY+XG4gIDxkaXYgY2xhc3M9XCJjMTIgc20tYzQgcDFcIj5cbiAgICB7QGh0bWwgcGFnZS5jb250ZW50LnJlbmRlcmVkfVxuICA8L2Rpdj5cbiAgPGRpdiBjbGFzcz1cImMxMiBzbS1jNCBwMVwiPlxuICAgIHsjaWYgcGFnZS5tZXRhLmNvb3JkaW5hdGluZ19lZGl0b3JzfVxuICAgICAgPGgzPkNvb3JkaW5hdGluZyBFZGl0b3JzPC9oMz5cbiAgICAgIDx1bD5cbiAgICAgICAgeyNlYWNoIHBhZ2UubWV0YS5jb29yZGluYXRpbmdfZWRpdG9ycyBhcyBlZGl0b3J9XG4gICAgICAgICAgPGxpPjxhIHJlbD1cInByZWZldGNoXCIgaHJlZj1cIi9jb250cmlidXRvcnMve2VkaXRvci5zbHVnfVwiPntAaHRtbCBlZGl0b3IudGl0bGUucmVuZGVyZWR9PC9hPjwvbGk+XG4gICAgICAgIHsvZWFjaH1cbiAgICAgIDwvdWw+XG4gICAgey9pZn1cbiAgICB7I2lmIHBhZ2UubWV0YS5wdWJsaXNoZXJzfVxuICAgICAgPGgzPlB1Ymxpc2hlcnM8L2gzPlxuICAgICAgPHVsPlxuICAgICAgICB7I2VhY2ggcGFnZS5tZXRhLnB1Ymxpc2hlcnMgYXMgcHVibGlzaGVyfVxuICAgICAgICAgIDxsaT48YSByZWw9XCJwcmVmZXRjaFwiIGhyZWY9XCIvY29udHJpYnV0b3JzL3twdWJsaXNoZXIuc2x1Z31cIj57QGh0bWwgcHVibGlzaGVyLnRpdGxlLnJlbmRlcmVkfTwvYT48L2xpPlxuICAgICAgICB7L2VhY2h9XG4gICAgICA8L3VsPlxuICAgIHsvaWZ9XG4gICAgeyNpZiBwYWdlLm1ldGEud2ViX2VkaXRvcn1cbiAgICAgIDxoMz5XZWIgRWRpdG9yPC9oMz5cbiAgICAgIDx1bD5cbiAgICAgICAgeyNlYWNoIHBhZ2UubWV0YS53ZWJfZWRpdG9yIGFzIGVkaXRvcn1cbiAgICAgICAgICA8bGk+PGEgcmVsPVwicHJlZmV0Y2hcIiBocmVmPVwiL2NvbnRyaWJ1dG9ycy97ZWRpdG9yLnNsdWd9XCI+e0BodG1sIGVkaXRvci50aXRsZS5yZW5kZXJlZH08L2E+PC9saT5cbiAgICAgICAgey9lYWNofVxuICAgICAgPC91bD5cbiAgICB7L2lmfVxuICAgIHsjaWYgcGFnZS5tZXRhLmdyYXBoaWNfZGVzaWduX2xpYXNvbn1cbiAgICAgIDxoMz5HcmFwaGljIERlc2lnbmVyIExpYXNvbjwvaDM+XG4gICAgICA8dWw+XG4gICAgICAgIHsjZWFjaCBwYWdlLm1ldGEuZ3JhcGhpY19kZXNpZ25fbGlhc29uIGFzIGRlc2lnbmVyfVxuICAgICAgICAgIDxsaT48YSByZWw9XCJwcmVmZXRjaFwiIGhyZWY9XCIvY29udHJpYnV0b3JzL3tkZXNpZ25lci5zbHVnfVwiPntAaHRtbCBkZXNpZ25lci50aXRsZS5yZW5kZXJlZH08L2E+PC9saT5cbiAgICAgICAgey9lYWNofVxuICAgICAgPC91bD5cbiAgICB7L2lmfVxuICAgIHsjaWYgcGFnZS5tZXRhLnNpdGVfZGVzaWdufVxuICAgICAgPGgzPlNpdGUgRGVzaWduPC9oMz5cbiAgICAgIDx1bD5cbiAgICAgICAgeyNlYWNoIHBhZ2UubWV0YS5zaXRlX2Rlc2lnbiBhcyBkZXNpZ25lcn1cbiAgICAgICAgICA8bGk+PGEgcmVsPVwicHJlZmV0Y2hcIiBocmVmPVwiL2NvbnRyaWJ1dG9ycy97ZGVzaWduZXIuc2x1Z31cIj57QGh0bWwgZGVzaWduZXIudGl0bGUucmVuZGVyZWR9PC9hPjwvbGk+XG4gICAgICAgIHsvZWFjaH1cbiAgICAgIDwvdWw+XG4gICAgey9pZn1cbiAgICB7I2lmIHBhZ2UubWV0YS5zaXRlX2RldmVsb3BtZW50fVxuICAgICAgPGgzPlNpdGUgRGV2ZWxvcG1lbnQ8L2gzPlxuICAgICAgPHVsPlxuICAgICAgICB7I2VhY2ggcGFnZS5tZXRhLnNpdGVfZGV2ZWxvcG1lbnQgYXMgZGV2ZWxvcGVyfVxuICAgICAgICAgIDxsaT48YSByZWw9XCJwcmVmZXRjaFwiIGhyZWY9XCIvY29udHJpYnV0b3JzL3tkZXZlbG9wZXIuc2x1Z31cIj57QGh0bWwgZGV2ZWxvcGVyLnRpdGxlLnJlbmRlcmVkfTwvYT48L2xpPlxuICAgICAgICB7L2VhY2h9XG4gICAgICA8L3VsPlxuICAgIHsvaWZ9XG4gIDwvZGl2PlxuPC9kaXY+XG5cbjxzY3JpcHQ+XG4gIGV4cG9ydCBkZWZhdWx0IHtcbiAgICBjb21wb25lbnRzOiB7XG4gICAgICBUaXRsZTogJy4uLy4uL2NvbXBvbmVudHMvVGl0bGUuaHRtbCdcbiAgICB9LFxuICAgIGFzeW5jIHByZWxvYWQoeyBwYXJhbXMsIHF1ZXJ5IH0pIHtcbiAgICAgIGNvbnN0IG1hc2tGaWVsZHMgPSAnY29udGVudC9yZW5kZXJlZCwnICtcbiAgICAgICAgJ21ldGEoJyArXG4gICAgICAgICAgJ2Nvb3JkaW5hdGluZ19lZGl0b3JzKHRpdGxlL3JlbmRlcmVkLHNsdWcpLCcgK1xuICAgICAgICAgICdwdWJsaXNoZXJzKHRpdGxlL3JlbmRlcmVkLHNsdWcpLCcgK1xuICAgICAgICAgICd3ZWJfZWRpdG9yKHRpdGxlL3JlbmRlcmVkLHNsdWcpLCcgK1xuICAgICAgICAgICdncmFwaGljX2Rlc2lnbl9saWFzb24odGl0bGUvcmVuZGVyZWQsc2x1ZyksJyArXG4gICAgICAgICAgJ3NpdGVfZGVzaWduKHRpdGxlL3JlbmRlcmVkLHNsdWcpLCcgK1xuICAgICAgICAgICdzaXRlX2RldmVsb3BtZW50KHRpdGxlL3JlbmRlcmVkLHNsdWcpJyArXG4gICAgICAgICcpJ1xuICAgICAgY29uc3QgcmVzID0gYXdhaXQgdGhpcy5mZXRjaChgL2Fib3V0Lmpzb24/ZmllbGRzPSR7bWFza0ZpZWxkc31gKVxuICAgICAgaWYgKCFyZXMub2spIHtcbiAgICAgICAgY29uc3QgbWVzc2FnZSA9IGF3YWl0IHJlcy50ZXh0KClcbiAgICAgICAgcmV0dXJuIHRoaXMuZXJyb3IocmVzLnN0YXR1cywgbWVzc2FnZSk7XG4gICAgICB9XG4gICAgICBjb25zdCBkYXRhID0gYXdhaXQgcmVzLmpzb24oKVxuICAgICAgcmV0dXJuIHsgcGFnZTogZGF0YSB9XG4gICAgfVxuICB9O1xuPC9zY3JpcHQ+Il0sInNvdXJjZVJvb3QiOiIifQ==