(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["archive"],{

/***/ "./src/routes/archive/index.html":
/*!***************************************!*\
  !*** ./src/routes/archive/index.html ***!
  \***************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/shared.js */ "./node_modules/svelte/shared.js");
/* src/routes/archive/index.html generated by Svelte v2.9.9 */


function preload() {
  return this.redirect(301, 'archive/articles')
};

const file = "src/routes/archive/index.html";

function create_main_fragment(component, ctx) {

	return {
		c: svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["noop"],

		l: svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["noop"],

		m: svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["noop"],

		p: svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["noop"]
	};
}

function Index(options) {
	this._debugName = '<Index>';
	if (!options || (!options.target && !options.root)) throw new Error("'target' is a required option");
	Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options);
	this._state = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])({}, options.data);
	this._intro = true;

	this._fragment = create_main_fragment(this, this._state);

	if (options.target) {
		var nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(options.target);
		options.hydrate ? this._fragment.l(nodes) : this._fragment.c();
		nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
		this._mount(options.target, options.anchor);
	}
}

Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])(Index.prototype, svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["protoDev"]);

Index.prototype._checkReadOnly = function _checkReadOnly(newState) {
};

Index.preload = preload;

if (true) {
	const { configure, register, reload } = __webpack_require__(/*! ./node_modules/svelte-loader/lib/hot-api.js */ "./node_modules/svelte-loader/lib/hot-api.js");

	module.hot.accept();

	if (!module.hot.data) {
		// initial load
		configure({});
		Index = register("src/routes/archive/index.html", Index);
	} else {
		// hot update
		Index = reload("src/routes/archive/index.html", Index);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Index);


/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL2FyY2hpdmUvaW5kZXguaHRtbCJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7Z0JBRVcsR0FBRztBQUNWLEVBQUUsT0FBTyxJQUFJLENBQUMsUUFBUSxDQUFDLEdBQUcsRUFBRSxrQkFBa0IsQ0FBQztBQUMvQyxDQUFDIiwiZmlsZSI6IjgxYmRjMzU0MDQwZjI0OTQxYjNkL2FyY2hpdmUuYXJjaGl2ZS5qcyIsInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG4gIGV4cG9ydCBkZWZhdWx0IHtcbiAgICBwcmVsb2FkKCkge1xuICAgICAgcmV0dXJuIHRoaXMucmVkaXJlY3QoMzAxLCAnYXJjaGl2ZS9hcnRpY2xlcycpXG4gICAgfVxuICB9XG48L3NjcmlwdD4iXSwic291cmNlUm9vdCI6IiJ9