(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["articles_$slug"],{

/***/ "./components/Title.html":
/*!*******************************!*\
  !*** ./components/Title.html ***!
  \*******************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/shared.js */ "./node_modules/svelte/shared.js");
/* components/Title.html generated by Svelte v2.9.9 */


const file = "components/Title.html";

function add_css() {
	var style = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("style");
	style.id = 'svelte-quv5ds-style';
	style.textContent = "h1.svelte-quv5ds{font-size:3rem;line-height:0.9;font-weight:400;margin-bottom:3rem}@media(min-width: 768px){h1.svelte-quv5ds{font-size:4rem}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiVGl0bGUuaHRtbCIsInNvdXJjZXMiOlsiVGl0bGUuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyI8ZGl2IGNsYXNzPVwiYzEyIHoyXCI+XG4gIDxoMSBjbGFzcz1cImNvMiBjOCBzbS1jbzQgc20tYzRcIj57QGh0bWwgdGl0bGV9PC9oMT5cbjwvZGl2PlxuXG48c3R5bGU+XG4gIGgxIHtcbiAgICBmb250LXNpemU6IDNyZW07XG4gICAgbGluZS1oZWlnaHQ6IDAuOTtcbiAgICBmb250LXdlaWdodDogNDAwO1xuICAgIG1hcmdpbi1ib3R0b206IDNyZW07XG4gIH1cbiAgQG1lZGlhIChtaW4td2lkdGg6IDc2OHB4KSB7XG4gICAgaDEge1xuICAgICAgZm9udC1zaXplOiA0cmVtO1xuICAgIH1cbiAgfVxuPC9zdHlsZT4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBS0UsRUFBRSxjQUFDLENBQUMsQUFDRixTQUFTLENBQUUsSUFBSSxDQUNmLFdBQVcsQ0FBRSxHQUFHLENBQ2hCLFdBQVcsQ0FBRSxHQUFHLENBQ2hCLGFBQWEsQ0FBRSxJQUFJLEFBQ3JCLENBQUMsQUFDRCxNQUFNLEFBQUMsWUFBWSxLQUFLLENBQUMsQUFBQyxDQUFDLEFBQ3pCLEVBQUUsY0FBQyxDQUFDLEFBQ0YsU0FBUyxDQUFFLElBQUksQUFDakIsQ0FBQyxBQUNILENBQUMifQ== */";
	Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(style, document.head);
}

function create_main_fragment(component, ctx) {
	var div, h1;

	return {
		c: function create() {
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			h1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h1");
			this.h()
		},

		l: function claim(nodes) {
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			h1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "H1", { class: true }, false);
			var h1_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);

			h1_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			div_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			h1.className = "co2 c8 sm-co4 sm-c4 svelte-quv5ds";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(h1, file, 1, 2, 23);
			div.className = "c12 z2";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div, file, 0, 0, 0);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(div, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(h1, div);
			h1.innerHTML = ctx.title;
		},

		p: function update(changed, ctx) {
			if (changed.title) {
				h1.innerHTML = ctx.title;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(div);
			}
		}
	};
}

function Title(options) {
	this._debugName = '<Title>';
	if (!options || (!options.target && !options.root)) throw new Error("'target' is a required option");
	Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options);
	this._state = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])({}, options.data);
	if (!('title' in this._state)) console.warn("<Title> was created without expected data property 'title'");
	this._intro = true;

	if (!document.getElementById("svelte-quv5ds-style")) add_css();

	this._fragment = create_main_fragment(this, this._state);

	if (options.target) {
		var nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(options.target);
		options.hydrate ? this._fragment.l(nodes) : this._fragment.c();
		nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
		this._mount(options.target, options.anchor);
	}
}

Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])(Title.prototype, svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["protoDev"]);

Title.prototype._checkReadOnly = function _checkReadOnly(newState) {
};

if (true) {
	const { configure, register, reload } = __webpack_require__(/*! ./node_modules/svelte-loader/lib/hot-api.js */ "./node_modules/svelte-loader/lib/hot-api.js");

	module.hot.accept();

	if (!module.hot.data) {
		// initial load
		configure({});
		Title = register("components/Title.html", Title);
	} else {
		// hot update
		Title = reload("components/Title.html", Title);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Title);


/***/ }),

/***/ "./node_modules/dayjs/dayjs.min.js":
/*!*****************************************!*\
  !*** ./node_modules/dayjs/dayjs.min.js ***!
  \*****************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

!function(t,e){ true?module.exports=e():undefined}(this,function(){"use strict";var t="millisecond",e="second",n="minute",r="hour",s="day",i="week",a="month",u="year",c=/^(\d{4})-?(\d{1,2})-?(\d{0,2})(.*?(\d{1,2}):(\d{1,2}):(\d{1,2}))?.?(\d{1,3})?$/,o=/\[.*?\]|Y{2,4}|M{1,4}|D{1,2}|d{1,4}|H{1,2}|h{1,2}|a|A|m{1,2}|s{1,2}|Z{1,2}|SSS/g,h={name:"en",weekdays:"Sunday_Monday_Tuesday_Wednesday_Thursday_Friday_Saturday".split("_"),months:"January_February_March_April_May_June_July_August_September_October_November_December".split("_")},d=function(t,e,n){var r=String(t);return!r||r.length>=e?t:""+Array(e+1-r.length).join(n)+t},$={padStart:d,padZoneStr:function(t){var e=Math.abs(t),n=Math.floor(e/60),r=e%60;return(t<=0?"+":"-")+d(n,2,"0")+":"+d(r,2,"0")},monthDiff:function(t,e){var n=12*(e.year()-t.year())+(e.month()-t.month()),r=t.clone().add(n,"months"),s=e-r<0,i=t.clone().add(n+(s?-1:1),"months");return Number(-(n+(e-r)/(s?r-i:i-r)))},absFloor:function(t){return t<0?Math.ceil(t)||0:Math.floor(t)},prettyUnit:function(c){return{M:a,y:u,w:i,d:s,h:r,m:n,s:e,ms:t}[c]||String(c||"").toLowerCase().replace(/s$/,"")},isUndefined:function(t){return void 0===t}},f="en",l={};l[f]=h;var m=function(t){return t instanceof D},y=function(t,e,n){var r;if(!t)return null;if("string"==typeof t)l[t]&&(r=t),e&&(l[t]=e,r=t);else{var s=t.name;l[s]=t,r=s}return n||(f=r),r},M=function(t,e){if(m(t))return t.clone();var n=e||{};return n.date=t,new D(n)},S=function(t,e){return M(t,{locale:e.$L})},p=$;p.parseLocale=y,p.isDayjs=m,p.wrapper=S;var D=function(){function h(t){this.parse(t)}var d=h.prototype;return d.parse=function(t){var e,n;this.$d=null===(e=t.date)?new Date(NaN):p.isUndefined(e)?new Date:e instanceof Date?e:"string"==typeof e&&/.*[^Z]$/i.test(e)&&(n=e.match(c))?new Date(n[1],n[2]-1,n[3]||1,n[5]||0,n[6]||0,n[7]||0,n[8]||0):new Date(e),this.init(t)},d.init=function(t){this.$y=this.$d.getFullYear(),this.$M=this.$d.getMonth(),this.$D=this.$d.getDate(),this.$W=this.$d.getDay(),this.$H=this.$d.getHours(),this.$m=this.$d.getMinutes(),this.$s=this.$d.getSeconds(),this.$ms=this.$d.getMilliseconds(),this.$L=this.$L||y(t.locale,null,!0)||f},d.$utils=function(){return p},d.isValid=function(){return!("Invalid Date"===this.$d.toString())},d.$compare=function(t){return this.valueOf()-M(t).valueOf()},d.isSame=function(t){return 0===this.$compare(t)},d.isBefore=function(t){return this.$compare(t)<0},d.isAfter=function(t){return this.$compare(t)>0},d.year=function(){return this.$y},d.month=function(){return this.$M},d.day=function(){return this.$W},d.date=function(){return this.$D},d.hour=function(){return this.$H},d.minute=function(){return this.$m},d.second=function(){return this.$s},d.millisecond=function(){return this.$ms},d.unix=function(){return Math.floor(this.valueOf()/1e3)},d.valueOf=function(){return this.$d.getTime()},d.startOf=function(t,c){var o=this,h=!!p.isUndefined(c)||c,d=function(t,e){var n=S(new Date(o.$y,e,t),o);return h?n:n.endOf(s)},$=function(t,e){return S(o.toDate()[t].apply(o.toDate(),h?[0,0,0,0].slice(e):[23,59,59,999].slice(e)),o)};switch(p.prettyUnit(t)){case u:return h?d(1,0):d(31,11);case a:return h?d(1,this.$M):d(0,this.$M+1);case i:return d(h?this.$D-this.$W:this.$D+(6-this.$W),this.$M);case s:case"date":return $("setHours",0);case r:return $("setMinutes",1);case n:return $("setSeconds",2);case e:return $("setMilliseconds",3);default:return this.clone()}},d.endOf=function(t){return this.startOf(t,!1)},d.$set=function(i,c){switch(p.prettyUnit(i)){case s:this.$d.setDate(this.$D+(c-this.$W));break;case"date":this.$d.setDate(c);break;case a:this.$d.setMonth(c);break;case u:this.$d.setFullYear(c);break;case r:this.$d.setHours(c);break;case n:this.$d.setMinutes(c);break;case e:this.$d.setSeconds(c);break;case t:this.$d.setMilliseconds(c)}return this.init(),this},d.set=function(t,e){return this.clone().$set(t,e)},d.add=function(t,c){var o=this;t=Number(t);var h,d=p.prettyUnit(c),$=function(e,n){var r=o.set("date",1).set(e,n+t);return r.set("date",Math.min(o.$D,r.daysInMonth()))};if(d===a)return $(a,this.$M);if(d===u)return $(u,this.$y);switch(d){case n:h=6e4;break;case r:h=36e5;break;case s:h=864e5;break;case i:h=6048e5;break;case e:h=1e3;break;default:h=1}var f=this.valueOf()+t*h;return S(f,this)},d.subtract=function(t,e){return this.add(-1*t,e)},d.format=function(t){var e=this,n=t||"YYYY-MM-DDTHH:mm:ssZ",r=p.padZoneStr(this.$d.getTimezoneOffset()),s=this.$locale(),i=s.weekdays,a=s.months,u=function(t,e,n,r){return t&&t[e]||n[e].substr(0,r)};return n.replace(o,function(t){if(t.indexOf("[")>-1)return t.replace(/\[|\]/g,"");switch(t){case"YY":return String(e.$y).slice(-2);case"YYYY":return String(e.$y);case"M":return String(e.$M+1);case"MM":return p.padStart(e.$M+1,2,"0");case"MMM":return u(s.monthsShort,e.$M,a,3);case"MMMM":return a[e.$M];case"D":return String(e.$D);case"DD":return p.padStart(e.$D,2,"0");case"d":return String(e.$W);case"dd":return u(s.weekdaysMin,e.$W,i,2);case"ddd":return u(s.weekdaysShort,e.$W,i,3);case"dddd":return i[e.$W];case"H":return String(e.$H);case"HH":return p.padStart(e.$H,2,"0");case"h":case"hh":return 0===e.$H?12:p.padStart(e.$H<13?e.$H:e.$H-12,"hh"===t?2:1,"0");case"a":return e.$H<12?"am":"pm";case"A":return e.$H<12?"AM":"PM";case"m":return String(e.$m);case"mm":return p.padStart(e.$m,2,"0");case"s":return String(e.$s);case"ss":return p.padStart(e.$s,2,"0");case"SSS":return p.padStart(e.$ms,3,"0");case"Z":return r;default:return r.replace(":","")}})},d.diff=function(t,c,o){var h=p.prettyUnit(c),d=M(t),$=this-d,f=p.monthDiff(this,d);switch(h){case u:f/=12;break;case a:break;case"quarter":f/=3;break;case i:f=$/6048e5;break;case s:f=$/864e5;break;case r:f=$/36e5;break;case n:f=$/6e4;break;case e:f=$/1e3;break;default:f=$}return o?f:p.absFloor(f)},d.daysInMonth=function(){return this.endOf(a).$D},d.$locale=function(){return l[this.$L]},d.locale=function(t,e){var n=this.clone();return n.$L=y(t,e,!0),n},d.clone=function(){return S(this.toDate(),this)},d.toDate=function(){return new Date(this.$d)},d.toArray=function(){return[this.$y,this.$M,this.$D,this.$H,this.$m,this.$s,this.$ms]},d.toJSON=function(){return this.toISOString()},d.toISOString=function(){return this.toDate().toISOString()},d.toObject=function(){return{years:this.$y,months:this.$M,date:this.$D,hours:this.$H,minutes:this.$m,seconds:this.$s,milliseconds:this.$ms}},d.toString=function(){return this.$d.toUTCString()},h}();return M.extend=function(t,e){return t(e,D,M),M},M.locale=y,M.isDayjs=m,M.en=l[f],M});


/***/ }),

/***/ "./node_modules/is-extendable/index.js":
/*!*********************************************!*\
  !*** ./node_modules/is-extendable/index.js ***!
  \*********************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";
/*!
 * is-extendable <https://github.com/jonschlinkert/is-extendable>
 *
 * Copyright (c) 2015, Jon Schlinkert.
 * Licensed under the MIT License.
 */



module.exports = function isExtendable(val) {
  return typeof val !== 'undefined' && val !== null
    && (typeof val === 'object' || typeof val === 'function');
};


/***/ }),

/***/ "./node_modules/unescape/index.js":
/*!****************************************!*\
  !*** ./node_modules/unescape/index.js ***!
  \****************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";


var extend = __webpack_require__(/*! extend-shallow */ "./node_modules/unescape/node_modules/extend-shallow/index.js");
var regexCache = {};
var all;

var charSets = {
  default: {
    '&quot;': '"',
    '&#34;': '"',

    '&apos;': '\'',
    '&#39;': '\'',

    '&amp;': '&',
    '&#38;': '&',

    '&gt;': '>',
    '&#62;': '>',

    '&lt;': '<',
    '&#60;': '<'
  },
  extras: {
    '&cent;': '¢',
    '&#162;': '¢',

    '&copy;': '©',
    '&#169;': '©',

    '&euro;': '€',
    '&#8364;': '€',

    '&pound;': '£',
    '&#163;': '£',

    '&reg;': '®',
    '&#174;': '®',

    '&yen;': '¥',
    '&#165;': '¥'
  }
};

// don't merge char sets unless "all" is explicitly called
Object.defineProperty(charSets, 'all', {
  get: function() {
    return all || (all = extend({}, charSets.default, charSets.extras));
  }
});

/**
 * Convert HTML entities to HTML characters.
 *
 * @param  {String} `str` String with HTML entities to un-escape.
 * @return {String}
 */

function unescape(str, type) {
  if (!isString(str)) return '';
  var chars = charSets[type || 'default'];
  var regex = toRegex(type, chars);
  return str.replace(regex, function(m) {
    return chars[m];
  });
}

function toRegex(type, chars) {
  if (regexCache[type]) {
    return regexCache[type];
  }
  var keys = Object.keys(chars).join('|');
  var regex = new RegExp('(?=(' + keys + '))\\1', 'g');
  regexCache[type] = regex;
  return regex;
}

/**
 * Returns true if str is a non-empty string
 */

function isString(str) {
  return str && typeof str === 'string';
}

/**
 * Expose charSets
 */

unescape.chars = charSets.default;
unescape.extras = charSets.extras;
// don't trip the "charSets" getter unless it's explicitly called
Object.defineProperty(unescape, 'all', {
  get: function() {
    return charSets.all;
  }
});

/**
 * Expose `unescape`
 */

module.exports = unescape;


/***/ }),

/***/ "./node_modules/unescape/node_modules/extend-shallow/index.js":
/*!********************************************************************!*\
  !*** ./node_modules/unescape/node_modules/extend-shallow/index.js ***!
  \********************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";


var isObject = __webpack_require__(/*! is-extendable */ "./node_modules/is-extendable/index.js");

module.exports = function extend(o/*, objects*/) {
  if (!isObject(o)) { o = {}; }

  var len = arguments.length;
  for (var i = 1; i < len; i++) {
    var obj = arguments[i];

    if (isObject(obj)) {
      assign(o, obj);
    }
  }
  return o;
};

function assign(a, b) {
  for (var key in b) {
    if (hasOwn(b, key)) {
      a[key] = b[key];
    }
  }
}

/**
 * Returns true if the given `key` is an own property of `obj`.
 */

function hasOwn(obj, key) {
  return Object.prototype.hasOwnProperty.call(obj, key);
}


/***/ }),

/***/ "./src/routes/_helpers/date-format.js":
/*!********************************************!*\
  !*** ./src/routes/_helpers/date-format.js ***!
  \********************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "default", function() { return format; });
/* harmony import */ var dayjs__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! dayjs */ "./node_modules/dayjs/dayjs.min.js");
/* harmony import */ var dayjs__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(dayjs__WEBPACK_IMPORTED_MODULE_0__);


function format(date) {
  return dayjs__WEBPACK_IMPORTED_MODULE_0___default()(date).format('MMMM D, YYYY')
}


/***/ }),

/***/ "./src/routes/_helpers/decode-html.js":
/*!********************************************!*\
  !*** ./src/routes/_helpers/decode-html.js ***!
  \********************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "default", function() { return decodehtml; });
/* harmony import */ var unescape__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! unescape */ "./node_modules/unescape/index.js");
/* harmony import */ var unescape__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(unescape__WEBPACK_IMPORTED_MODULE_0__);


function decodehtml(str) {
  return unescape__WEBPACK_IMPORTED_MODULE_0___default()(str, 'all')
}


/***/ }),

/***/ "./src/routes/articles/[slug].html":
/*!*****************************************!*\
  !*** ./src/routes/articles/[slug].html ***!
  \*****************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/shared.js */ "./node_modules/svelte/shared.js");
/* harmony import */ var _helpers_date_format_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../_helpers/date-format.js */ "./src/routes/_helpers/date-format.js");
/* harmony import */ var _helpers_decode_html_js__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../_helpers/decode-html.js */ "./src/routes/_helpers/decode-html.js");
/* harmony import */ var _components_Title_html__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../../../components/Title.html */ "./components/Title.html");
/* src/routes/articles/[slug].html generated by Svelte v2.9.9 */





async function preload({ params, query }) {
  const maskFields = 'title/rendered,content/rendered,' +
    'meta(' +
      'contributors(title/rendered,slug,meta(degree,graduation_year)),' +
      'fold(title/rendered,meta(volume,number,publication_date))'
    ')'
  const res = await this.fetch(`articles/${params.slug}.json?fields=${maskFields}`);
  if (!res.ok) {
    const message = await res.text()
    return this.error(res.status, message);
  }
  const data = await res.json();
  return { article: data };
};

const file = "src/routes/articles/[slug].html";

function add_css() {
	var style = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("style");
	style.id = 'svelte-cnetnj-style';
	style.textContent = ".content img{display:block;margin-bottom:1rem;width:100%;height:auto}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiW3NsdWddLmh0bWwiLCJzb3VyY2VzIjpbIltzbHVnXS5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIjxzdmVsdGU6aGVhZD5cbiAgPHRpdGxlPntkZWNvZGVIVE1MKGFydGljbGUudGl0bGUucmVuZGVyZWQpfTwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuXG48VGl0bGUgdGl0bGU9e2FydGljbGUudGl0bGUucmVuZGVyZWR9Lz5cbjxkaXYgY2xhc3M9XCJ4IHhhZnMgeHdcIj5cbiAgPGRpdiBjbGFzcz1cImMxMiBzbS1jMiBwMVwiPlxuICAgIHsjaWYgYXJ0aWNsZS5tZXRhfVxuICAgICAgeyNpZiBhcnRpY2xlLm1ldGEuY29udHJpYnV0b3JzfVxuICAgICAgICA8dWw+XG4gICAgICAgICAgeyNlYWNoIGFydGljbGUubWV0YS5jb250cmlidXRvcnMgYXMgY29udHJpYnV0b3J9XG4gICAgICAgICAgICA8bGk+XG4gICAgICAgICAgICAgIDxoMj48YSByZWw9XCJwcmVmZXRjaFwiIGhyZWY9XCIvY29udHJpYnV0b3JzL3tjb250cmlidXRvci5zbHVnfVwiPntAaHRtbCBjb250cmlidXRvci50aXRsZS5yZW5kZXJlZH08L2E+PC9oMj5cbiAgICAgICAgICAgICAgeyNpZiBjb250cmlidXRvci5tZXRhLmRlZ3JlZSAmJiBjb250cmlidXRvci5tZXRhLmdyYWR1YXRpb25feWVhcn1cbiAgICAgICAgICAgICAgICA8aDM+e2NvbnRyaWJ1dG9yLm1ldGEuZGVncmVlfSwge2NvbnRyaWJ1dG9yLm1ldGEuZ3JhZHVhdGlvbl95ZWFyfTwvaDM+XG4gICAgICAgICAgICAgIHsvaWZ9XG4gICAgICAgICAgICA8L2xpPlxuICAgICAgICAgIHsvZWFjaH1cbiAgICAgICAgPC91bD5cbiAgICAgIHsvaWZ9XG4gICAgICB7I2lmIGFydGljbGUubWV0YS5mb2xkfVxuICAgICAgICA8cCBjbGFzcz1cIm1iMFwiPnthcnRpY2xlLm1ldGEuZm9sZC5tZXRhLnZvbHVtZX0te2FydGljbGUubWV0YS5mb2xkLm1ldGEubnVtYmVyfTwvcD5cbiAgICAgICAgPHA+e0BodG1sIGFydGljbGUubWV0YS5mb2xkLnRpdGxlLnJlbmRlcmVkfTwvcD5cbiAgICAgICAgPGg1PntkYXRlRm9ybWF0KGFydGljbGUubWV0YS5mb2xkLm1ldGEucHVibGljYXRpb25fZGF0ZSl9PC9oNT5cbiAgICAgIHsvaWZ9XG4gICAgey9pZn1cbiAgPC9kaXY+XG4gIDxkaXYgY2xhc3M9XCJjMTIgc20tYzYgcDEgY29udGVudFwiPlxuICAgIHtAaHRtbCBhcnRpY2xlLmNvbnRlbnQucmVuZGVyZWR9XG4gIDwvZGl2PlxuPC9kaXY+XG5cbjxzdHlsZT5cbiAgOmdsb2JhbCguY29udGVudCBpbWcpIHtcbiAgICBkaXNwbGF5OiBibG9jaztcbiAgICBtYXJnaW4tYm90dG9tOiAxcmVtO1xuICAgIHdpZHRoOiAxMDAlO1xuICAgIGhlaWdodDogYXV0bztcbiAgfVxuPC9zdHlsZT5cblxuPHNjcmlwdD5cbiAgaW1wb3J0IGRhdGVGb3JtYXQgZnJvbSAnLi4vX2hlbHBlcnMvZGF0ZS1mb3JtYXQuanMnXG4gIGltcG9ydCBkZWNvZGVIVE1MIGZyb20gJy4uL19oZWxwZXJzL2RlY29kZS1odG1sLmpzJ1xuXG4gIGV4cG9ydCBkZWZhdWx0IHtcbiAgICBjb21wb25lbnRzOiB7XG4gICAgICBUaXRsZTogJy4uLy4uLy4uL2NvbXBvbmVudHMvVGl0bGUuaHRtbCdcbiAgICB9LFxuICAgIGhlbHBlcnM6IHtcbiAgICAgIGRhdGVGb3JtYXQsXG4gICAgICBkZWNvZGVIVE1MXG4gICAgfSxcbiAgICBhc3luYyBwcmVsb2FkKHsgcGFyYW1zLCBxdWVyeSB9KSB7XG4gICAgICBjb25zdCBtYXNrRmllbGRzID0gJ3RpdGxlL3JlbmRlcmVkLGNvbnRlbnQvcmVuZGVyZWQsJyArXG4gICAgICAgICdtZXRhKCcgK1xuICAgICAgICAgICdjb250cmlidXRvcnModGl0bGUvcmVuZGVyZWQsc2x1ZyxtZXRhKGRlZ3JlZSxncmFkdWF0aW9uX3llYXIpKSwnICtcbiAgICAgICAgICAnZm9sZCh0aXRsZS9yZW5kZXJlZCxtZXRhKHZvbHVtZSxudW1iZXIscHVibGljYXRpb25fZGF0ZSkpJ1xuICAgICAgICAnKSdcbiAgICAgIGNvbnN0IHJlcyA9IGF3YWl0IHRoaXMuZmV0Y2goYGFydGljbGVzLyR7cGFyYW1zLnNsdWd9Lmpzb24/ZmllbGRzPSR7bWFza0ZpZWxkc31gKTtcbiAgICAgIGlmICghcmVzLm9rKSB7XG4gICAgICAgIGNvbnN0IG1lc3NhZ2UgPSBhd2FpdCByZXMudGV4dCgpXG4gICAgICAgIHJldHVybiB0aGlzLmVycm9yKHJlcy5zdGF0dXMsIG1lc3NhZ2UpO1xuICAgICAgfVxuICAgICAgY29uc3QgZGF0YSA9IGF3YWl0IHJlcy5qc29uKCk7XG4gICAgICByZXR1cm4geyBhcnRpY2xlOiBkYXRhIH07XG4gICAgfVxuICB9O1xuPC9zY3JpcHQ+Il0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQWlDVSxZQUFZLEFBQUUsQ0FBQyxBQUNyQixPQUFPLENBQUUsS0FBSyxDQUNkLGFBQWEsQ0FBRSxJQUFJLENBQ25CLEtBQUssQ0FBRSxJQUFJLENBQ1gsTUFBTSxDQUFFLElBQUksQUFDZCxDQUFDIn0= */";
	Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(style, document.head);
}

function create_main_fragment(component, ctx) {
	var title_value, text, text_1, div, div_1, text_3, div_2, raw_value = ctx.article.content.rendered;

	document.title = title_value = Object(_helpers_decode_html_js__WEBPACK_IMPORTED_MODULE_2__["default"])(ctx.article.title.rendered);

	var title_initial_data = { title: ctx.article.title.rendered };
	var title = new _components_Title_html__WEBPACK_IMPORTED_MODULE_3__["default"]({
		root: component.root,
		store: component.store,
		data: title_initial_data
	});

	var if_block = (ctx.article.meta) && create_if_block(component, ctx);

	return {
		c: function create() {
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n\n");
			title._fragment.c();
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n");
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			div_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			if (if_block) if_block.c();
			text_3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n  ");
			div_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			this.h()
		},

		l: function claim(nodes) {
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(nodes, "\n\n");
			title._fragment.l(nodes);
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(nodes, "\n");

			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			div_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "DIV", { class: true }, false);
			var div_1_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div_1);

			if (if_block) if_block.l(div_1_nodes);
			div_1_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_nodes, "\n  ");

			div_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "DIV", { class: true }, false);
			var div_2_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div_2);

			div_2_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			div_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			div_1.className = "c12 sm-c2 p1";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div_1, file, 6, 2, 150);
			div_2.className = "c12 sm-c6 p1 content";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div_2, file, 27, 2, 977);
			div.className = "x xafs xw";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div, file, 5, 0, 124);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(text, target, anchor);
			title._mount(target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(text_1, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(div, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(div_1, div);
			if (if_block) if_block.m(div_1, null);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_3, div);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(div_2, div);
			div_2.innerHTML = raw_value;
		},

		p: function update(changed, ctx) {
			if ((changed.article) && title_value !== (title_value = Object(_helpers_decode_html_js__WEBPACK_IMPORTED_MODULE_2__["default"])(ctx.article.title.rendered))) {
				document.title = title_value;
			}

			var title_changes = {};
			if (changed.article) title_changes.title = ctx.article.title.rendered;
			title._set(title_changes);

			if (ctx.article.meta) {
				if (if_block) {
					if_block.p(changed, ctx);
				} else {
					if_block = create_if_block(component, ctx);
					if_block.c();
					if_block.m(div_1, null);
				}
			} else if (if_block) {
				if_block.d(1);
				if_block = null;
			}

			if ((changed.article) && raw_value !== (raw_value = ctx.article.content.rendered)) {
				div_2.innerHTML = raw_value;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(text);
			}

			title.destroy(detach);
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(text_1);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(div);
			}

			if (if_block) if_block.d();
		}
	};
}

// (11:10) {#each article.meta.contributors as contributor}
function create_each_block(component, ctx) {
	var li, h2, a, raw_value = ctx.contributor.title.rendered, a_href_value, text;

	var if_block = (ctx.contributor.meta.degree && ctx.contributor.meta.graduation_year) && create_if_block_2(component, ctx);

	return {
		c: function create() {
			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("li");
			h2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h2");
			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("a");
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n              ");
			if (if_block) if_block.c();
			this.h()
		},

		l: function claim(nodes) {
			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "LI", {}, false);
			var li_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(li);

			h2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(li_nodes, "H2", {}, false);
			var h2_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(h2);

			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(h2_nodes, "A", { rel: true, href: true }, false);
			var a_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			a_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			h2_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(li_nodes, "\n              ");
			if (if_block) if_block.l(li_nodes);
			li_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			a.rel = "prefetch";
			a.href = a_href_value = "/contributors/" + ctx.contributor.slug;
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(a, file, 12, 18, 345);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(h2, file, 12, 14, 341);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(li, file, 11, 12, 322);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(li, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(h2, li);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(a, h2);
			a.innerHTML = raw_value;
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text, li);
			if (if_block) if_block.m(li, null);
		},

		p: function update(changed, ctx) {
			if ((changed.article) && raw_value !== (raw_value = ctx.contributor.title.rendered)) {
				a.innerHTML = raw_value;
			}

			if ((changed.article) && a_href_value !== (a_href_value = "/contributors/" + ctx.contributor.slug)) {
				a.href = a_href_value;
			}

			if (ctx.contributor.meta.degree && ctx.contributor.meta.graduation_year) {
				if (if_block) {
					if_block.p(changed, ctx);
				} else {
					if_block = create_if_block_2(component, ctx);
					if_block.c();
					if_block.m(li, null);
				}
			} else if (if_block) {
				if_block.d(1);
				if_block = null;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(li);
			}

			if (if_block) if_block.d();
		}
	};
}

// (14:14) {#if contributor.meta.degree && contributor.meta.graduation_year}
function create_if_block_2(component, ctx) {
	var h3, text_value = ctx.contributor.meta.degree, text, text_1, text_2_value = ctx.contributor.meta.graduation_year, text_2;

	return {
		c: function create() {
			h3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h3");
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])(text_value);
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])(", ");
			text_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])(text_2_value);
			this.h()
		},

		l: function claim(nodes) {
			h3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "H3", {}, false);
			var h3_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(h3);

			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(h3_nodes, text_value);
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(h3_nodes, ", ");
			text_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(h3_nodes, text_2_value);
			h3_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(h3, file, 14, 16, 543);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(h3, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text, h3);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_1, h3);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_2, h3);
		},

		p: function update(changed, ctx) {
			if ((changed.article) && text_value !== (text_value = ctx.contributor.meta.degree)) {
				text.data = text_value;
			}

			if ((changed.article) && text_2_value !== (text_2_value = ctx.contributor.meta.graduation_year)) {
				text_2.data = text_2_value;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(h3);
			}
		}
	};
}

// (9:6) {#if article.meta.contributors}
function create_if_block_1(component, ctx) {
	var ul;

	var each_value = ctx.article.meta.contributors;

	var each_blocks = [];

	for (var i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(component, get_each_context(ctx, each_value, i));
	}

	return {
		c: function create() {
			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("ul");

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}
			this.h()
		},

		l: function claim(nodes) {
			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "UL", {}, false);
			var ul_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(ul_nodes);
			}

			ul_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(ul, file, 9, 8, 246);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(ul, target, anchor);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(ul, null);
			}
		},

		p: function update(changed, ctx) {
			if (changed.article) {
				each_value = ctx.article.meta.contributors;

				for (var i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(changed, child_ctx);
					} else {
						each_blocks[i] = create_each_block(component, child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(ul, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}
				each_blocks.length = each_value.length;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(ul);
			}

			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["destroyEach"])(each_blocks, detach);
		}
	};
}

// (21:6) {#if article.meta.fold}
function create_if_block_3(component, ctx) {
	var p, text_value = ctx.article.meta.fold.meta.volume, text, text_1, text_2_value = ctx.article.meta.fold.meta.number, text_2, text_3, p_1, raw_value = ctx.article.meta.fold.title.rendered, text_4, h5, text_5_value = Object(_helpers_date_format_js__WEBPACK_IMPORTED_MODULE_1__["default"])(ctx.article.meta.fold.meta.publication_date), text_5;

	return {
		c: function create() {
			p = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("p");
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])(text_value);
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("-");
			text_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])(text_2_value);
			text_3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n        ");
			p_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("p");
			text_4 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n        ");
			h5 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h5");
			text_5 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])(text_5_value);
			this.h()
		},

		l: function claim(nodes) {
			p = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "P", { class: true }, false);
			var p_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(p);

			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(p_nodes, text_value);
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(p_nodes, "-");
			text_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(p_nodes, text_2_value);
			p_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(nodes, "\n        ");

			p_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "P", {}, false);
			var p_1_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(p_1);

			p_1_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_4 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(nodes, "\n        ");

			h5 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "H5", {}, false);
			var h5_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(h5);

			text_5 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(h5_nodes, text_5_value);
			h5_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			p.className = "mb0";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(p, file, 21, 8, 734);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(p_1, file, 22, 8, 825);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(h5, file, 23, 8, 881);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(p, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text, p);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_1, p);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_2, p);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(text_3, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(p_1, target, anchor);
			p_1.innerHTML = raw_value;
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(text_4, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(h5, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_5, h5);
		},

		p: function update(changed, ctx) {
			if ((changed.article) && text_value !== (text_value = ctx.article.meta.fold.meta.volume)) {
				text.data = text_value;
			}

			if ((changed.article) && text_2_value !== (text_2_value = ctx.article.meta.fold.meta.number)) {
				text_2.data = text_2_value;
			}

			if ((changed.article) && raw_value !== (raw_value = ctx.article.meta.fold.title.rendered)) {
				p_1.innerHTML = raw_value;
			}

			if ((changed.article) && text_5_value !== (text_5_value = Object(_helpers_date_format_js__WEBPACK_IMPORTED_MODULE_1__["default"])(ctx.article.meta.fold.meta.publication_date))) {
				text_5.data = text_5_value;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(p);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(text_3);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(p_1);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(text_4);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(h5);
			}
		}
	};
}

// (8:4) {#if article.meta}
function create_if_block(component, ctx) {
	var text, if_block_1_anchor;

	var if_block = (ctx.article.meta.contributors) && create_if_block_1(component, ctx);

	var if_block_1 = (ctx.article.meta.fold) && create_if_block_3(component, ctx);

	return {
		c: function create() {
			if (if_block) if_block.c();
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n      ");
			if (if_block_1) if_block_1.c();
			if_block_1_anchor = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createComment"])();
		},

		l: function claim(nodes) {
			if (if_block) if_block.l(nodes);
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(nodes, "\n      ");
			if (if_block_1) if_block_1.l(nodes);
			if_block_1_anchor = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createComment"])();
		},

		m: function mount(target, anchor) {
			if (if_block) if_block.m(target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(text, target, anchor);
			if (if_block_1) if_block_1.m(target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(if_block_1_anchor, target, anchor);
		},

		p: function update(changed, ctx) {
			if (ctx.article.meta.contributors) {
				if (if_block) {
					if_block.p(changed, ctx);
				} else {
					if_block = create_if_block_1(component, ctx);
					if_block.c();
					if_block.m(text.parentNode, text);
				}
			} else if (if_block) {
				if_block.d(1);
				if_block = null;
			}

			if (ctx.article.meta.fold) {
				if (if_block_1) {
					if_block_1.p(changed, ctx);
				} else {
					if_block_1 = create_if_block_3(component, ctx);
					if_block_1.c();
					if_block_1.m(if_block_1_anchor.parentNode, if_block_1_anchor);
				}
			} else if (if_block_1) {
				if_block_1.d(1);
				if_block_1 = null;
			}
		},

		d: function destroy(detach) {
			if (if_block) if_block.d(detach);
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(text);
			}

			if (if_block_1) if_block_1.d(detach);
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(if_block_1_anchor);
			}
		}
	};
}

function get_each_context(ctx, list, i) {
	const child_ctx = Object.create(ctx);
	child_ctx.contributor = list[i];
	child_ctx.each_value = list;
	child_ctx.contributor_index = i;
	return child_ctx;
}

function Slug(options) {
	this._debugName = '<Slug>';
	if (!options || (!options.target && !options.root)) throw new Error("'target' is a required option");
	Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options);
	this._state = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])({}, options.data);
	if (!('article' in this._state)) console.warn("<Slug> was created without expected data property 'article'");
	this._intro = true;

	if (!document.getElementById("svelte-cnetnj-style")) add_css();

	if (!options.root) {
		this._oncreate = [];
		this._beforecreate = [];
		this._aftercreate = [];
	}

	this._fragment = create_main_fragment(this, this._state);

	if (options.target) {
		var nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(options.target);
		options.hydrate ? this._fragment.l(nodes) : this._fragment.c();
		nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
		this._mount(options.target, options.anchor);

		this._lock = true;
		Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["callAll"])(this._beforecreate);
		Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["callAll"])(this._oncreate);
		Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["callAll"])(this._aftercreate);
		this._lock = false;
	}
}

Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])(Slug.prototype, svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["protoDev"]);

Slug.prototype._checkReadOnly = function _checkReadOnly(newState) {
};

Slug.preload = preload;

if (true) {
	const { configure, register, reload } = __webpack_require__(/*! ./node_modules/svelte-loader/lib/hot-api.js */ "./node_modules/svelte-loader/lib/hot-api.js");

	module.hot.accept();

	if (!module.hot.data) {
		// initial load
		configure({});
		Slug = register("src/routes/articles/[slug].html", Slug);
	} else {
		// hot update
		Slug = reload("src/routes/articles/[slug].html", Slug);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Slug);


/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9jb21wb25lbnRzL1RpdGxlLmh0bWwiLCJ3ZWJwYWNrOi8vLy4vbm9kZV9tb2R1bGVzL2RheWpzL2RheWpzLm1pbi5qcyIsIndlYnBhY2s6Ly8vLi9ub2RlX21vZHVsZXMvaXMtZXh0ZW5kYWJsZS9pbmRleC5qcyIsIndlYnBhY2s6Ly8vLi9ub2RlX21vZHVsZXMvdW5lc2NhcGUvaW5kZXguanMiLCJ3ZWJwYWNrOi8vLy4vbm9kZV9tb2R1bGVzL3VuZXNjYXBlL25vZGVfbW9kdWxlcy9leHRlbmQtc2hhbGxvdy9pbmRleC5qcyIsIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL19oZWxwZXJzL2RhdGUtZm9ybWF0LmpzIiwid2VicGFjazovLy8uL3NyYy9yb3V0ZXMvX2hlbHBlcnMvZGVjb2RlLWh0bWwuanMiLCJ3ZWJwYWNrOi8vLy4vc3JjL3JvdXRlcy9hcnRpY2xlcy9bc2x1Z10uaHRtbCJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztzQkFDeUMsS0FBSzs7Ozs7dUJBQUwsS0FBSzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQ0Q5QyxlQUFlLG1DQUFvSSxpQkFBaUIsYUFBYSwrRkFBK0YsRUFBRSxPQUFPLElBQUksT0FBTyxJQUFJLFNBQVMsSUFBSSxNQUFNLElBQUksTUFBTSxJQUFJLFNBQVMsSUFBSSxrQkFBa0IsSUFBSSxHQUFHLElBQUksR0FBRyxJQUFJLEdBQUcsSUFBSSxHQUFHLElBQUksR0FBRyxJQUFJLE9BQU8sSUFBSSxHQUFHLElBQUksR0FBRyxJQUFJLFVBQVUsbU1BQW1NLG1CQUFtQixnQkFBZ0IseURBQXlELElBQUksa0NBQWtDLDRDQUE0QywrQ0FBK0MseUJBQXlCLDRIQUE0SCxzQ0FBc0Msc0JBQXNCLHlDQUF5Qyx3QkFBd0IsT0FBTyxpQ0FBaUMsa0RBQWtELHlCQUF5QixtQkFBbUIsYUFBYSxPQUFPLGtCQUFrQixzQkFBc0IsbUJBQW1CLE1BQU0sa0JBQWtCLGtEQUFrRCxLQUFLLGFBQWEsV0FBVyxrQkFBa0IsaUJBQWlCLHlCQUF5QixZQUFZLHlCQUF5QixpQkFBaUIsWUFBWSxZQUFZLEVBQUUsS0FBSyx3Q0FBd0MsaUJBQWlCLGNBQWMsY0FBYyxrQkFBa0IsMkJBQTJCLFFBQVEsb09BQW9PLG9CQUFvQiw0UUFBNFEscUJBQXFCLFNBQVMsc0JBQXNCLDZDQUE2Qyx3QkFBd0IscUNBQXFDLHNCQUFzQiw0QkFBNEIsd0JBQXdCLDBCQUEwQix1QkFBdUIsMEJBQTBCLG1CQUFtQixlQUFlLG9CQUFvQixlQUFlLGtCQUFrQixlQUFlLG1CQUFtQixlQUFlLG1CQUFtQixlQUFlLHFCQUFxQixlQUFlLHFCQUFxQixlQUFlLDBCQUEwQixnQkFBZ0IsbUJBQW1CLHNDQUFzQyxzQkFBc0IseUJBQXlCLHlCQUF5QixtREFBbUQsOEJBQThCLHNCQUFzQixpQkFBaUIsMEZBQTBGLHdCQUF3QixnQ0FBZ0MsNENBQTRDLCtEQUErRCx5Q0FBeUMsZ0NBQWdDLGdDQUFnQyxxQ0FBcUMsNkJBQTZCLHFCQUFxQiwwQkFBMEIsc0JBQXNCLHdCQUF3Qiw0Q0FBNEMsTUFBTSw4QkFBOEIsTUFBTSwyQkFBMkIsTUFBTSw4QkFBOEIsTUFBTSwyQkFBMkIsTUFBTSw2QkFBNkIsTUFBTSw2QkFBNkIsTUFBTSxrQ0FBa0Msd0JBQXdCLHFCQUFxQiw4QkFBOEIscUJBQXFCLFdBQVcsWUFBWSx3Q0FBd0MsaUNBQWlDLHFEQUFxRCw2QkFBNkIsNkJBQTZCLFVBQVUsYUFBYSxNQUFNLGNBQWMsTUFBTSxlQUFlLE1BQU0sZ0JBQWdCLE1BQU0sYUFBYSxNQUFNLFlBQVkseUJBQXlCLGlCQUFpQiwwQkFBMEIsd0JBQXdCLHNCQUFzQixnSkFBZ0osa0NBQWtDLCtCQUErQixtREFBbUQsVUFBVSx1Q0FBdUMsK0JBQStCLDhCQUE4Qix5Q0FBeUMsMkNBQTJDLDBCQUEwQiw0QkFBNEIsdUNBQXVDLDRCQUE0QiwwQ0FBMEMsNkNBQTZDLDBCQUEwQiw0QkFBNEIsdUNBQXVDLHNGQUFzRixpQ0FBaUMsaUNBQWlDLDRCQUE0Qix1Q0FBdUMsNEJBQTRCLHVDQUF1Qyx5Q0FBeUMsaUJBQWlCLGtDQUFrQyxFQUFFLHdCQUF3Qiw0REFBNEQsVUFBVSxhQUFhLE1BQU0sYUFBYSxtQkFBbUIsTUFBTSxrQkFBa0IsTUFBTSxpQkFBaUIsTUFBTSxnQkFBZ0IsTUFBTSxlQUFlLE1BQU0sZUFBZSxNQUFNLFlBQVkseUJBQXlCLDBCQUEwQix3QkFBd0Isc0JBQXNCLGtCQUFrQix3QkFBd0IsbUJBQW1CLHdCQUF3QixvQkFBb0IsNkJBQTZCLHFCQUFxQix5QkFBeUIsc0JBQXNCLGlFQUFpRSxxQkFBcUIsMEJBQTBCLDBCQUEwQixtQ0FBbUMsdUJBQXVCLE9BQU8sK0dBQStHLHVCQUF1Qiw2QkFBNkIsR0FBRyxHQUFHLDhCQUE4QixrQkFBa0Isb0NBQW9DOzs7Ozs7Ozs7Ozs7O0FDQWg4TTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7O0FBRUE7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7Ozs7Ozs7Ozs7Ozs7QUNaQTs7QUFFQTtBQUNBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBLFdBQVc7QUFDWCxVQUFVOztBQUVWLFdBQVc7QUFDWCxVQUFVOztBQUVWLFVBQVU7QUFDVixVQUFVOztBQUVWLFNBQVM7QUFDVCxVQUFVOztBQUVWLFNBQVM7QUFDVCxVQUFVO0FBQ1YsR0FBRztBQUNIO0FBQ0EsV0FBVztBQUNYLFdBQVc7O0FBRVgsV0FBVztBQUNYLFdBQVc7O0FBRVgsV0FBVztBQUNYLFlBQVk7O0FBRVosWUFBWTtBQUNaLFdBQVc7O0FBRVgsVUFBVTtBQUNWLFdBQVc7O0FBRVgsVUFBVTtBQUNWLFdBQVc7QUFDWDtBQUNBOztBQUVBO0FBQ0E7QUFDQTtBQUNBLGtDQUFrQztBQUNsQztBQUNBLENBQUM7O0FBRUQ7QUFDQTtBQUNBO0FBQ0EsWUFBWSxPQUFPO0FBQ25CLFlBQVk7QUFDWjs7QUFFQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxHQUFHO0FBQ0g7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBOztBQUVBO0FBQ0E7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBOztBQUVBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0EsQ0FBQzs7QUFFRDtBQUNBO0FBQ0E7O0FBRUE7Ozs7Ozs7Ozs7Ozs7QUN0R0E7O0FBRUE7O0FBRUE7QUFDQSxxQkFBcUIsUUFBUTs7QUFFN0I7QUFDQSxpQkFBaUIsU0FBUztBQUMxQjs7QUFFQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBOztBQUVBO0FBQ0E7QUFDQTs7Ozs7Ozs7Ozs7Ozs7Ozs7QUNoQ0E7O0FBRUE7QUFDQTtBQUNBOzs7Ozs7Ozs7Ozs7Ozs7OztBQ0pBOztBQUVBO0FBQ0E7QUFDQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3NCQ2lEaUIsQ0FBQyxFQUFFLE1BQU0sRUFBRSxLQUFLLEVBQUUsRUFBRTtBQUNqQyxFQUFFLE1BQU0sVUFBVSxHQUFHLGtDQUFrQztBQUN2RCxJQUFJLE9BQU87QUFDWCxNQUFNLGlFQUFpRTtBQUN2RSxNQUFNLDJEQUEyRDtBQUNqRSxJQUFJLEdBQUc7QUFDUCxFQUFFLE1BQU0sR0FBRyxHQUFHLE1BQU0sSUFBSSxDQUFDLEtBQUssQ0FBQyxDQUFDLFNBQVMsRUFBRSxNQUFNLENBQUMsSUFBSSxDQUFDLGFBQWEsRUFBRSxVQUFVLENBQUMsQ0FBQyxDQUFDLENBQUM7QUFDcEYsRUFBRSxJQUFJLENBQUMsR0FBRyxDQUFDLEVBQUUsRUFBRTtBQUNmLElBQUksTUFBTSxPQUFPLEdBQUcsTUFBTSxHQUFHLENBQUMsSUFBSSxFQUFFO0FBQ3BDLElBQUksT0FBTyxJQUFJLENBQUMsS0FBSyxDQUFDLEdBQUcsQ0FBQyxNQUFNLEVBQUUsT0FBTyxDQUFDLENBQUM7QUFDM0MsR0FBRztBQUNILEVBQUUsTUFBTSxJQUFJLEdBQUcsTUFBTSxHQUFHLENBQUMsSUFBSSxFQUFFLENBQUM7QUFDaEMsRUFBRSxPQUFPLEVBQUUsT0FBTyxFQUFFLElBQUksRUFBRSxDQUFDO0FBQzNCLENBQUM7Ozs7Ozs7Ozs7OzsyRUF0Q00sT0FBTyxDQUFDLE9BQU8sQ0FBQyxRQUFROztnQ0EzQnpCLHVFQUFVLEtBQUMsT0FBTyxDQUFDLEtBQUssQ0FBQyxRQUFRLENBQUM7O3VDQUc5QixPQUFPLENBQUMsS0FBSyxDQUFDLFFBQVE7Ozs7Ozs7cUJBRzNCLE9BQU8sQ0FBQyxJQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7MkRBTlgsdUVBQVUsS0FBQyxPQUFPLENBQUMsS0FBSyxDQUFDLFFBQVEsQ0FBQzs7Ozs7a0RBRzlCLE9BQU8sQ0FBQyxLQUFLLENBQUMsUUFBUTs7O1dBRzNCLE9BQU8sQ0FBQyxJQUFJOzs7Ozs7Ozs7Ozs7OzJEQXFCVixPQUFPLENBQUMsT0FBTyxDQUFDLFFBQVE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2dDQWhCZ0QsV0FBVyxDQUFDLEtBQUssQ0FBQyxRQUFROztxQkFDMUYsV0FBVyxDQUFDLElBQUksQ0FBQyxNQUFNLFFBQUksV0FBVyxDQUFDLElBQUksQ0FBQyxlQUFlOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztrREFEckIsV0FBVyxDQUFDLElBQUk7Ozs7Ozs7Ozs7Ozs7Ozs7MkRBQVUsV0FBVyxDQUFDLEtBQUssQ0FBQyxRQUFROzs7O29GQUFwRCxXQUFXLENBQUMsSUFBSTs7OztXQUN0RCxXQUFXLENBQUMsSUFBSSxDQUFDLE1BQU0sUUFBSSxXQUFXLENBQUMsSUFBSSxDQUFDLGVBQWU7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzBCQUN6RCxXQUFXLENBQUMsSUFBSSxDQUFDLE1BQU0sbUNBQUksV0FBVyxDQUFDLElBQUksQ0FBQyxlQUFlOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzZEQUEzRCxXQUFXLENBQUMsSUFBSSxDQUFDLE1BQU07Ozs7aUVBQUksV0FBVyxDQUFDLElBQUksQ0FBQyxlQUFlOzs7Ozs7Ozs7Ozs7Ozs7OztzQkFKL0QsT0FBTyxDQUFDLElBQUksQ0FBQyxZQUFZOzs7O2dDQUE5Qjs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztxQkFBSyxPQUFPLENBQUMsSUFBSSxDQUFDLFlBQVk7O21DQUE5Qjs7Ozs7Ozs7Ozs7Ozs7O29DQUFBOzs7Ozs7Ozs7Ozs7Ozs7O3lCQVdZLE9BQU8sQ0FBQyxJQUFJLENBQUMsSUFBSSxDQUFDLElBQUksQ0FBQyxNQUFNLG1DQUFHLE9BQU8sQ0FBQyxJQUFJLENBQUMsSUFBSSxDQUFDLElBQUksQ0FBQyxNQUFNLHVDQUNuRSxPQUFPLENBQUMsSUFBSSxDQUFDLElBQUksQ0FBQyxLQUFLLENBQUMsUUFBUSw2QkFDckMsdUVBQVUsS0FBQyxPQUFPLENBQUMsSUFBSSxDQUFDLElBQUksQ0FBQyxJQUFJLENBQUMsZ0JBQWdCLENBQUM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7NkRBRnhDLE9BQU8sQ0FBQyxJQUFJLENBQUMsSUFBSSxDQUFDLElBQUksQ0FBQyxNQUFNOzs7O2lFQUFHLE9BQU8sQ0FBQyxJQUFJLENBQUMsSUFBSSxDQUFDLElBQUksQ0FBQyxNQUFNOzs7OzJEQUNuRSxPQUFPLENBQUMsSUFBSSxDQUFDLElBQUksQ0FBQyxLQUFLLENBQUMsUUFBUTs7Ozs2REFDckMsdUVBQVUsS0FBQyxPQUFPLENBQUMsSUFBSSxDQUFDLElBQUksQ0FBQyxJQUFJLENBQUMsZ0JBQWdCLENBQUM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztxQkFmckQsT0FBTyxDQUFDLElBQUksQ0FBQyxZQUFZOzt1QkFZekIsT0FBTyxDQUFDLElBQUksQ0FBQyxJQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O1dBWmpCLE9BQU8sQ0FBQyxJQUFJLENBQUMsWUFBWTs7Ozs7Ozs7Ozs7OztXQVl6QixPQUFPLENBQUMsSUFBSSxDQUFDLElBQUkiLCJmaWxlIjoiODFiZGMzNTQwNDBmMjQ5NDFiM2QvYXJ0aWNsZXNfJHNsdWcuYXJ0aWNsZXNfJHNsdWcuanMiLCJzb3VyY2VzQ29udGVudCI6WyI8ZGl2IGNsYXNzPVwiYzEyIHoyXCI+XG4gIDxoMSBjbGFzcz1cImNvMiBjOCBzbS1jbzQgc20tYzRcIj57QGh0bWwgdGl0bGV9PC9oMT5cbjwvZGl2PlxuXG48c3R5bGU+XG4gIGgxIHtcbiAgICBmb250LXNpemU6IDNyZW07XG4gICAgbGluZS1oZWlnaHQ6IDAuOTtcbiAgICBmb250LXdlaWdodDogNDAwO1xuICAgIG1hcmdpbi1ib3R0b206IDNyZW07XG4gIH1cbiAgQG1lZGlhIChtaW4td2lkdGg6IDc2OHB4KSB7XG4gICAgaDEge1xuICAgICAgZm9udC1zaXplOiA0cmVtO1xuICAgIH1cbiAgfVxuPC9zdHlsZT4iLCIhZnVuY3Rpb24odCxlKXtcIm9iamVjdFwiPT10eXBlb2YgZXhwb3J0cyYmXCJ1bmRlZmluZWRcIiE9dHlwZW9mIG1vZHVsZT9tb2R1bGUuZXhwb3J0cz1lKCk6XCJmdW5jdGlvblwiPT10eXBlb2YgZGVmaW5lJiZkZWZpbmUuYW1kP2RlZmluZShlKTp0LmRheWpzPWUoKX0odGhpcyxmdW5jdGlvbigpe1widXNlIHN0cmljdFwiO3ZhciB0PVwibWlsbGlzZWNvbmRcIixlPVwic2Vjb25kXCIsbj1cIm1pbnV0ZVwiLHI9XCJob3VyXCIscz1cImRheVwiLGk9XCJ3ZWVrXCIsYT1cIm1vbnRoXCIsdT1cInllYXJcIixjPS9eKFxcZHs0fSktPyhcXGR7MSwyfSktPyhcXGR7MCwyfSkoLio/KFxcZHsxLDJ9KTooXFxkezEsMn0pOihcXGR7MSwyfSkpPy4/KFxcZHsxLDN9KT8kLyxvPS9cXFsuKj9cXF18WXsyLDR9fE17MSw0fXxEezEsMn18ZHsxLDR9fEh7MSwyfXxoezEsMn18YXxBfG17MSwyfXxzezEsMn18WnsxLDJ9fFNTUy9nLGg9e25hbWU6XCJlblwiLHdlZWtkYXlzOlwiU3VuZGF5X01vbmRheV9UdWVzZGF5X1dlZG5lc2RheV9UaHVyc2RheV9GcmlkYXlfU2F0dXJkYXlcIi5zcGxpdChcIl9cIiksbW9udGhzOlwiSmFudWFyeV9GZWJydWFyeV9NYXJjaF9BcHJpbF9NYXlfSnVuZV9KdWx5X0F1Z3VzdF9TZXB0ZW1iZXJfT2N0b2Jlcl9Ob3ZlbWJlcl9EZWNlbWJlclwiLnNwbGl0KFwiX1wiKX0sZD1mdW5jdGlvbih0LGUsbil7dmFyIHI9U3RyaW5nKHQpO3JldHVybiFyfHxyLmxlbmd0aD49ZT90OlwiXCIrQXJyYXkoZSsxLXIubGVuZ3RoKS5qb2luKG4pK3R9LCQ9e3BhZFN0YXJ0OmQscGFkWm9uZVN0cjpmdW5jdGlvbih0KXt2YXIgZT1NYXRoLmFicyh0KSxuPU1hdGguZmxvb3IoZS82MCkscj1lJTYwO3JldHVybih0PD0wP1wiK1wiOlwiLVwiKStkKG4sMixcIjBcIikrXCI6XCIrZChyLDIsXCIwXCIpfSxtb250aERpZmY6ZnVuY3Rpb24odCxlKXt2YXIgbj0xMiooZS55ZWFyKCktdC55ZWFyKCkpKyhlLm1vbnRoKCktdC5tb250aCgpKSxyPXQuY2xvbmUoKS5hZGQobixcIm1vbnRoc1wiKSxzPWUtcjwwLGk9dC5jbG9uZSgpLmFkZChuKyhzPy0xOjEpLFwibW9udGhzXCIpO3JldHVybiBOdW1iZXIoLShuKyhlLXIpLyhzP3ItaTppLXIpKSl9LGFic0Zsb29yOmZ1bmN0aW9uKHQpe3JldHVybiB0PDA/TWF0aC5jZWlsKHQpfHwwOk1hdGguZmxvb3IodCl9LHByZXR0eVVuaXQ6ZnVuY3Rpb24oYyl7cmV0dXJue006YSx5OnUsdzppLGQ6cyxoOnIsbTpuLHM6ZSxtczp0fVtjXXx8U3RyaW5nKGN8fFwiXCIpLnRvTG93ZXJDYXNlKCkucmVwbGFjZSgvcyQvLFwiXCIpfSxpc1VuZGVmaW5lZDpmdW5jdGlvbih0KXtyZXR1cm4gdm9pZCAwPT09dH19LGY9XCJlblwiLGw9e307bFtmXT1oO3ZhciBtPWZ1bmN0aW9uKHQpe3JldHVybiB0IGluc3RhbmNlb2YgRH0seT1mdW5jdGlvbih0LGUsbil7dmFyIHI7aWYoIXQpcmV0dXJuIG51bGw7aWYoXCJzdHJpbmdcIj09dHlwZW9mIHQpbFt0XSYmKHI9dCksZSYmKGxbdF09ZSxyPXQpO2Vsc2V7dmFyIHM9dC5uYW1lO2xbc109dCxyPXN9cmV0dXJuIG58fChmPXIpLHJ9LE09ZnVuY3Rpb24odCxlKXtpZihtKHQpKXJldHVybiB0LmNsb25lKCk7dmFyIG49ZXx8e307cmV0dXJuIG4uZGF0ZT10LG5ldyBEKG4pfSxTPWZ1bmN0aW9uKHQsZSl7cmV0dXJuIE0odCx7bG9jYWxlOmUuJEx9KX0scD0kO3AucGFyc2VMb2NhbGU9eSxwLmlzRGF5anM9bSxwLndyYXBwZXI9Uzt2YXIgRD1mdW5jdGlvbigpe2Z1bmN0aW9uIGgodCl7dGhpcy5wYXJzZSh0KX12YXIgZD1oLnByb3RvdHlwZTtyZXR1cm4gZC5wYXJzZT1mdW5jdGlvbih0KXt2YXIgZSxuO3RoaXMuJGQ9bnVsbD09PShlPXQuZGF0ZSk/bmV3IERhdGUoTmFOKTpwLmlzVW5kZWZpbmVkKGUpP25ldyBEYXRlOmUgaW5zdGFuY2VvZiBEYXRlP2U6XCJzdHJpbmdcIj09dHlwZW9mIGUmJi8uKlteWl0kL2kudGVzdChlKSYmKG49ZS5tYXRjaChjKSk/bmV3IERhdGUoblsxXSxuWzJdLTEsblszXXx8MSxuWzVdfHwwLG5bNl18fDAsbls3XXx8MCxuWzhdfHwwKTpuZXcgRGF0ZShlKSx0aGlzLmluaXQodCl9LGQuaW5pdD1mdW5jdGlvbih0KXt0aGlzLiR5PXRoaXMuJGQuZ2V0RnVsbFllYXIoKSx0aGlzLiRNPXRoaXMuJGQuZ2V0TW9udGgoKSx0aGlzLiREPXRoaXMuJGQuZ2V0RGF0ZSgpLHRoaXMuJFc9dGhpcy4kZC5nZXREYXkoKSx0aGlzLiRIPXRoaXMuJGQuZ2V0SG91cnMoKSx0aGlzLiRtPXRoaXMuJGQuZ2V0TWludXRlcygpLHRoaXMuJHM9dGhpcy4kZC5nZXRTZWNvbmRzKCksdGhpcy4kbXM9dGhpcy4kZC5nZXRNaWxsaXNlY29uZHMoKSx0aGlzLiRMPXRoaXMuJEx8fHkodC5sb2NhbGUsbnVsbCwhMCl8fGZ9LGQuJHV0aWxzPWZ1bmN0aW9uKCl7cmV0dXJuIHB9LGQuaXNWYWxpZD1mdW5jdGlvbigpe3JldHVybiEoXCJJbnZhbGlkIERhdGVcIj09PXRoaXMuJGQudG9TdHJpbmcoKSl9LGQuJGNvbXBhcmU9ZnVuY3Rpb24odCl7cmV0dXJuIHRoaXMudmFsdWVPZigpLU0odCkudmFsdWVPZigpfSxkLmlzU2FtZT1mdW5jdGlvbih0KXtyZXR1cm4gMD09PXRoaXMuJGNvbXBhcmUodCl9LGQuaXNCZWZvcmU9ZnVuY3Rpb24odCl7cmV0dXJuIHRoaXMuJGNvbXBhcmUodCk8MH0sZC5pc0FmdGVyPWZ1bmN0aW9uKHQpe3JldHVybiB0aGlzLiRjb21wYXJlKHQpPjB9LGQueWVhcj1mdW5jdGlvbigpe3JldHVybiB0aGlzLiR5fSxkLm1vbnRoPWZ1bmN0aW9uKCl7cmV0dXJuIHRoaXMuJE19LGQuZGF5PWZ1bmN0aW9uKCl7cmV0dXJuIHRoaXMuJFd9LGQuZGF0ZT1mdW5jdGlvbigpe3JldHVybiB0aGlzLiREfSxkLmhvdXI9ZnVuY3Rpb24oKXtyZXR1cm4gdGhpcy4kSH0sZC5taW51dGU9ZnVuY3Rpb24oKXtyZXR1cm4gdGhpcy4kbX0sZC5zZWNvbmQ9ZnVuY3Rpb24oKXtyZXR1cm4gdGhpcy4kc30sZC5taWxsaXNlY29uZD1mdW5jdGlvbigpe3JldHVybiB0aGlzLiRtc30sZC51bml4PWZ1bmN0aW9uKCl7cmV0dXJuIE1hdGguZmxvb3IodGhpcy52YWx1ZU9mKCkvMWUzKX0sZC52YWx1ZU9mPWZ1bmN0aW9uKCl7cmV0dXJuIHRoaXMuJGQuZ2V0VGltZSgpfSxkLnN0YXJ0T2Y9ZnVuY3Rpb24odCxjKXt2YXIgbz10aGlzLGg9ISFwLmlzVW5kZWZpbmVkKGMpfHxjLGQ9ZnVuY3Rpb24odCxlKXt2YXIgbj1TKG5ldyBEYXRlKG8uJHksZSx0KSxvKTtyZXR1cm4gaD9uOm4uZW5kT2Yocyl9LCQ9ZnVuY3Rpb24odCxlKXtyZXR1cm4gUyhvLnRvRGF0ZSgpW3RdLmFwcGx5KG8udG9EYXRlKCksaD9bMCwwLDAsMF0uc2xpY2UoZSk6WzIzLDU5LDU5LDk5OV0uc2xpY2UoZSkpLG8pfTtzd2l0Y2gocC5wcmV0dHlVbml0KHQpKXtjYXNlIHU6cmV0dXJuIGg/ZCgxLDApOmQoMzEsMTEpO2Nhc2UgYTpyZXR1cm4gaD9kKDEsdGhpcy4kTSk6ZCgwLHRoaXMuJE0rMSk7Y2FzZSBpOnJldHVybiBkKGg/dGhpcy4kRC10aGlzLiRXOnRoaXMuJEQrKDYtdGhpcy4kVyksdGhpcy4kTSk7Y2FzZSBzOmNhc2VcImRhdGVcIjpyZXR1cm4gJChcInNldEhvdXJzXCIsMCk7Y2FzZSByOnJldHVybiAkKFwic2V0TWludXRlc1wiLDEpO2Nhc2UgbjpyZXR1cm4gJChcInNldFNlY29uZHNcIiwyKTtjYXNlIGU6cmV0dXJuICQoXCJzZXRNaWxsaXNlY29uZHNcIiwzKTtkZWZhdWx0OnJldHVybiB0aGlzLmNsb25lKCl9fSxkLmVuZE9mPWZ1bmN0aW9uKHQpe3JldHVybiB0aGlzLnN0YXJ0T2YodCwhMSl9LGQuJHNldD1mdW5jdGlvbihpLGMpe3N3aXRjaChwLnByZXR0eVVuaXQoaSkpe2Nhc2Ugczp0aGlzLiRkLnNldERhdGUodGhpcy4kRCsoYy10aGlzLiRXKSk7YnJlYWs7Y2FzZVwiZGF0ZVwiOnRoaXMuJGQuc2V0RGF0ZShjKTticmVhaztjYXNlIGE6dGhpcy4kZC5zZXRNb250aChjKTticmVhaztjYXNlIHU6dGhpcy4kZC5zZXRGdWxsWWVhcihjKTticmVhaztjYXNlIHI6dGhpcy4kZC5zZXRIb3VycyhjKTticmVhaztjYXNlIG46dGhpcy4kZC5zZXRNaW51dGVzKGMpO2JyZWFrO2Nhc2UgZTp0aGlzLiRkLnNldFNlY29uZHMoYyk7YnJlYWs7Y2FzZSB0OnRoaXMuJGQuc2V0TWlsbGlzZWNvbmRzKGMpfXJldHVybiB0aGlzLmluaXQoKSx0aGlzfSxkLnNldD1mdW5jdGlvbih0LGUpe3JldHVybiB0aGlzLmNsb25lKCkuJHNldCh0LGUpfSxkLmFkZD1mdW5jdGlvbih0LGMpe3ZhciBvPXRoaXM7dD1OdW1iZXIodCk7dmFyIGgsZD1wLnByZXR0eVVuaXQoYyksJD1mdW5jdGlvbihlLG4pe3ZhciByPW8uc2V0KFwiZGF0ZVwiLDEpLnNldChlLG4rdCk7cmV0dXJuIHIuc2V0KFwiZGF0ZVwiLE1hdGgubWluKG8uJEQsci5kYXlzSW5Nb250aCgpKSl9O2lmKGQ9PT1hKXJldHVybiAkKGEsdGhpcy4kTSk7aWYoZD09PXUpcmV0dXJuICQodSx0aGlzLiR5KTtzd2l0Y2goZCl7Y2FzZSBuOmg9NmU0O2JyZWFrO2Nhc2UgcjpoPTM2ZTU7YnJlYWs7Y2FzZSBzOmg9ODY0ZTU7YnJlYWs7Y2FzZSBpOmg9NjA0OGU1O2JyZWFrO2Nhc2UgZTpoPTFlMzticmVhaztkZWZhdWx0Omg9MX12YXIgZj10aGlzLnZhbHVlT2YoKSt0Kmg7cmV0dXJuIFMoZix0aGlzKX0sZC5zdWJ0cmFjdD1mdW5jdGlvbih0LGUpe3JldHVybiB0aGlzLmFkZCgtMSp0LGUpfSxkLmZvcm1hdD1mdW5jdGlvbih0KXt2YXIgZT10aGlzLG49dHx8XCJZWVlZLU1NLUREVEhIOm1tOnNzWlwiLHI9cC5wYWRab25lU3RyKHRoaXMuJGQuZ2V0VGltZXpvbmVPZmZzZXQoKSkscz10aGlzLiRsb2NhbGUoKSxpPXMud2Vla2RheXMsYT1zLm1vbnRocyx1PWZ1bmN0aW9uKHQsZSxuLHIpe3JldHVybiB0JiZ0W2VdfHxuW2VdLnN1YnN0cigwLHIpfTtyZXR1cm4gbi5yZXBsYWNlKG8sZnVuY3Rpb24odCl7aWYodC5pbmRleE9mKFwiW1wiKT4tMSlyZXR1cm4gdC5yZXBsYWNlKC9cXFt8XFxdL2csXCJcIik7c3dpdGNoKHQpe2Nhc2VcIllZXCI6cmV0dXJuIFN0cmluZyhlLiR5KS5zbGljZSgtMik7Y2FzZVwiWVlZWVwiOnJldHVybiBTdHJpbmcoZS4keSk7Y2FzZVwiTVwiOnJldHVybiBTdHJpbmcoZS4kTSsxKTtjYXNlXCJNTVwiOnJldHVybiBwLnBhZFN0YXJ0KGUuJE0rMSwyLFwiMFwiKTtjYXNlXCJNTU1cIjpyZXR1cm4gdShzLm1vbnRoc1Nob3J0LGUuJE0sYSwzKTtjYXNlXCJNTU1NXCI6cmV0dXJuIGFbZS4kTV07Y2FzZVwiRFwiOnJldHVybiBTdHJpbmcoZS4kRCk7Y2FzZVwiRERcIjpyZXR1cm4gcC5wYWRTdGFydChlLiRELDIsXCIwXCIpO2Nhc2VcImRcIjpyZXR1cm4gU3RyaW5nKGUuJFcpO2Nhc2VcImRkXCI6cmV0dXJuIHUocy53ZWVrZGF5c01pbixlLiRXLGksMik7Y2FzZVwiZGRkXCI6cmV0dXJuIHUocy53ZWVrZGF5c1Nob3J0LGUuJFcsaSwzKTtjYXNlXCJkZGRkXCI6cmV0dXJuIGlbZS4kV107Y2FzZVwiSFwiOnJldHVybiBTdHJpbmcoZS4kSCk7Y2FzZVwiSEhcIjpyZXR1cm4gcC5wYWRTdGFydChlLiRILDIsXCIwXCIpO2Nhc2VcImhcIjpjYXNlXCJoaFwiOnJldHVybiAwPT09ZS4kSD8xMjpwLnBhZFN0YXJ0KGUuJEg8MTM/ZS4kSDplLiRILTEyLFwiaGhcIj09PXQ/MjoxLFwiMFwiKTtjYXNlXCJhXCI6cmV0dXJuIGUuJEg8MTI/XCJhbVwiOlwicG1cIjtjYXNlXCJBXCI6cmV0dXJuIGUuJEg8MTI/XCJBTVwiOlwiUE1cIjtjYXNlXCJtXCI6cmV0dXJuIFN0cmluZyhlLiRtKTtjYXNlXCJtbVwiOnJldHVybiBwLnBhZFN0YXJ0KGUuJG0sMixcIjBcIik7Y2FzZVwic1wiOnJldHVybiBTdHJpbmcoZS4kcyk7Y2FzZVwic3NcIjpyZXR1cm4gcC5wYWRTdGFydChlLiRzLDIsXCIwXCIpO2Nhc2VcIlNTU1wiOnJldHVybiBwLnBhZFN0YXJ0KGUuJG1zLDMsXCIwXCIpO2Nhc2VcIlpcIjpyZXR1cm4gcjtkZWZhdWx0OnJldHVybiByLnJlcGxhY2UoXCI6XCIsXCJcIil9fSl9LGQuZGlmZj1mdW5jdGlvbih0LGMsbyl7dmFyIGg9cC5wcmV0dHlVbml0KGMpLGQ9TSh0KSwkPXRoaXMtZCxmPXAubW9udGhEaWZmKHRoaXMsZCk7c3dpdGNoKGgpe2Nhc2UgdTpmLz0xMjticmVhaztjYXNlIGE6YnJlYWs7Y2FzZVwicXVhcnRlclwiOmYvPTM7YnJlYWs7Y2FzZSBpOmY9JC82MDQ4ZTU7YnJlYWs7Y2FzZSBzOmY9JC84NjRlNTticmVhaztjYXNlIHI6Zj0kLzM2ZTU7YnJlYWs7Y2FzZSBuOmY9JC82ZTQ7YnJlYWs7Y2FzZSBlOmY9JC8xZTM7YnJlYWs7ZGVmYXVsdDpmPSR9cmV0dXJuIG8/ZjpwLmFic0Zsb29yKGYpfSxkLmRheXNJbk1vbnRoPWZ1bmN0aW9uKCl7cmV0dXJuIHRoaXMuZW5kT2YoYSkuJER9LGQuJGxvY2FsZT1mdW5jdGlvbigpe3JldHVybiBsW3RoaXMuJExdfSxkLmxvY2FsZT1mdW5jdGlvbih0LGUpe3ZhciBuPXRoaXMuY2xvbmUoKTtyZXR1cm4gbi4kTD15KHQsZSwhMCksbn0sZC5jbG9uZT1mdW5jdGlvbigpe3JldHVybiBTKHRoaXMudG9EYXRlKCksdGhpcyl9LGQudG9EYXRlPWZ1bmN0aW9uKCl7cmV0dXJuIG5ldyBEYXRlKHRoaXMuJGQpfSxkLnRvQXJyYXk9ZnVuY3Rpb24oKXtyZXR1cm5bdGhpcy4keSx0aGlzLiRNLHRoaXMuJEQsdGhpcy4kSCx0aGlzLiRtLHRoaXMuJHMsdGhpcy4kbXNdfSxkLnRvSlNPTj1mdW5jdGlvbigpe3JldHVybiB0aGlzLnRvSVNPU3RyaW5nKCl9LGQudG9JU09TdHJpbmc9ZnVuY3Rpb24oKXtyZXR1cm4gdGhpcy50b0RhdGUoKS50b0lTT1N0cmluZygpfSxkLnRvT2JqZWN0PWZ1bmN0aW9uKCl7cmV0dXJue3llYXJzOnRoaXMuJHksbW9udGhzOnRoaXMuJE0sZGF0ZTp0aGlzLiRELGhvdXJzOnRoaXMuJEgsbWludXRlczp0aGlzLiRtLHNlY29uZHM6dGhpcy4kcyxtaWxsaXNlY29uZHM6dGhpcy4kbXN9fSxkLnRvU3RyaW5nPWZ1bmN0aW9uKCl7cmV0dXJuIHRoaXMuJGQudG9VVENTdHJpbmcoKX0saH0oKTtyZXR1cm4gTS5leHRlbmQ9ZnVuY3Rpb24odCxlKXtyZXR1cm4gdChlLEQsTSksTX0sTS5sb2NhbGU9eSxNLmlzRGF5anM9bSxNLmVuPWxbZl0sTX0pO1xuIiwiLyohXG4gKiBpcy1leHRlbmRhYmxlIDxodHRwczovL2dpdGh1Yi5jb20vam9uc2NobGlua2VydC9pcy1leHRlbmRhYmxlPlxuICpcbiAqIENvcHlyaWdodCAoYykgMjAxNSwgSm9uIFNjaGxpbmtlcnQuXG4gKiBMaWNlbnNlZCB1bmRlciB0aGUgTUlUIExpY2Vuc2UuXG4gKi9cblxuJ3VzZSBzdHJpY3QnO1xuXG5tb2R1bGUuZXhwb3J0cyA9IGZ1bmN0aW9uIGlzRXh0ZW5kYWJsZSh2YWwpIHtcbiAgcmV0dXJuIHR5cGVvZiB2YWwgIT09ICd1bmRlZmluZWQnICYmIHZhbCAhPT0gbnVsbFxuICAgICYmICh0eXBlb2YgdmFsID09PSAnb2JqZWN0JyB8fCB0eXBlb2YgdmFsID09PSAnZnVuY3Rpb24nKTtcbn07XG4iLCIndXNlIHN0cmljdCc7XG5cbnZhciBleHRlbmQgPSByZXF1aXJlKCdleHRlbmQtc2hhbGxvdycpO1xudmFyIHJlZ2V4Q2FjaGUgPSB7fTtcbnZhciBhbGw7XG5cbnZhciBjaGFyU2V0cyA9IHtcbiAgZGVmYXVsdDoge1xuICAgICcmcXVvdDsnOiAnXCInLFxuICAgICcmIzM0Oyc6ICdcIicsXG5cbiAgICAnJmFwb3M7JzogJ1xcJycsXG4gICAgJyYjMzk7JzogJ1xcJycsXG5cbiAgICAnJmFtcDsnOiAnJicsXG4gICAgJyYjMzg7JzogJyYnLFxuXG4gICAgJyZndDsnOiAnPicsXG4gICAgJyYjNjI7JzogJz4nLFxuXG4gICAgJyZsdDsnOiAnPCcsXG4gICAgJyYjNjA7JzogJzwnXG4gIH0sXG4gIGV4dHJhczoge1xuICAgICcmY2VudDsnOiAnwqInLFxuICAgICcmIzE2MjsnOiAnwqInLFxuXG4gICAgJyZjb3B5Oyc6ICfCqScsXG4gICAgJyYjMTY5Oyc6ICfCqScsXG5cbiAgICAnJmV1cm87JzogJ+KCrCcsXG4gICAgJyYjODM2NDsnOiAn4oKsJyxcblxuICAgICcmcG91bmQ7JzogJ8KjJyxcbiAgICAnJiMxNjM7JzogJ8KjJyxcblxuICAgICcmcmVnOyc6ICfCricsXG4gICAgJyYjMTc0Oyc6ICfCricsXG5cbiAgICAnJnllbjsnOiAnwqUnLFxuICAgICcmIzE2NTsnOiAnwqUnXG4gIH1cbn07XG5cbi8vIGRvbid0IG1lcmdlIGNoYXIgc2V0cyB1bmxlc3MgXCJhbGxcIiBpcyBleHBsaWNpdGx5IGNhbGxlZFxuT2JqZWN0LmRlZmluZVByb3BlcnR5KGNoYXJTZXRzLCAnYWxsJywge1xuICBnZXQ6IGZ1bmN0aW9uKCkge1xuICAgIHJldHVybiBhbGwgfHwgKGFsbCA9IGV4dGVuZCh7fSwgY2hhclNldHMuZGVmYXVsdCwgY2hhclNldHMuZXh0cmFzKSk7XG4gIH1cbn0pO1xuXG4vKipcbiAqIENvbnZlcnQgSFRNTCBlbnRpdGllcyB0byBIVE1MIGNoYXJhY3RlcnMuXG4gKlxuICogQHBhcmFtICB7U3RyaW5nfSBgc3RyYCBTdHJpbmcgd2l0aCBIVE1MIGVudGl0aWVzIHRvIHVuLWVzY2FwZS5cbiAqIEByZXR1cm4ge1N0cmluZ31cbiAqL1xuXG5mdW5jdGlvbiB1bmVzY2FwZShzdHIsIHR5cGUpIHtcbiAgaWYgKCFpc1N0cmluZyhzdHIpKSByZXR1cm4gJyc7XG4gIHZhciBjaGFycyA9IGNoYXJTZXRzW3R5cGUgfHwgJ2RlZmF1bHQnXTtcbiAgdmFyIHJlZ2V4ID0gdG9SZWdleCh0eXBlLCBjaGFycyk7XG4gIHJldHVybiBzdHIucmVwbGFjZShyZWdleCwgZnVuY3Rpb24obSkge1xuICAgIHJldHVybiBjaGFyc1ttXTtcbiAgfSk7XG59XG5cbmZ1bmN0aW9uIHRvUmVnZXgodHlwZSwgY2hhcnMpIHtcbiAgaWYgKHJlZ2V4Q2FjaGVbdHlwZV0pIHtcbiAgICByZXR1cm4gcmVnZXhDYWNoZVt0eXBlXTtcbiAgfVxuICB2YXIga2V5cyA9IE9iamVjdC5rZXlzKGNoYXJzKS5qb2luKCd8Jyk7XG4gIHZhciByZWdleCA9IG5ldyBSZWdFeHAoJyg/PSgnICsga2V5cyArICcpKVxcXFwxJywgJ2cnKTtcbiAgcmVnZXhDYWNoZVt0eXBlXSA9IHJlZ2V4O1xuICByZXR1cm4gcmVnZXg7XG59XG5cbi8qKlxuICogUmV0dXJucyB0cnVlIGlmIHN0ciBpcyBhIG5vbi1lbXB0eSBzdHJpbmdcbiAqL1xuXG5mdW5jdGlvbiBpc1N0cmluZyhzdHIpIHtcbiAgcmV0dXJuIHN0ciAmJiB0eXBlb2Ygc3RyID09PSAnc3RyaW5nJztcbn1cblxuLyoqXG4gKiBFeHBvc2UgY2hhclNldHNcbiAqL1xuXG51bmVzY2FwZS5jaGFycyA9IGNoYXJTZXRzLmRlZmF1bHQ7XG51bmVzY2FwZS5leHRyYXMgPSBjaGFyU2V0cy5leHRyYXM7XG4vLyBkb24ndCB0cmlwIHRoZSBcImNoYXJTZXRzXCIgZ2V0dGVyIHVubGVzcyBpdCdzIGV4cGxpY2l0bHkgY2FsbGVkXG5PYmplY3QuZGVmaW5lUHJvcGVydHkodW5lc2NhcGUsICdhbGwnLCB7XG4gIGdldDogZnVuY3Rpb24oKSB7XG4gICAgcmV0dXJuIGNoYXJTZXRzLmFsbDtcbiAgfVxufSk7XG5cbi8qKlxuICogRXhwb3NlIGB1bmVzY2FwZWBcbiAqL1xuXG5tb2R1bGUuZXhwb3J0cyA9IHVuZXNjYXBlO1xuIiwiJ3VzZSBzdHJpY3QnO1xuXG52YXIgaXNPYmplY3QgPSByZXF1aXJlKCdpcy1leHRlbmRhYmxlJyk7XG5cbm1vZHVsZS5leHBvcnRzID0gZnVuY3Rpb24gZXh0ZW5kKG8vKiwgb2JqZWN0cyovKSB7XG4gIGlmICghaXNPYmplY3QobykpIHsgbyA9IHt9OyB9XG5cbiAgdmFyIGxlbiA9IGFyZ3VtZW50cy5sZW5ndGg7XG4gIGZvciAodmFyIGkgPSAxOyBpIDwgbGVuOyBpKyspIHtcbiAgICB2YXIgb2JqID0gYXJndW1lbnRzW2ldO1xuXG4gICAgaWYgKGlzT2JqZWN0KG9iaikpIHtcbiAgICAgIGFzc2lnbihvLCBvYmopO1xuICAgIH1cbiAgfVxuICByZXR1cm4gbztcbn07XG5cbmZ1bmN0aW9uIGFzc2lnbihhLCBiKSB7XG4gIGZvciAodmFyIGtleSBpbiBiKSB7XG4gICAgaWYgKGhhc093bihiLCBrZXkpKSB7XG4gICAgICBhW2tleV0gPSBiW2tleV07XG4gICAgfVxuICB9XG59XG5cbi8qKlxuICogUmV0dXJucyB0cnVlIGlmIHRoZSBnaXZlbiBga2V5YCBpcyBhbiBvd24gcHJvcGVydHkgb2YgYG9iamAuXG4gKi9cblxuZnVuY3Rpb24gaGFzT3duKG9iaiwga2V5KSB7XG4gIHJldHVybiBPYmplY3QucHJvdG90eXBlLmhhc093blByb3BlcnR5LmNhbGwob2JqLCBrZXkpO1xufVxuIiwiaW1wb3J0IGRheWpzIGZyb20gJ2RheWpzJ1xuXG5leHBvcnQgZGVmYXVsdCBmdW5jdGlvbiBmb3JtYXQoZGF0ZSkge1xuICByZXR1cm4gZGF5anMoZGF0ZSkuZm9ybWF0KCdNTU1NIEQsIFlZWVknKVxufVxuIiwiaW1wb3J0IGRlY29kZSBmcm9tICd1bmVzY2FwZSdcblxuZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gZGVjb2RlaHRtbChzdHIpIHtcbiAgcmV0dXJuIGRlY29kZShzdHIsICdhbGwnKVxufVxuIiwiPHN2ZWx0ZTpoZWFkPlxuICA8dGl0bGU+e2RlY29kZUhUTUwoYXJ0aWNsZS50aXRsZS5yZW5kZXJlZCl9PC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG5cbjxUaXRsZSB0aXRsZT17YXJ0aWNsZS50aXRsZS5yZW5kZXJlZH0vPlxuPGRpdiBjbGFzcz1cInggeGFmcyB4d1wiPlxuICA8ZGl2IGNsYXNzPVwiYzEyIHNtLWMyIHAxXCI+XG4gICAgeyNpZiBhcnRpY2xlLm1ldGF9XG4gICAgICB7I2lmIGFydGljbGUubWV0YS5jb250cmlidXRvcnN9XG4gICAgICAgIDx1bD5cbiAgICAgICAgICB7I2VhY2ggYXJ0aWNsZS5tZXRhLmNvbnRyaWJ1dG9ycyBhcyBjb250cmlidXRvcn1cbiAgICAgICAgICAgIDxsaT5cbiAgICAgICAgICAgICAgPGgyPjxhIHJlbD1cInByZWZldGNoXCIgaHJlZj1cIi9jb250cmlidXRvcnMve2NvbnRyaWJ1dG9yLnNsdWd9XCI+e0BodG1sIGNvbnRyaWJ1dG9yLnRpdGxlLnJlbmRlcmVkfTwvYT48L2gyPlxuICAgICAgICAgICAgICB7I2lmIGNvbnRyaWJ1dG9yLm1ldGEuZGVncmVlICYmIGNvbnRyaWJ1dG9yLm1ldGEuZ3JhZHVhdGlvbl95ZWFyfVxuICAgICAgICAgICAgICAgIDxoMz57Y29udHJpYnV0b3IubWV0YS5kZWdyZWV9LCB7Y29udHJpYnV0b3IubWV0YS5ncmFkdWF0aW9uX3llYXJ9PC9oMz5cbiAgICAgICAgICAgICAgey9pZn1cbiAgICAgICAgICAgIDwvbGk+XG4gICAgICAgICAgey9lYWNofVxuICAgICAgICA8L3VsPlxuICAgICAgey9pZn1cbiAgICAgIHsjaWYgYXJ0aWNsZS5tZXRhLmZvbGR9XG4gICAgICAgIDxwIGNsYXNzPVwibWIwXCI+e2FydGljbGUubWV0YS5mb2xkLm1ldGEudm9sdW1lfS17YXJ0aWNsZS5tZXRhLmZvbGQubWV0YS5udW1iZXJ9PC9wPlxuICAgICAgICA8cD57QGh0bWwgYXJ0aWNsZS5tZXRhLmZvbGQudGl0bGUucmVuZGVyZWR9PC9wPlxuICAgICAgICA8aDU+e2RhdGVGb3JtYXQoYXJ0aWNsZS5tZXRhLmZvbGQubWV0YS5wdWJsaWNhdGlvbl9kYXRlKX08L2g1PlxuICAgICAgey9pZn1cbiAgICB7L2lmfVxuICA8L2Rpdj5cbiAgPGRpdiBjbGFzcz1cImMxMiBzbS1jNiBwMSBjb250ZW50XCI+XG4gICAge0BodG1sIGFydGljbGUuY29udGVudC5yZW5kZXJlZH1cbiAgPC9kaXY+XG48L2Rpdj5cblxuPHN0eWxlPlxuICA6Z2xvYmFsKC5jb250ZW50IGltZykge1xuICAgIGRpc3BsYXk6IGJsb2NrO1xuICAgIG1hcmdpbi1ib3R0b206IDFyZW07XG4gICAgd2lkdGg6IDEwMCU7XG4gICAgaGVpZ2h0OiBhdXRvO1xuICB9XG48L3N0eWxlPlxuXG48c2NyaXB0PlxuICBpbXBvcnQgZGF0ZUZvcm1hdCBmcm9tICcuLi9faGVscGVycy9kYXRlLWZvcm1hdC5qcydcbiAgaW1wb3J0IGRlY29kZUhUTUwgZnJvbSAnLi4vX2hlbHBlcnMvZGVjb2RlLWh0bWwuanMnXG5cbiAgZXhwb3J0IGRlZmF1bHQge1xuICAgIGNvbXBvbmVudHM6IHtcbiAgICAgIFRpdGxlOiAnLi4vLi4vLi4vY29tcG9uZW50cy9UaXRsZS5odG1sJ1xuICAgIH0sXG4gICAgaGVscGVyczoge1xuICAgICAgZGF0ZUZvcm1hdCxcbiAgICAgIGRlY29kZUhUTUxcbiAgICB9LFxuICAgIGFzeW5jIHByZWxvYWQoeyBwYXJhbXMsIHF1ZXJ5IH0pIHtcbiAgICAgIGNvbnN0IG1hc2tGaWVsZHMgPSAndGl0bGUvcmVuZGVyZWQsY29udGVudC9yZW5kZXJlZCwnICtcbiAgICAgICAgJ21ldGEoJyArXG4gICAgICAgICAgJ2NvbnRyaWJ1dG9ycyh0aXRsZS9yZW5kZXJlZCxzbHVnLG1ldGEoZGVncmVlLGdyYWR1YXRpb25feWVhcikpLCcgK1xuICAgICAgICAgICdmb2xkKHRpdGxlL3JlbmRlcmVkLG1ldGEodm9sdW1lLG51bWJlcixwdWJsaWNhdGlvbl9kYXRlKSknXG4gICAgICAgICcpJ1xuICAgICAgY29uc3QgcmVzID0gYXdhaXQgdGhpcy5mZXRjaChgYXJ0aWNsZXMvJHtwYXJhbXMuc2x1Z30uanNvbj9maWVsZHM9JHttYXNrRmllbGRzfWApO1xuICAgICAgaWYgKCFyZXMub2spIHtcbiAgICAgICAgY29uc3QgbWVzc2FnZSA9IGF3YWl0IHJlcy50ZXh0KClcbiAgICAgICAgcmV0dXJuIHRoaXMuZXJyb3IocmVzLnN0YXR1cywgbWVzc2FnZSk7XG4gICAgICB9XG4gICAgICBjb25zdCBkYXRhID0gYXdhaXQgcmVzLmpzb24oKTtcbiAgICAgIHJldHVybiB7IGFydGljbGU6IGRhdGEgfTtcbiAgICB9XG4gIH07XG48L3NjcmlwdD4iXSwic291cmNlUm9vdCI6IiJ9