(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["contributors_$slug"],{

/***/ "./components/FullSpread.html":
/*!************************************!*\
  !*** ./components/FullSpread.html ***!
  \************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/shared.js */ "./node_modules/svelte/shared.js");
/* components/FullSpread.html generated by Svelte v2.9.9 */


const file = "components/FullSpread.html";

function add_css() {
	var style = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("style");
	style.id = 'svelte-1cuuebb-style';
	style.textContent = "img.svelte-1cuuebb{width:100%;height:100%}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiRnVsbFNwcmVhZC5odG1sIiwic291cmNlcyI6WyJGdWxsU3ByZWFkLmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiPGRpdiBjbGFzcz1cImgxMDAgdzEwMCBvaCBiZ2Mtd2hpdGVcIj5cbiAgPGltZyBzcmM9XCJ7bWVkaWEubWVkaWFfZGV0YWlscy5zaXplcy5mdWxsLnNvdXJjZV91cmx9XCI+XG48L2Rpdj5cblxuPHN0eWxlPlxuICBpbWcge1xuICAgIHdpZHRoOiAxMDAlO1xuICAgIGhlaWdodDogMTAwJTtcbiAgfVxuPC9zdHlsZT4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBS0UsR0FBRyxlQUFDLENBQUMsQUFDSCxLQUFLLENBQUUsSUFBSSxDQUNYLE1BQU0sQ0FBRSxJQUFJLEFBQ2QsQ0FBQyJ9 */";
	Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(style, document.head);
}

function create_main_fragment(component, ctx) {
	var div, img, img_src_value;

	return {
		c: function create() {
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			img = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("img");
			this.h()
		},

		l: function claim(nodes) {
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			img = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "IMG", { src: true, class: true }, false);
			var img_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(img);

			img_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			div_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			img.src = img_src_value = ctx.media.media_details.sizes.full.source_url;
			img.className = "svelte-1cuuebb";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(img, file, 1, 2, 39);
			div.className = "h100 w100 oh bgc-white";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div, file, 0, 0, 0);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(div, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(img, div);
		},

		p: function update(changed, ctx) {
			if ((changed.media) && img_src_value !== (img_src_value = ctx.media.media_details.sizes.full.source_url)) {
				img.src = img_src_value;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(div);
			}
		}
	};
}

function FullSpread(options) {
	this._debugName = '<FullSpread>';
	if (!options || (!options.target && !options.root)) throw new Error("'target' is a required option");
	Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options);
	this._state = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])({}, options.data);
	if (!('media' in this._state)) console.warn("<FullSpread> was created without expected data property 'media'");
	this._intro = true;

	if (!document.getElementById("svelte-1cuuebb-style")) add_css();

	this._fragment = create_main_fragment(this, this._state);

	if (options.target) {
		var nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(options.target);
		options.hydrate ? this._fragment.l(nodes) : this._fragment.c();
		nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
		this._mount(options.target, options.anchor);
	}
}

Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])(FullSpread.prototype, svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["protoDev"]);

FullSpread.prototype._checkReadOnly = function _checkReadOnly(newState) {
};

if (true) {
	const { configure, register, reload } = __webpack_require__(/*! ./node_modules/svelte-loader/lib/hot-api.js */ "./node_modules/svelte-loader/lib/hot-api.js");

	module.hot.accept();

	if (!module.hot.data) {
		// initial load
		configure({});
		FullSpread = register("components/FullSpread.html", FullSpread);
	} else {
		// hot update
		FullSpread = reload("components/FullSpread.html", FullSpread);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (FullSpread);


/***/ }),

/***/ "./node_modules/is-extendable/index.js":
/*!*********************************************!*\
  !*** ./node_modules/is-extendable/index.js ***!
  \*********************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";
/*!
 * is-extendable <https://github.com/jonschlinkert/is-extendable>
 *
 * Copyright (c) 2015, Jon Schlinkert.
 * Licensed under the MIT License.
 */



module.exports = function isExtendable(val) {
  return typeof val !== 'undefined' && val !== null
    && (typeof val === 'object' || typeof val === 'function');
};


/***/ }),

/***/ "./node_modules/unescape/index.js":
/*!****************************************!*\
  !*** ./node_modules/unescape/index.js ***!
  \****************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";


var extend = __webpack_require__(/*! extend-shallow */ "./node_modules/unescape/node_modules/extend-shallow/index.js");
var regexCache = {};
var all;

var charSets = {
  default: {
    '&quot;': '"',
    '&#34;': '"',

    '&apos;': '\'',
    '&#39;': '\'',

    '&amp;': '&',
    '&#38;': '&',

    '&gt;': '>',
    '&#62;': '>',

    '&lt;': '<',
    '&#60;': '<'
  },
  extras: {
    '&cent;': '¢',
    '&#162;': '¢',

    '&copy;': '©',
    '&#169;': '©',

    '&euro;': '€',
    '&#8364;': '€',

    '&pound;': '£',
    '&#163;': '£',

    '&reg;': '®',
    '&#174;': '®',

    '&yen;': '¥',
    '&#165;': '¥'
  }
};

// don't merge char sets unless "all" is explicitly called
Object.defineProperty(charSets, 'all', {
  get: function() {
    return all || (all = extend({}, charSets.default, charSets.extras));
  }
});

/**
 * Convert HTML entities to HTML characters.
 *
 * @param  {String} `str` String with HTML entities to un-escape.
 * @return {String}
 */

function unescape(str, type) {
  if (!isString(str)) return '';
  var chars = charSets[type || 'default'];
  var regex = toRegex(type, chars);
  return str.replace(regex, function(m) {
    return chars[m];
  });
}

function toRegex(type, chars) {
  if (regexCache[type]) {
    return regexCache[type];
  }
  var keys = Object.keys(chars).join('|');
  var regex = new RegExp('(?=(' + keys + '))\\1', 'g');
  regexCache[type] = regex;
  return regex;
}

/**
 * Returns true if str is a non-empty string
 */

function isString(str) {
  return str && typeof str === 'string';
}

/**
 * Expose charSets
 */

unescape.chars = charSets.default;
unescape.extras = charSets.extras;
// don't trip the "charSets" getter unless it's explicitly called
Object.defineProperty(unescape, 'all', {
  get: function() {
    return charSets.all;
  }
});

/**
 * Expose `unescape`
 */

module.exports = unescape;


/***/ }),

/***/ "./node_modules/unescape/node_modules/extend-shallow/index.js":
/*!********************************************************************!*\
  !*** ./node_modules/unescape/node_modules/extend-shallow/index.js ***!
  \********************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";


var isObject = __webpack_require__(/*! is-extendable */ "./node_modules/is-extendable/index.js");

module.exports = function extend(o/*, objects*/) {
  if (!isObject(o)) { o = {}; }

  var len = arguments.length;
  for (var i = 1; i < len; i++) {
    var obj = arguments[i];

    if (isObject(obj)) {
      assign(o, obj);
    }
  }
  return o;
};

function assign(a, b) {
  for (var key in b) {
    if (hasOwn(b, key)) {
      a[key] = b[key];
    }
  }
}

/**
 * Returns true if the given `key` is an own property of `obj`.
 */

function hasOwn(obj, key) {
  return Object.prototype.hasOwnProperty.call(obj, key);
}


/***/ }),

/***/ "./src/routes/_helpers/decode-html.js":
/*!********************************************!*\
  !*** ./src/routes/_helpers/decode-html.js ***!
  \********************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "default", function() { return decodehtml; });
/* harmony import */ var unescape__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! unescape */ "./node_modules/unescape/index.js");
/* harmony import */ var unescape__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(unescape__WEBPACK_IMPORTED_MODULE_0__);


function decodehtml(str) {
  return unescape__WEBPACK_IMPORTED_MODULE_0___default()(str, 'all')
}


/***/ }),

/***/ "./src/routes/contributors/[slug].html":
/*!*********************************************!*\
  !*** ./src/routes/contributors/[slug].html ***!
  \*********************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/shared.js */ "./node_modules/svelte/shared.js");
/* harmony import */ var _helpers_decode_html_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../_helpers/decode-html.js */ "./src/routes/_helpers/decode-html.js");
/* harmony import */ var _components_FullSpread_html__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../../../components/FullSpread.html */ "./components/FullSpread.html");
/* harmony import */ var _components_ArticleList_html__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../../../components/ArticleList.html */ "./components/ArticleList.html");
/* harmony import */ var _components_Title_html__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ../../../components/Title.html */ "./components/Title.html");
/* src/routes/contributors/[slug].html generated by Svelte v2.9.9 */






function oncreate() {
  console.log('json', this.get());
};

async function preload({ params, query }) {
  const maskFields = 'title/rendered,' +
  'meta(' +
    'degree,graduation_year,' +
    'folds_edited(slug,meta(fold_front(media_details(sizes(full(source_url)))))),' +
    'folds_designed(slug,meta(fold_front(media_details(sizes(full(source_url)))))),' +
    'posts_contributed(title/rendered,slug,meta/contributors(title/rendered))' +
  ')'
  const res = await this.fetch(`contributors/${params.slug}.json?fields=${maskFields}`);
  if (!res.ok) {
    const message = await res.text()
    return this.error(res.status, message);
  }
  const data = await res.json();
  return { contributor: data };
};

const file = "src/routes/contributors/[slug].html";

function create_main_fragment(component, ctx) {
	var title_value, text, text_1, div, div_1, h2, raw_value = ctx.contributor.title.rendered, text_2, text_4, div_2, text_5, text_6;

	document.title = title_value = Object(_helpers_decode_html_js__WEBPACK_IMPORTED_MODULE_1__["default"])(ctx.contributor.title.rendered);

	var title_initial_data = { title: ctx.contributor.title.rendered };
	var title = new _components_Title_html__WEBPACK_IMPORTED_MODULE_4__["default"]({
		root: component.root,
		store: component.store,
		data: title_initial_data
	});

	var if_block = (ctx.contributor.meta.degree && ctx.contributor.meta.graduation_year) && create_if_block(component, ctx);

	var if_block_1 = (ctx.contributor.meta.folds_edited && ctx.contributor.meta.folds_edited.length) && create_if_block_1(component, ctx);

	var if_block_2 = (ctx.contributor.meta.folds_designed && ctx.contributor.meta.folds_designed.length) && create_if_block_2(component, ctx);

	var if_block_3 = (ctx.contributor.meta.posts_contributed && ctx.contributor.meta.posts_contributed.length) && create_if_block_3(component, ctx);

	return {
		c: function create() {
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n\n");
			title._fragment.c();
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n");
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			div_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			h2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h2");
			text_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n    ");
			if (if_block) if_block.c();
			text_4 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n  ");
			div_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			if (if_block_1) if_block_1.c();
			text_5 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n    ");
			if (if_block_2) if_block_2.c();
			text_6 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n    ");
			if (if_block_3) if_block_3.c();
			this.h()
		},

		l: function claim(nodes) {
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(nodes, "\n\n");
			title._fragment.l(nodes);
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(nodes, "\n");

			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			div_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "DIV", { class: true }, false);
			var div_1_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div_1);

			h2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_1_nodes, "H2", {}, false);
			var h2_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(h2);

			h2_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_1_nodes, "\n    ");
			if (if_block) if_block.l(div_1_nodes);
			div_1_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_4 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_nodes, "\n  ");

			div_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "DIV", { class: true }, false);
			var div_2_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div_2);

			if (if_block_1) if_block_1.l(div_2_nodes);
			text_5 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_2_nodes, "\n    ");
			if (if_block_2) if_block_2.l(div_2_nodes);
			text_6 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_2_nodes, "\n    ");
			if (if_block_3) if_block_3.l(div_2_nodes);
			div_2_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			div_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(h2, file, 7, 4, 184);
			div_1.className = "c12 sm-c2 p1";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div_1, file, 6, 2, 153);
			div_2.className = "c12 sm-c8 p1";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div_2, file, 12, 2, 396);
			div.className = "x xw";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div, file, 5, 0, 132);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(text, target, anchor);
			title._mount(target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(text_1, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(div, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(div_1, div);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(h2, div_1);
			h2.innerHTML = raw_value;
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_2, div_1);
			if (if_block) if_block.m(div_1, null);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_4, div);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(div_2, div);
			if (if_block_1) if_block_1.m(div_2, null);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_5, div_2);
			if (if_block_2) if_block_2.m(div_2, null);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_6, div_2);
			if (if_block_3) if_block_3.m(div_2, null);
		},

		p: function update(changed, ctx) {
			if ((changed.contributor) && title_value !== (title_value = Object(_helpers_decode_html_js__WEBPACK_IMPORTED_MODULE_1__["default"])(ctx.contributor.title.rendered))) {
				document.title = title_value;
			}

			var title_changes = {};
			if (changed.contributor) title_changes.title = ctx.contributor.title.rendered;
			title._set(title_changes);

			if ((changed.contributor) && raw_value !== (raw_value = ctx.contributor.title.rendered)) {
				h2.innerHTML = raw_value;
			}

			if (ctx.contributor.meta.degree && ctx.contributor.meta.graduation_year) {
				if (if_block) {
					if_block.p(changed, ctx);
				} else {
					if_block = create_if_block(component, ctx);
					if_block.c();
					if_block.m(div_1, null);
				}
			} else if (if_block) {
				if_block.d(1);
				if_block = null;
			}

			if (ctx.contributor.meta.folds_edited && ctx.contributor.meta.folds_edited.length) {
				if (if_block_1) {
					if_block_1.p(changed, ctx);
				} else {
					if_block_1 = create_if_block_1(component, ctx);
					if_block_1.c();
					if_block_1.m(div_2, text_5);
				}
			} else if (if_block_1) {
				if_block_1.d(1);
				if_block_1 = null;
			}

			if (ctx.contributor.meta.folds_designed && ctx.contributor.meta.folds_designed.length) {
				if (if_block_2) {
					if_block_2.p(changed, ctx);
				} else {
					if_block_2 = create_if_block_2(component, ctx);
					if_block_2.c();
					if_block_2.m(div_2, text_6);
				}
			} else if (if_block_2) {
				if_block_2.d(1);
				if_block_2 = null;
			}

			if (ctx.contributor.meta.posts_contributed && ctx.contributor.meta.posts_contributed.length) {
				if (if_block_3) {
					if_block_3.p(changed, ctx);
				} else {
					if_block_3 = create_if_block_3(component, ctx);
					if_block_3.c();
					if_block_3.m(div_2, null);
				}
			} else if (if_block_3) {
				if_block_3.d(1);
				if_block_3 = null;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(text);
			}

			title.destroy(detach);
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(text_1);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(div);
			}

			if (if_block) if_block.d();
			if (if_block_1) if_block_1.d();
			if (if_block_2) if_block_2.d();
			if (if_block_3) if_block_3.d();
		}
	};
}

// (9:4) {#if contributor.meta.degree && contributor.meta.graduation_year}
function create_if_block(component, ctx) {
	var h3, text_value = ctx.contributor.meta.degree, text, text_1, text_2_value = ctx.contributor.meta.graduation_year, text_2;

	return {
		c: function create() {
			h3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h3");
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])(text_value);
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])(", ");
			text_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])(text_2_value);
			this.h()
		},

		l: function claim(nodes) {
			h3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "H3", {}, false);
			var h3_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(h3);

			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(h3_nodes, text_value);
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(h3_nodes, ", ");
			text_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(h3_nodes, text_2_value);
			h3_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(h3, file, 9, 6, 304);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(h3, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text, h3);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_1, h3);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_2, h3);
		},

		p: function update(changed, ctx) {
			if ((changed.contributor) && text_value !== (text_value = ctx.contributor.meta.degree)) {
				text.data = text_value;
			}

			if ((changed.contributor) && text_2_value !== (text_2_value = ctx.contributor.meta.graduation_year)) {
				text_2.data = text_2_value;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(h3);
			}
		}
	};
}

// (17:8) {#each contributor.meta.folds_edited as fold}
function create_each_block(component, ctx) {
	var div, a, a_href_value;

	var fullspread_initial_data = { media: ctx.fold.meta.fold_front };
	var fullspread = new _components_FullSpread_html__WEBPACK_IMPORTED_MODULE_2__["default"]({
		root: component.root,
		store: component.store,
		data: fullspread_initial_data
	});

	return {
		c: function create() {
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("a");
			fullspread._fragment.c();
			this.h()
		},

		l: function claim(nodes) {
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "A", { rel: true, href: true }, false);
			var a_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			fullspread._fragment.l(a_nodes);
			a_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			div_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			a.rel = "prefetch";
			a.href = a_href_value = "/folds/" + ctx.fold.slug;
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(a, file, 18, 12, 678);
			div.className = "c4 pr1 pb1";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div, file, 17, 10, 641);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(div, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(a, div);
			fullspread._mount(a, null);
		},

		p: function update(changed, ctx) {
			var fullspread_changes = {};
			if (changed.contributor) fullspread_changes.media = ctx.fold.meta.fold_front;
			fullspread._set(fullspread_changes);

			if ((changed.contributor) && a_href_value !== (a_href_value = "/folds/" + ctx.fold.slug)) {
				a.href = a_href_value;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(div);
			}

			fullspread.destroy();
		}
	};
}

// (14:4) {#if contributor.meta.folds_edited && contributor.meta.folds_edited.length}
function create_if_block_1(component, ctx) {
	var h3, text, text_1, div;

	var each_value = ctx.contributor.meta.folds_edited;

	var each_blocks = [];

	for (var i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(component, get_each_context(ctx, each_value, i));
	}

	return {
		c: function create() {
			h3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h3");
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("Folds (Issue Editor)");
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n      ");
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}
			this.h()
		},

		l: function claim(nodes) {
			h3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "H3", { class: true }, false);
			var h3_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(h3);

			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(h3_nodes, "Folds (Issue Editor)");
			h3_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(nodes, "\n      ");

			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(div_nodes);
			}

			div_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			h3.className = "mb1";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(h3, file, 14, 6, 509);
			div.className = "x c12";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div, file, 15, 6, 557);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(h3, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text, h3);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(text_1, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(div, target, anchor);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(div, null);
			}
		},

		p: function update(changed, ctx) {
			if (changed.contributor) {
				each_value = ctx.contributor.meta.folds_edited;

				for (var i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(changed, child_ctx);
					} else {
						each_blocks[i] = create_each_block(component, child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(div, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}
				each_blocks.length = each_value.length;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(h3);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(text_1);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(div);
			}

			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["destroyEach"])(each_blocks, detach);
		}
	};
}

// (27:8) {#each contributor.meta.folds_designed as fold}
function create_each_block_1(component, ctx) {
	var div, a, a_href_value;

	var fullspread_initial_data = { media: ctx.fold.meta.fold_front };
	var fullspread = new _components_FullSpread_html__WEBPACK_IMPORTED_MODULE_2__["default"]({
		root: component.root,
		store: component.store,
		data: fullspread_initial_data
	});

	return {
		c: function create() {
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("a");
			fullspread._fragment.c();
			this.h()
		},

		l: function claim(nodes) {
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "A", { rel: true, href: true }, false);
			var a_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			fullspread._fragment.l(a_nodes);
			a_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			div_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			a.rel = "prefetch";
			a.href = a_href_value = "/folds/" + ctx.fold.slug;
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(a, file, 28, 12, 1090);
			div.className = "c4 pr1 pb1";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div, file, 27, 10, 1053);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(div, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(a, div);
			fullspread._mount(a, null);
		},

		p: function update(changed, ctx) {
			var fullspread_changes = {};
			if (changed.contributor) fullspread_changes.media = ctx.fold.meta.fold_front;
			fullspread._set(fullspread_changes);

			if ((changed.contributor) && a_href_value !== (a_href_value = "/folds/" + ctx.fold.slug)) {
				a.href = a_href_value;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(div);
			}

			fullspread.destroy();
		}
	};
}

// (24:4) {#if contributor.meta.folds_designed && contributor.meta.folds_designed.length}
function create_if_block_2(component, ctx) {
	var h3, text, text_1, div;

	var each_value_1 = ctx.contributor.meta.folds_designed;

	var each_blocks = [];

	for (var i = 0; i < each_value_1.length; i += 1) {
		each_blocks[i] = create_each_block_1(component, get_each_context_1(ctx, each_value_1, i));
	}

	return {
		c: function create() {
			h3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h3");
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("Folds (Graphic Designer)");
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n      ");
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}
			this.h()
		},

		l: function claim(nodes) {
			h3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "H3", { class: true }, false);
			var h3_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(h3);

			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(h3_nodes, "Folds (Graphic Designer)");
			h3_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(nodes, "\n      ");

			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(div_nodes);
			}

			div_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			h3.className = "mb1";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(h3, file, 24, 6, 915);
			div.className = "x c12";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div, file, 25, 6, 967);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(h3, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text, h3);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(text_1, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(div, target, anchor);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(div, null);
			}
		},

		p: function update(changed, ctx) {
			if (changed.contributor) {
				each_value_1 = ctx.contributor.meta.folds_designed;

				for (var i = 0; i < each_value_1.length; i += 1) {
					const child_ctx = get_each_context_1(ctx, each_value_1, i);

					if (each_blocks[i]) {
						each_blocks[i].p(changed, child_ctx);
					} else {
						each_blocks[i] = create_each_block_1(component, child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(div, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}
				each_blocks.length = each_value_1.length;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(h3);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(text_1);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(div);
			}

			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["destroyEach"])(each_blocks, detach);
		}
	};
}

// (34:4) {#if contributor.meta.posts_contributed && contributor.meta.posts_contributed.length}
function create_if_block_3(component, ctx) {
	var h3, text, text_1;

	var articlelist_initial_data = { articles: ctx.contributor.meta.posts_contributed };
	var articlelist = new _components_ArticleList_html__WEBPACK_IMPORTED_MODULE_3__["default"]({
		root: component.root,
		store: component.store,
		data: articlelist_initial_data
	});

	return {
		c: function create() {
			h3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h3");
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("Articles");
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n      ");
			articlelist._fragment.c();
			this.h()
		},

		l: function claim(nodes) {
			h3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "H3", {}, false);
			var h3_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(h3);

			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(h3_nodes, "Articles");
			h3_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(nodes, "\n      ");
			articlelist._fragment.l(nodes);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(h3, file, 34, 6, 1333);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(h3, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text, h3);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(text_1, target, anchor);
			articlelist._mount(target, anchor);
		},

		p: function update(changed, ctx) {
			var articlelist_changes = {};
			if (changed.contributor) articlelist_changes.articles = ctx.contributor.meta.posts_contributed;
			articlelist._set(articlelist_changes);
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(h3);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(text_1);
			}

			articlelist.destroy(detach);
		}
	};
}

function get_each_context(ctx, list, i) {
	const child_ctx = Object.create(ctx);
	child_ctx.fold = list[i];
	child_ctx.each_value = list;
	child_ctx.fold_index = i;
	return child_ctx;
}

function get_each_context_1(ctx, list, i) {
	const child_ctx = Object.create(ctx);
	child_ctx.fold = list[i];
	child_ctx.each_value_1 = list;
	child_ctx.fold_index_1 = i;
	return child_ctx;
}

function Slug(options) {
	this._debugName = '<Slug>';
	if (!options || (!options.target && !options.root)) throw new Error("'target' is a required option");
	Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options);
	this._state = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])({}, options.data);
	if (!('contributor' in this._state)) console.warn("<Slug> was created without expected data property 'contributor'");
	this._intro = true;

	if (!options.root) {
		this._oncreate = [];
		this._beforecreate = [];
		this._aftercreate = [];
	}

	this._fragment = create_main_fragment(this, this._state);

	this.root._oncreate.push(() => {
		oncreate.call(this);
		this.fire("update", { changed: Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assignTrue"])({}, this._state), current: this._state });
	});

	if (options.target) {
		var nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(options.target);
		options.hydrate ? this._fragment.l(nodes) : this._fragment.c();
		nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
		this._mount(options.target, options.anchor);

		this._lock = true;
		Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["callAll"])(this._beforecreate);
		Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["callAll"])(this._oncreate);
		Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["callAll"])(this._aftercreate);
		this._lock = false;
	}
}

Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])(Slug.prototype, svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["protoDev"]);

Slug.prototype._checkReadOnly = function _checkReadOnly(newState) {
};

Slug.preload = preload;

if (true) {
	const { configure, register, reload } = __webpack_require__(/*! ./node_modules/svelte-loader/lib/hot-api.js */ "./node_modules/svelte-loader/lib/hot-api.js");

	module.hot.accept();

	if (!module.hot.data) {
		// initial load
		configure({});
		Slug = register("src/routes/contributors/[slug].html", Slug);
	} else {
		// hot update
		Slug = reload("src/routes/contributors/[slug].html", Slug);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Slug);


/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9jb21wb25lbnRzL0Z1bGxTcHJlYWQuaHRtbCIsIndlYnBhY2s6Ly8vLi9ub2RlX21vZHVsZXMvaXMtZXh0ZW5kYWJsZS9pbmRleC5qcyIsIndlYnBhY2s6Ly8vLi9ub2RlX21vZHVsZXMvdW5lc2NhcGUvaW5kZXguanMiLCJ3ZWJwYWNrOi8vLy4vbm9kZV9tb2R1bGVzL3VuZXNjYXBlL25vZGVfbW9kdWxlcy9leHRlbmQtc2hhbGxvdy9pbmRleC5qcyIsIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL19oZWxwZXJzL2RlY29kZS1odG1sLmpzIiwid2VicGFjazovLy8uL3NyYy9yb3V0ZXMvY29udHJpYnV0b3JzL1tzbHVnXS5odG1sIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2lDQUNhLEtBQUssQ0FBQyxhQUFhLENBQUMsS0FBSyxDQUFDLElBQUksQ0FBQyxVQUFVOzs7Ozs7Ozs7Ozs7O2lFQUF6QyxLQUFLLENBQUMsYUFBYSxDQUFDLEtBQUssQ0FBQyxJQUFJLENBQUMsVUFBVTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0FDRHREO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTs7QUFFQTs7QUFFQTtBQUNBO0FBQ0E7QUFDQTs7Ozs7Ozs7Ozs7OztBQ1pBOztBQUVBO0FBQ0E7QUFDQTs7QUFFQTtBQUNBO0FBQ0EsV0FBVztBQUNYLFVBQVU7O0FBRVYsV0FBVztBQUNYLFVBQVU7O0FBRVYsVUFBVTtBQUNWLFVBQVU7O0FBRVYsU0FBUztBQUNULFVBQVU7O0FBRVYsU0FBUztBQUNULFVBQVU7QUFDVixHQUFHO0FBQ0g7QUFDQSxXQUFXO0FBQ1gsV0FBVzs7QUFFWCxXQUFXO0FBQ1gsV0FBVzs7QUFFWCxXQUFXO0FBQ1gsWUFBWTs7QUFFWixZQUFZO0FBQ1osV0FBVzs7QUFFWCxVQUFVO0FBQ1YsV0FBVzs7QUFFWCxVQUFVO0FBQ1YsV0FBVztBQUNYO0FBQ0E7O0FBRUE7QUFDQTtBQUNBO0FBQ0Esa0NBQWtDO0FBQ2xDO0FBQ0EsQ0FBQzs7QUFFRDtBQUNBO0FBQ0E7QUFDQSxZQUFZLE9BQU87QUFDbkIsWUFBWTtBQUNaOztBQUVBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBLEdBQUc7QUFDSDs7QUFFQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBOztBQUVBO0FBQ0E7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxDQUFDOztBQUVEO0FBQ0E7QUFDQTs7QUFFQTs7Ozs7Ozs7Ozs7OztBQ3RHQTs7QUFFQTs7QUFFQTtBQUNBLHFCQUFxQixRQUFROztBQUU3QjtBQUNBLGlCQUFpQixTQUFTO0FBQzFCOztBQUVBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBOzs7Ozs7Ozs7Ozs7Ozs7OztBQ2hDQTs7QUFFQTtBQUNBO0FBQ0E7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2lCQ21FWSxHQUFHO0FBQ1gsRUFBRSxPQUFPLENBQUMsR0FBRyxDQUFDLE1BQU0sRUFBRSxJQUFJLENBQUMsR0FBRyxFQUFFLENBQUMsQ0FBQztBQUNsQyxDQUFDOztzQkFsQlksQ0FBQyxFQUFFLE1BQU0sRUFBRSxLQUFLLEVBQUUsRUFBRTtBQUNqQyxFQUFFLE1BQU0sVUFBVSxHQUFHLGlCQUFpQjtBQUN0QyxFQUFFLE9BQU87QUFDVCxJQUFJLHlCQUF5QjtBQUM3QixJQUFJLDhFQUE4RTtBQUNsRixJQUFJLGdGQUFnRjtBQUNwRixJQUFJLDBFQUEwRTtBQUM5RSxFQUFFLEdBQUc7QUFDTCxFQUFFLE1BQU0sR0FBRyxHQUFHLE1BQU0sSUFBSSxDQUFDLEtBQUssQ0FBQyxDQUFDLGFBQWEsRUFBRSxNQUFNLENBQUMsSUFBSSxDQUFDLGFBQWEsRUFBRSxVQUFVLENBQUMsQ0FBQyxDQUFDLENBQUM7QUFDeEYsRUFBRSxJQUFJLENBQUMsR0FBRyxDQUFDLEVBQUUsRUFBRTtBQUNmLElBQUksTUFBTSxPQUFPLEdBQUcsTUFBTSxHQUFHLENBQUMsSUFBSSxFQUFFO0FBQ3BDLElBQUksT0FBTyxJQUFJLENBQUMsS0FBSyxDQUFDLEdBQUcsQ0FBQyxNQUFNLEVBQUUsT0FBTyxDQUFDLENBQUM7QUFDM0MsR0FBRztBQUNILEVBQUUsTUFBTSxJQUFJLEdBQUcsTUFBTSxHQUFHLENBQUMsSUFBSSxFQUFFLENBQUM7QUFDaEMsRUFBRSxPQUFPLEVBQUUsV0FBVyxFQUFFLElBQUksRUFBRSxDQUFDO0FBQy9CLENBQUM7Ozs7O2dFQS9EVSxXQUFXLENBQUMsS0FBSyxDQUFDLFFBQVE7O2dDQU4vQix1RUFBVSxLQUFDLFdBQVcsQ0FBQyxLQUFLLENBQUMsUUFBUSxDQUFDOzt1Q0FHbEMsV0FBVyxDQUFDLEtBQUssQ0FBQyxRQUFROzs7Ozs7O3FCQUkvQixXQUFXLENBQUMsSUFBSSxDQUFDLE1BQU0sUUFBSSxXQUFXLENBQUMsSUFBSSxDQUFDLGVBQWU7O3VCQUszRCxXQUFXLENBQUMsSUFBSSxDQUFDLFlBQVksUUFBSSxXQUFXLENBQUMsSUFBSSxDQUFDLFlBQVksQ0FBQyxNQUFNOzt1QkFVckUsV0FBVyxDQUFDLElBQUksQ0FBQyxjQUFjLFFBQUksV0FBVyxDQUFDLElBQUksQ0FBQyxjQUFjLENBQUMsTUFBTTs7dUJBVXpFLFdBQVcsQ0FBQyxJQUFJLENBQUMsaUJBQWlCLFFBQUksV0FBVyxDQUFDLElBQUksQ0FBQyxpQkFBaUIsQ0FBQyxNQUFNOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OytEQWhDOUUsdUVBQVUsS0FBQyxXQUFXLENBQUMsS0FBSyxDQUFDLFFBQVEsQ0FBQzs7Ozs7c0RBR2xDLFdBQVcsQ0FBQyxLQUFLLENBQUMsUUFBUTs7OytEQUd6QixXQUFXLENBQUMsS0FBSyxDQUFDLFFBQVE7Ozs7V0FDaEMsV0FBVyxDQUFDLElBQUksQ0FBQyxNQUFNLFFBQUksV0FBVyxDQUFDLElBQUksQ0FBQyxlQUFlOzs7Ozs7Ozs7Ozs7O1dBSzNELFdBQVcsQ0FBQyxJQUFJLENBQUMsWUFBWSxRQUFJLFdBQVcsQ0FBQyxJQUFJLENBQUMsWUFBWSxDQUFDLE1BQU07Ozs7Ozs7Ozs7Ozs7V0FVckUsV0FBVyxDQUFDLElBQUksQ0FBQyxjQUFjLFFBQUksV0FBVyxDQUFDLElBQUksQ0FBQyxjQUFjLENBQUMsTUFBTTs7Ozs7Ozs7Ozs7OztXQVV6RSxXQUFXLENBQUMsSUFBSSxDQUFDLGlCQUFpQixRQUFJLFdBQVcsQ0FBQyxJQUFJLENBQUMsaUJBQWlCLENBQUMsTUFBTTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7MEJBeEI3RSxXQUFXLENBQUMsSUFBSSxDQUFDLE1BQU0sbUNBQUksV0FBVyxDQUFDLElBQUksQ0FBQyxlQUFlOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2lFQUEzRCxXQUFXLENBQUMsSUFBSSxDQUFDLE1BQU07Ozs7cUVBQUksV0FBVyxDQUFDLElBQUksQ0FBQyxlQUFlOzs7Ozs7Ozs7Ozs7Ozs7Ozs0Q0FTSyxJQUFJLENBQUMsSUFBSSxDQUFDLFVBQVU7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsyQ0FBbkQsSUFBSSxDQUFDLElBQUk7Ozs7Ozs7Ozs7Ozs7OzJEQUFzQixJQUFJLENBQUMsSUFBSSxDQUFDLFVBQVU7OztpRkFBbkQsSUFBSSxDQUFDLElBQUk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7c0JBRnRDLFdBQVcsQ0FBQyxJQUFJLENBQUMsWUFBWTs7OztnQ0FBbEM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3FCQUFLLFdBQVcsQ0FBQyxJQUFJLENBQUMsWUFBWTs7bUNBQWxDOzs7Ozs7Ozs7Ozs7Ozs7b0NBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzRDQVlpRSxJQUFJLENBQUMsSUFBSSxDQUFDLFVBQVU7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsyQ0FBbkQsSUFBSSxDQUFDLElBQUk7Ozs7Ozs7Ozs7Ozs7OzJEQUFzQixJQUFJLENBQUMsSUFBSSxDQUFDLFVBQVU7OztpRkFBbkQsSUFBSSxDQUFDLElBQUk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7d0JBRnRDLFdBQVcsQ0FBQyxJQUFJLENBQUMsY0FBYzs7OztrQ0FBcEM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3VCQUFLLFdBQVcsQ0FBQyxJQUFJLENBQUMsY0FBYzs7cUNBQXBDOzs7Ozs7Ozs7Ozs7Ozs7c0NBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2dEQVNtQixXQUFXLENBQUMsSUFBSSxDQUFDLGlCQUFpQjs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsrREFBbEMsV0FBVyxDQUFDLElBQUksQ0FBQyxpQkFBaUIiLCJmaWxlIjoiODFiZGMzNTQwNDBmMjQ5NDFiM2QvY29udHJpYnV0b3JzXyRzbHVnLmNvbnRyaWJ1dG9yc18kc2x1Zy5qcyIsInNvdXJjZXNDb250ZW50IjpbIjxkaXYgY2xhc3M9XCJoMTAwIHcxMDAgb2ggYmdjLXdoaXRlXCI+XG4gIDxpbWcgc3JjPVwie21lZGlhLm1lZGlhX2RldGFpbHMuc2l6ZXMuZnVsbC5zb3VyY2VfdXJsfVwiPlxuPC9kaXY+XG5cbjxzdHlsZT5cbiAgaW1nIHtcbiAgICB3aWR0aDogMTAwJTtcbiAgICBoZWlnaHQ6IDEwMCU7XG4gIH1cbjwvc3R5bGU+IiwiLyohXG4gKiBpcy1leHRlbmRhYmxlIDxodHRwczovL2dpdGh1Yi5jb20vam9uc2NobGlua2VydC9pcy1leHRlbmRhYmxlPlxuICpcbiAqIENvcHlyaWdodCAoYykgMjAxNSwgSm9uIFNjaGxpbmtlcnQuXG4gKiBMaWNlbnNlZCB1bmRlciB0aGUgTUlUIExpY2Vuc2UuXG4gKi9cblxuJ3VzZSBzdHJpY3QnO1xuXG5tb2R1bGUuZXhwb3J0cyA9IGZ1bmN0aW9uIGlzRXh0ZW5kYWJsZSh2YWwpIHtcbiAgcmV0dXJuIHR5cGVvZiB2YWwgIT09ICd1bmRlZmluZWQnICYmIHZhbCAhPT0gbnVsbFxuICAgICYmICh0eXBlb2YgdmFsID09PSAnb2JqZWN0JyB8fCB0eXBlb2YgdmFsID09PSAnZnVuY3Rpb24nKTtcbn07XG4iLCIndXNlIHN0cmljdCc7XG5cbnZhciBleHRlbmQgPSByZXF1aXJlKCdleHRlbmQtc2hhbGxvdycpO1xudmFyIHJlZ2V4Q2FjaGUgPSB7fTtcbnZhciBhbGw7XG5cbnZhciBjaGFyU2V0cyA9IHtcbiAgZGVmYXVsdDoge1xuICAgICcmcXVvdDsnOiAnXCInLFxuICAgICcmIzM0Oyc6ICdcIicsXG5cbiAgICAnJmFwb3M7JzogJ1xcJycsXG4gICAgJyYjMzk7JzogJ1xcJycsXG5cbiAgICAnJmFtcDsnOiAnJicsXG4gICAgJyYjMzg7JzogJyYnLFxuXG4gICAgJyZndDsnOiAnPicsXG4gICAgJyYjNjI7JzogJz4nLFxuXG4gICAgJyZsdDsnOiAnPCcsXG4gICAgJyYjNjA7JzogJzwnXG4gIH0sXG4gIGV4dHJhczoge1xuICAgICcmY2VudDsnOiAnwqInLFxuICAgICcmIzE2MjsnOiAnwqInLFxuXG4gICAgJyZjb3B5Oyc6ICfCqScsXG4gICAgJyYjMTY5Oyc6ICfCqScsXG5cbiAgICAnJmV1cm87JzogJ+KCrCcsXG4gICAgJyYjODM2NDsnOiAn4oKsJyxcblxuICAgICcmcG91bmQ7JzogJ8KjJyxcbiAgICAnJiMxNjM7JzogJ8KjJyxcblxuICAgICcmcmVnOyc6ICfCricsXG4gICAgJyYjMTc0Oyc6ICfCricsXG5cbiAgICAnJnllbjsnOiAnwqUnLFxuICAgICcmIzE2NTsnOiAnwqUnXG4gIH1cbn07XG5cbi8vIGRvbid0IG1lcmdlIGNoYXIgc2V0cyB1bmxlc3MgXCJhbGxcIiBpcyBleHBsaWNpdGx5IGNhbGxlZFxuT2JqZWN0LmRlZmluZVByb3BlcnR5KGNoYXJTZXRzLCAnYWxsJywge1xuICBnZXQ6IGZ1bmN0aW9uKCkge1xuICAgIHJldHVybiBhbGwgfHwgKGFsbCA9IGV4dGVuZCh7fSwgY2hhclNldHMuZGVmYXVsdCwgY2hhclNldHMuZXh0cmFzKSk7XG4gIH1cbn0pO1xuXG4vKipcbiAqIENvbnZlcnQgSFRNTCBlbnRpdGllcyB0byBIVE1MIGNoYXJhY3RlcnMuXG4gKlxuICogQHBhcmFtICB7U3RyaW5nfSBgc3RyYCBTdHJpbmcgd2l0aCBIVE1MIGVudGl0aWVzIHRvIHVuLWVzY2FwZS5cbiAqIEByZXR1cm4ge1N0cmluZ31cbiAqL1xuXG5mdW5jdGlvbiB1bmVzY2FwZShzdHIsIHR5cGUpIHtcbiAgaWYgKCFpc1N0cmluZyhzdHIpKSByZXR1cm4gJyc7XG4gIHZhciBjaGFycyA9IGNoYXJTZXRzW3R5cGUgfHwgJ2RlZmF1bHQnXTtcbiAgdmFyIHJlZ2V4ID0gdG9SZWdleCh0eXBlLCBjaGFycyk7XG4gIHJldHVybiBzdHIucmVwbGFjZShyZWdleCwgZnVuY3Rpb24obSkge1xuICAgIHJldHVybiBjaGFyc1ttXTtcbiAgfSk7XG59XG5cbmZ1bmN0aW9uIHRvUmVnZXgodHlwZSwgY2hhcnMpIHtcbiAgaWYgKHJlZ2V4Q2FjaGVbdHlwZV0pIHtcbiAgICByZXR1cm4gcmVnZXhDYWNoZVt0eXBlXTtcbiAgfVxuICB2YXIga2V5cyA9IE9iamVjdC5rZXlzKGNoYXJzKS5qb2luKCd8Jyk7XG4gIHZhciByZWdleCA9IG5ldyBSZWdFeHAoJyg/PSgnICsga2V5cyArICcpKVxcXFwxJywgJ2cnKTtcbiAgcmVnZXhDYWNoZVt0eXBlXSA9IHJlZ2V4O1xuICByZXR1cm4gcmVnZXg7XG59XG5cbi8qKlxuICogUmV0dXJucyB0cnVlIGlmIHN0ciBpcyBhIG5vbi1lbXB0eSBzdHJpbmdcbiAqL1xuXG5mdW5jdGlvbiBpc1N0cmluZyhzdHIpIHtcbiAgcmV0dXJuIHN0ciAmJiB0eXBlb2Ygc3RyID09PSAnc3RyaW5nJztcbn1cblxuLyoqXG4gKiBFeHBvc2UgY2hhclNldHNcbiAqL1xuXG51bmVzY2FwZS5jaGFycyA9IGNoYXJTZXRzLmRlZmF1bHQ7XG51bmVzY2FwZS5leHRyYXMgPSBjaGFyU2V0cy5leHRyYXM7XG4vLyBkb24ndCB0cmlwIHRoZSBcImNoYXJTZXRzXCIgZ2V0dGVyIHVubGVzcyBpdCdzIGV4cGxpY2l0bHkgY2FsbGVkXG5PYmplY3QuZGVmaW5lUHJvcGVydHkodW5lc2NhcGUsICdhbGwnLCB7XG4gIGdldDogZnVuY3Rpb24oKSB7XG4gICAgcmV0dXJuIGNoYXJTZXRzLmFsbDtcbiAgfVxufSk7XG5cbi8qKlxuICogRXhwb3NlIGB1bmVzY2FwZWBcbiAqL1xuXG5tb2R1bGUuZXhwb3J0cyA9IHVuZXNjYXBlO1xuIiwiJ3VzZSBzdHJpY3QnO1xuXG52YXIgaXNPYmplY3QgPSByZXF1aXJlKCdpcy1leHRlbmRhYmxlJyk7XG5cbm1vZHVsZS5leHBvcnRzID0gZnVuY3Rpb24gZXh0ZW5kKG8vKiwgb2JqZWN0cyovKSB7XG4gIGlmICghaXNPYmplY3QobykpIHsgbyA9IHt9OyB9XG5cbiAgdmFyIGxlbiA9IGFyZ3VtZW50cy5sZW5ndGg7XG4gIGZvciAodmFyIGkgPSAxOyBpIDwgbGVuOyBpKyspIHtcbiAgICB2YXIgb2JqID0gYXJndW1lbnRzW2ldO1xuXG4gICAgaWYgKGlzT2JqZWN0KG9iaikpIHtcbiAgICAgIGFzc2lnbihvLCBvYmopO1xuICAgIH1cbiAgfVxuICByZXR1cm4gbztcbn07XG5cbmZ1bmN0aW9uIGFzc2lnbihhLCBiKSB7XG4gIGZvciAodmFyIGtleSBpbiBiKSB7XG4gICAgaWYgKGhhc093bihiLCBrZXkpKSB7XG4gICAgICBhW2tleV0gPSBiW2tleV07XG4gICAgfVxuICB9XG59XG5cbi8qKlxuICogUmV0dXJucyB0cnVlIGlmIHRoZSBnaXZlbiBga2V5YCBpcyBhbiBvd24gcHJvcGVydHkgb2YgYG9iamAuXG4gKi9cblxuZnVuY3Rpb24gaGFzT3duKG9iaiwga2V5KSB7XG4gIHJldHVybiBPYmplY3QucHJvdG90eXBlLmhhc093blByb3BlcnR5LmNhbGwob2JqLCBrZXkpO1xufVxuIiwiaW1wb3J0IGRlY29kZSBmcm9tICd1bmVzY2FwZSdcblxuZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gZGVjb2RlaHRtbChzdHIpIHtcbiAgcmV0dXJuIGRlY29kZShzdHIsICdhbGwnKVxufVxuIiwiPHN2ZWx0ZTpoZWFkPlxuICA8dGl0bGU+e2RlY29kZUhUTUwoY29udHJpYnV0b3IudGl0bGUucmVuZGVyZWQpfTwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuXG48VGl0bGUgdGl0bGU9e2NvbnRyaWJ1dG9yLnRpdGxlLnJlbmRlcmVkfS8+XG48ZGl2IGNsYXNzPVwieCB4d1wiPlxuICA8ZGl2IGNsYXNzPVwiYzEyIHNtLWMyIHAxXCI+XG4gICAgPGgyPntAaHRtbCBjb250cmlidXRvci50aXRsZS5yZW5kZXJlZH08L2gyPlxuICAgIHsjaWYgY29udHJpYnV0b3IubWV0YS5kZWdyZWUgJiYgY29udHJpYnV0b3IubWV0YS5ncmFkdWF0aW9uX3llYXJ9XG4gICAgICA8aDM+e2NvbnRyaWJ1dG9yLm1ldGEuZGVncmVlfSwge2NvbnRyaWJ1dG9yLm1ldGEuZ3JhZHVhdGlvbl95ZWFyfTwvaDM+XG4gICAgey9pZn1cbiAgPC9kaXY+XG4gIDxkaXYgY2xhc3M9XCJjMTIgc20tYzggcDFcIj5cbiAgICB7I2lmIGNvbnRyaWJ1dG9yLm1ldGEuZm9sZHNfZWRpdGVkICYmIGNvbnRyaWJ1dG9yLm1ldGEuZm9sZHNfZWRpdGVkLmxlbmd0aH1cbiAgICAgIDxoMyBjbGFzcz1cIm1iMVwiPkZvbGRzIChJc3N1ZSBFZGl0b3IpPC9oMz5cbiAgICAgIDxkaXYgY2xhc3M9XCJ4IGMxMlwiPlxuICAgICAgICB7I2VhY2ggY29udHJpYnV0b3IubWV0YS5mb2xkc19lZGl0ZWQgYXMgZm9sZH1cbiAgICAgICAgICA8ZGl2IGNsYXNzPVwiYzQgcHIxIHBiMVwiPlxuICAgICAgICAgICAgPGEgcmVsPVwicHJlZmV0Y2hcIiBocmVmPVwiL2ZvbGRzL3tmb2xkLnNsdWd9XCI+PEZ1bGxTcHJlYWQgbWVkaWE9e2ZvbGQubWV0YS5mb2xkX2Zyb250fS8+PC9hPlxuICAgICAgICAgIDwvZGl2PlxuICAgICAgICB7L2VhY2h9XG4gICAgICA8L2Rpdj5cbiAgICB7L2lmfVxuICAgIHsjaWYgY29udHJpYnV0b3IubWV0YS5mb2xkc19kZXNpZ25lZCAmJiBjb250cmlidXRvci5tZXRhLmZvbGRzX2Rlc2lnbmVkLmxlbmd0aH1cbiAgICAgIDxoMyBjbGFzcz1cIm1iMVwiPkZvbGRzIChHcmFwaGljIERlc2lnbmVyKTwvaDM+XG4gICAgICA8ZGl2IGNsYXNzPVwieCBjMTJcIj5cbiAgICAgICAgeyNlYWNoIGNvbnRyaWJ1dG9yLm1ldGEuZm9sZHNfZGVzaWduZWQgYXMgZm9sZH1cbiAgICAgICAgICA8ZGl2IGNsYXNzPVwiYzQgcHIxIHBiMVwiPlxuICAgICAgICAgICAgPGEgcmVsPVwicHJlZmV0Y2hcIiBocmVmPVwiL2ZvbGRzL3tmb2xkLnNsdWd9XCI+PEZ1bGxTcHJlYWQgbWVkaWE9e2ZvbGQubWV0YS5mb2xkX2Zyb250fS8+PC9hPlxuICAgICAgICAgIDwvZGl2PlxuICAgICAgICB7L2VhY2h9XG4gICAgICA8L2Rpdj5cbiAgICB7L2lmfVxuICAgIHsjaWYgY29udHJpYnV0b3IubWV0YS5wb3N0c19jb250cmlidXRlZCAmJiBjb250cmlidXRvci5tZXRhLnBvc3RzX2NvbnRyaWJ1dGVkLmxlbmd0aH1cbiAgICAgIDxoMz5BcnRpY2xlczwvaDM+XG4gICAgICA8QXJ0aWNsZUxpc3QgYXJ0aWNsZXM9e2NvbnRyaWJ1dG9yLm1ldGEucG9zdHNfY29udHJpYnV0ZWR9IC8+XG4gICAgey9pZn1cbiAgPC9kaXY+XG48L2Rpdj5cbjxzdHlsZT5cblxuPC9zdHlsZT5cblxuPHNjcmlwdD5cbiAgaW1wb3J0IGRlY29kZUhUTUwgZnJvbSAnLi4vX2hlbHBlcnMvZGVjb2RlLWh0bWwuanMnXG5cbiAgZXhwb3J0IGRlZmF1bHQge1xuICAgIGNvbXBvbmVudHM6IHtcbiAgICAgIEZ1bGxTcHJlYWQ6ICcuLi8uLi8uLi9jb21wb25lbnRzL0Z1bGxTcHJlYWQuaHRtbCcsXG4gICAgICBBcnRpY2xlTGlzdDogJy4uLy4uLy4uL2NvbXBvbmVudHMvQXJ0aWNsZUxpc3QuaHRtbCcsXG4gICAgICBUaXRsZTogJy4uLy4uLy4uL2NvbXBvbmVudHMvVGl0bGUuaHRtbCdcbiAgICB9LFxuICAgIGhlbHBlcnM6IHtcbiAgICAgIGRlY29kZUhUTUxcbiAgICB9LFxuICAgIGFzeW5jIHByZWxvYWQoeyBwYXJhbXMsIHF1ZXJ5IH0pIHtcbiAgICAgIGNvbnN0IG1hc2tGaWVsZHMgPSAndGl0bGUvcmVuZGVyZWQsJyArXG4gICAgICAnbWV0YSgnICtcbiAgICAgICAgJ2RlZ3JlZSxncmFkdWF0aW9uX3llYXIsJyArXG4gICAgICAgICdmb2xkc19lZGl0ZWQoc2x1ZyxtZXRhKGZvbGRfZnJvbnQobWVkaWFfZGV0YWlscyhzaXplcyhmdWxsKHNvdXJjZV91cmwpKSkpKSksJyArXG4gICAgICAgICdmb2xkc19kZXNpZ25lZChzbHVnLG1ldGEoZm9sZF9mcm9udChtZWRpYV9kZXRhaWxzKHNpemVzKGZ1bGwoc291cmNlX3VybCkpKSkpKSwnICtcbiAgICAgICAgJ3Bvc3RzX2NvbnRyaWJ1dGVkKHRpdGxlL3JlbmRlcmVkLHNsdWcsbWV0YS9jb250cmlidXRvcnModGl0bGUvcmVuZGVyZWQpKScgK1xuICAgICAgJyknXG4gICAgICBjb25zdCByZXMgPSBhd2FpdCB0aGlzLmZldGNoKGBjb250cmlidXRvcnMvJHtwYXJhbXMuc2x1Z30uanNvbj9maWVsZHM9JHttYXNrRmllbGRzfWApO1xuICAgICAgaWYgKCFyZXMub2spIHtcbiAgICAgICAgY29uc3QgbWVzc2FnZSA9IGF3YWl0IHJlcy50ZXh0KClcbiAgICAgICAgcmV0dXJuIHRoaXMuZXJyb3IocmVzLnN0YXR1cywgbWVzc2FnZSk7XG4gICAgICB9XG4gICAgICBjb25zdCBkYXRhID0gYXdhaXQgcmVzLmpzb24oKTtcbiAgICAgIHJldHVybiB7IGNvbnRyaWJ1dG9yOiBkYXRhIH07XG4gICAgfSxcbiAgICBvbmNyZWF0ZSgpIHtcbiAgICAgIGNvbnNvbGUubG9nKCdqc29uJywgdGhpcy5nZXQoKSk7XG4gICAgfSxcbiAgfTtcbjwvc2NyaXB0PiJdLCJzb3VyY2VSb290IjoiIn0=