(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["search"],{

/***/ "./components/Title.html":
/*!*******************************!*\
  !*** ./components/Title.html ***!
  \*******************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/shared.js */ "./node_modules/svelte/shared.js");
/* components/Title.html generated by Svelte v2.9.9 */


const file = "components/Title.html";

function add_css() {
	var style = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("style");
	style.id = 'svelte-quv5ds-style';
	style.textContent = "h1.svelte-quv5ds{font-size:3rem;line-height:0.9;font-weight:400;margin-bottom:3rem}@media(min-width: 768px){h1.svelte-quv5ds{font-size:4rem}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiVGl0bGUuaHRtbCIsInNvdXJjZXMiOlsiVGl0bGUuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyI8ZGl2IGNsYXNzPVwiYzEyIHoyXCI+XG4gIDxoMSBjbGFzcz1cImNvMiBjOCBzbS1jbzQgc20tYzRcIj57QGh0bWwgdGl0bGV9PC9oMT5cbjwvZGl2PlxuXG48c3R5bGU+XG4gIGgxIHtcbiAgICBmb250LXNpemU6IDNyZW07XG4gICAgbGluZS1oZWlnaHQ6IDAuOTtcbiAgICBmb250LXdlaWdodDogNDAwO1xuICAgIG1hcmdpbi1ib3R0b206IDNyZW07XG4gIH1cbiAgQG1lZGlhIChtaW4td2lkdGg6IDc2OHB4KSB7XG4gICAgaDEge1xuICAgICAgZm9udC1zaXplOiA0cmVtO1xuICAgIH1cbiAgfVxuPC9zdHlsZT4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBS0UsRUFBRSxjQUFDLENBQUMsQUFDRixTQUFTLENBQUUsSUFBSSxDQUNmLFdBQVcsQ0FBRSxHQUFHLENBQ2hCLFdBQVcsQ0FBRSxHQUFHLENBQ2hCLGFBQWEsQ0FBRSxJQUFJLEFBQ3JCLENBQUMsQUFDRCxNQUFNLEFBQUMsWUFBWSxLQUFLLENBQUMsQUFBQyxDQUFDLEFBQ3pCLEVBQUUsY0FBQyxDQUFDLEFBQ0YsU0FBUyxDQUFFLElBQUksQUFDakIsQ0FBQyxBQUNILENBQUMifQ== */";
	Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(style, document.head);
}

function create_main_fragment(component, ctx) {
	var div, h1;

	return {
		c: function create() {
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			h1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h1");
			this.h()
		},

		l: function claim(nodes) {
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			h1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "H1", { class: true }, false);
			var h1_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);

			h1_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			div_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			h1.className = "co2 c8 sm-co4 sm-c4 svelte-quv5ds";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(h1, file, 1, 2, 23);
			div.className = "c12 z2";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div, file, 0, 0, 0);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(div, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(h1, div);
			h1.innerHTML = ctx.title;
		},

		p: function update(changed, ctx) {
			if (changed.title) {
				h1.innerHTML = ctx.title;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(div);
			}
		}
	};
}

function Title(options) {
	this._debugName = '<Title>';
	if (!options || (!options.target && !options.root)) throw new Error("'target' is a required option");
	Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options);
	this._state = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])({}, options.data);
	if (!('title' in this._state)) console.warn("<Title> was created without expected data property 'title'");
	this._intro = true;

	if (!document.getElementById("svelte-quv5ds-style")) add_css();

	this._fragment = create_main_fragment(this, this._state);

	if (options.target) {
		var nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(options.target);
		options.hydrate ? this._fragment.l(nodes) : this._fragment.c();
		nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
		this._mount(options.target, options.anchor);
	}
}

Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])(Title.prototype, svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["protoDev"]);

Title.prototype._checkReadOnly = function _checkReadOnly(newState) {
};

if (true) {
	const { configure, register, reload } = __webpack_require__(/*! ./node_modules/svelte-loader/lib/hot-api.js */ "./node_modules/svelte-loader/lib/hot-api.js");

	module.hot.accept();

	if (!module.hot.data) {
		// initial load
		configure({});
		Title = register("components/Title.html", Title);
	} else {
		// hot update
		Title = reload("components/Title.html", Title);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Title);


/***/ }),

/***/ "./src/routes/search.html":
/*!********************************!*\
  !*** ./src/routes/search.html ***!
  \********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/shared.js */ "./node_modules/svelte/shared.js");
/* harmony import */ var lunr__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! lunr */ "./node_modules/lunr/lunr.js");
/* harmony import */ var lunr__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(lunr__WEBPACK_IMPORTED_MODULE_1__);
/* harmony import */ var svelte_transitions_fly__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! svelte-transitions-fly */ "./node_modules/svelte-transitions-fly/module.js");
/* harmony import */ var _components_Title_html__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../../components/Title.html */ "./components/Title.html");
/* src/routes/search.html generated by Svelte v2.9.9 */





function results({ lunrResults, resources }) {
  resources = lunrResults.map(result => {
    const resource = resources.filter(resource => {
      return resource.id == result.ref
    })[0]
    return resource
  })
  let out = {}
  for (let resource of resources) {
    if (!out[resource.type]) out[resource.type] = []
    out[resource.type].push(resource)
  }
  return out
}

function data() {
  return {
    lunrResults: [],
    searchQuery: ''
  }
};

function resultsLength(results) {
  if (!results) return false
  let out = (results.post && results.post.length) ||
    (results.fold && results.fold.length) ||
    (results.contributor && results.contributor.length)
  return out
}

var methods = {
  search(e) {
    e.preventDefault();
    const { searchQuery, index } = this.get();
    let tokens = searchQuery.split(' ')
    if (tokens[0]) tokens = tokens.map(token => token + '~1')
    const lunrResults = index.search(tokens.join(' '))
    this.set({
      lunrResults
    })
  }
};

async function preload({ params, query }) {
  const maskFields = 'resources(id,title/rendered,slug,type,meta(volume,number)),index'
  const res = await this.fetch(`search.json?fields=${maskFields}`)
  if (!res.ok) {
    const message = await res.text()
    return this.error(res.status, message);
  }
  const data = await res.json()
  return {
    resources: data.resources,
    index: lunr__WEBPACK_IMPORTED_MODULE_1___default.a.Index.load(data.index)
  }
};

const file = "src/routes/search.html";

function add_css() {
	var style = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("style");
	style.id = 'svelte-kncznk-style';
	style.textContent = "input.svelte-kncznk{border-bottom:0.2rem solid black;font-size:4rem;line-height:0.9;font-weight:400;margin-right:1rem}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2VhcmNoLmh0bWwiLCJzb3VyY2VzIjpbInNlYXJjaC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIjxzdmVsdGU6aGVhZD5cbiAgPHRpdGxlPlNlYXJjaDwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuXG48VGl0bGUgdGl0bGU9XCJTZWFyY2hcIi8+XG48ZGl2IGNsYXNzPVwieFwiPlxuICA8ZGl2IGNsYXNzPVwiZG4gc20tZGIgYzIgcDFcIj5cbiAgICA8dWw+XG4gICAgICA8bGk+PGEgcmVsPVwicHJlZmV0Y2hcIiBocmVmPVwiL2Fib3V0XCI+QWJvdXQ8L2E+PC9saT5cbiAgICAgIDxsaT48YSByZWw9XCJwcmVmZXRjaFwiIGhyZWY9XCIvc3VwcG9ydFwiPlN1cHBvcnQ8L2E+PC9saT5cbiAgICAgIDxsaT48YSByZWw9XCJwcmVmZXRjaFwiIGhyZWY9XCIvc2VhcmNoXCI+U2VhcmNoPC9hPjwvbGk+XG4gICAgPC91bD5cbiAgPC9kaXY+XG4gIDxkaXYgY2xhc3M9XCJjMTIgc20tYzEwIHAxXCI+XG4gICAgPGZvcm0gY2xhc3M9XCJtYjNcIiBvbjpzdWJtaXQ9XCJzZWFyY2goZXZlbnQpXCI+XG4gICAgICA8aW5wdXQgY2xhc3M9XCJjMTAgc20tYzhcIiBiaW5kOnZhbHVlPXNlYXJjaFF1ZXJ5IHR5cGU9dGV4dD5cbiAgICAgIDxidXR0b24gdHlwZT1zdWJtaXQ+4oaSPC9idXR0b24+XG4gICAgPC9mb3JtPlxuICAgIHsjaWYgcmVzdWx0c0xlbmd0aChyZXN1bHRzKX1cbiAgICAgIDxkaXYgY2xhc3M9XCJyZXN1bHRzIGMxMiB4d1wiIHRyYW5zaXRpb246Zmx5PSd7eToyMH0nPlxuICAgICAgICB7I2lmIHJlc3VsdHMucG9zdCAmJiByZXN1bHRzLnBvc3QubGVuZ3RofVxuICAgICAgICA8ZGl2IGNsYXNzPVwiYzEyIHNtLWM0XCI+XG4gICAgICAgICAgPGgxPkFydGljbGVzPC9oMT5cbiAgICAgICAgICA8dWw+XG4gICAgICAgICAgICB7I2VhY2ggcmVzdWx0cy5wb3N0IGFzIHJlc3VsdH1cbiAgICAgICAgICAgICAgPGxpPjxoMT48YSByZWw9J3ByZWZldGNoJyBocmVmPSdhcnRpY2xlcy97cmVzdWx0LnNsdWd9Jz57QGh0bWwgcmVzdWx0LnRpdGxlLnJlbmRlcmVkIH08L2E+PC9oMT48L2xpPlxuICAgICAgICAgICAgey9lYWNofVxuICAgICAgICAgIDwvdWw+XG4gICAgICAgIDwvZGl2PlxuICAgICAgICB7L2lmfVxuICAgICAgICB7I2lmIHJlc3VsdHMuZm9sZCAmJiByZXN1bHRzLmZvbGQubGVuZ3RofVxuICAgICAgICA8ZGl2IGNsYXNzPVwiYzEyIHNtLWM0XCI+XG4gICAgICAgICAgPGgxPkZvbGRzPC9oMT5cbiAgICAgICAgICA8dWw+XG4gICAgICAgICAgICB7I2VhY2ggcmVzdWx0cy5mb2xkIGFzIHJlc3VsdH1cbiAgICAgICAgICAgICAgPGxpPjxoMT48YSByZWw9J3ByZWZldGNoJyBocmVmPSdmb2xkcy97cmVzdWx0Lm1ldGEudm9sdW1lfS17cmVzdWx0Lm1ldGEubnVtYmVyfSc+e0BodG1sIHJlc3VsdC50aXRsZS5yZW5kZXJlZCB9PC9hPjwvaDE+PC9saT5cbiAgICAgICAgICAgIHsvZWFjaH1cbiAgICAgICAgICA8L3VsPlxuICAgICAgICA8L2Rpdj5cbiAgICAgICAgey9pZn1cbiAgICAgICAgeyNpZiByZXN1bHRzLmNvbnRyaWJ1dG9yICYmIHJlc3VsdHMuY29udHJpYnV0b3IubGVuZ3RofVxuICAgICAgICA8ZGl2IGNsYXNzPVwiYzEyIHNtLWM0XCI+XG4gICAgICAgICAgPGgxPkNvbnRyaWJ1dG9yczwvaDE+XG4gICAgICAgICAgPHVsPlxuICAgICAgICAgICAgeyNlYWNoIHJlc3VsdHMuY29udHJpYnV0b3IgYXMgcmVzdWx0fVxuICAgICAgICAgICAgICA8bGk+PGgxPjxhIHJlbD0ncHJlZmV0Y2gnIGhyZWY9J2NvbnRyaWJ1dG9ycy97cmVzdWx0LnNsdWd9Jz57QGh0bWwgcmVzdWx0LnRpdGxlLnJlbmRlcmVkIH08L2E+PC9oMT48L2xpPlxuICAgICAgICAgICAgey9lYWNofVxuICAgICAgICAgIDwvdWw+XG4gICAgICAgIDwvZGl2PlxuICAgICAgICB7L2lmfVxuICAgICAgPC9kaXY+XG4gICAgey9pZn1cbiAgPC9kaXY+XG48L2Rpdj5cblxuPHN0eWxlPlxuICBpbnB1dCB7XG4gICAgYm9yZGVyLWJvdHRvbTogMC4ycmVtIHNvbGlkIGJsYWNrO1xuICAgIGZvbnQtc2l6ZTogNHJlbTtcbiAgICBsaW5lLWhlaWdodDogMC45O1xuICAgIGZvbnQtd2VpZ2h0OiA0MDA7XG4gICAgbWFyZ2luLXJpZ2h0OiAxcmVtO1xuICB9XG48L3N0eWxlPlxuXG48c2NyaXB0PlxuICBpbXBvcnQgbHVuciBmcm9tICdsdW5yJ1xuICBpbXBvcnQgZmx5IGZyb20gJ3N2ZWx0ZS10cmFuc2l0aW9ucy1mbHknO1xuXG4gIGV4cG9ydCBkZWZhdWx0IHtcbiAgICBoZWxwZXJzOiB7XG4gICAgICByZXN1bHRzTGVuZ3RoOiAocmVzdWx0cykgPT4ge1xuICAgICAgICBpZiAoIXJlc3VsdHMpIHJldHVybiBmYWxzZVxuICAgICAgICBsZXQgb3V0ID0gKHJlc3VsdHMucG9zdCAmJiByZXN1bHRzLnBvc3QubGVuZ3RoKSB8fFxuICAgICAgICAgIChyZXN1bHRzLmZvbGQgJiYgcmVzdWx0cy5mb2xkLmxlbmd0aCkgfHxcbiAgICAgICAgICAocmVzdWx0cy5jb250cmlidXRvciAmJiByZXN1bHRzLmNvbnRyaWJ1dG9yLmxlbmd0aClcbiAgICAgICAgcmV0dXJuIG91dFxuICAgICAgfVxuICAgIH0sXG4gICAgY29tcG9uZW50czoge1xuICAgICAgVGl0bGU6ICcuLi8uLi9jb21wb25lbnRzL1RpdGxlLmh0bWwnXG4gICAgfSxcbiAgICBtZXRob2RzOiB7XG4gICAgICBzZWFyY2goZSkge1xuICAgICAgICBlLnByZXZlbnREZWZhdWx0KCk7XG4gICAgICAgIGNvbnN0IHsgc2VhcmNoUXVlcnksIGluZGV4IH0gPSB0aGlzLmdldCgpO1xuICAgICAgICBsZXQgdG9rZW5zID0gc2VhcmNoUXVlcnkuc3BsaXQoJyAnKVxuICAgICAgICBpZiAodG9rZW5zWzBdKSB0b2tlbnMgPSB0b2tlbnMubWFwKHRva2VuID0+IHRva2VuICsgJ34xJylcbiAgICAgICAgY29uc3QgbHVuclJlc3VsdHMgPSBpbmRleC5zZWFyY2godG9rZW5zLmpvaW4oJyAnKSlcbiAgICAgICAgdGhpcy5zZXQoe1xuICAgICAgICAgIGx1bnJSZXN1bHRzXG4gICAgICAgIH0pXG4gICAgICB9XG4gICAgfSxcbiAgICB0cmFuc2l0aW9uczogeyBmbHkgfSxcbiAgICBkYXRhKCkge1xuICAgICAgcmV0dXJuIHtcbiAgICAgICAgbHVuclJlc3VsdHM6IFtdLFxuICAgICAgICBzZWFyY2hRdWVyeTogJydcbiAgICAgIH1cbiAgICB9LFxuICAgIGFzeW5jIHByZWxvYWQoeyBwYXJhbXMsIHF1ZXJ5IH0pIHtcbiAgICAgIGNvbnN0IG1hc2tGaWVsZHMgPSAncmVzb3VyY2VzKGlkLHRpdGxlL3JlbmRlcmVkLHNsdWcsdHlwZSxtZXRhKHZvbHVtZSxudW1iZXIpKSxpbmRleCdcbiAgICAgIGNvbnN0IHJlcyA9IGF3YWl0IHRoaXMuZmV0Y2goYHNlYXJjaC5qc29uP2ZpZWxkcz0ke21hc2tGaWVsZHN9YClcbiAgICAgIGlmICghcmVzLm9rKSB7XG4gICAgICAgIGNvbnN0IG1lc3NhZ2UgPSBhd2FpdCByZXMudGV4dCgpXG4gICAgICAgIHJldHVybiB0aGlzLmVycm9yKHJlcy5zdGF0dXMsIG1lc3NhZ2UpO1xuICAgICAgfVxuICAgICAgY29uc3QgZGF0YSA9IGF3YWl0IHJlcy5qc29uKClcbiAgICAgIHJldHVybiB7XG4gICAgICAgIHJlc291cmNlczogZGF0YS5yZXNvdXJjZXMsXG4gICAgICAgIGluZGV4OiBsdW5yLkluZGV4LmxvYWQoZGF0YS5pbmRleClcbiAgICAgIH1cbiAgICB9LFxuICAgIGNvbXB1dGVkOiB7XG4gICAgICByZXN1bHRzOiAoeyBsdW5yUmVzdWx0cywgcmVzb3VyY2VzIH0pID0+IHtcbiAgICAgICAgcmVzb3VyY2VzID0gbHVuclJlc3VsdHMubWFwKHJlc3VsdCA9PiB7XG4gICAgICAgICAgY29uc3QgcmVzb3VyY2UgPSByZXNvdXJjZXMuZmlsdGVyKHJlc291cmNlID0+IHtcbiAgICAgICAgICAgIHJldHVybiByZXNvdXJjZS5pZCA9PSByZXN1bHQucmVmXG4gICAgICAgICAgfSlbMF1cbiAgICAgICAgICByZXR1cm4gcmVzb3VyY2VcbiAgICAgICAgfSlcbiAgICAgICAgbGV0IG91dCA9IHt9XG4gICAgICAgIGZvciAobGV0IHJlc291cmNlIG9mIHJlc291cmNlcykge1xuICAgICAgICAgIGlmICghb3V0W3Jlc291cmNlLnR5cGVdKSBvdXRbcmVzb3VyY2UudHlwZV0gPSBbXVxuICAgICAgICAgIG91dFtyZXNvdXJjZS50eXBlXS5wdXNoKHJlc291cmNlKVxuICAgICAgICB9XG4gICAgICAgIHJldHVybiBvdXRcbiAgICAgIH1cbiAgICB9XG4gIH07XG48L3NjcmlwdD4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBd0RFLEtBQUssY0FBQyxDQUFDLEFBQ0wsYUFBYSxDQUFFLE1BQU0sQ0FBQyxLQUFLLENBQUMsS0FBSyxDQUNqQyxTQUFTLENBQUUsSUFBSSxDQUNmLFdBQVcsQ0FBRSxHQUFHLENBQ2hCLFdBQVcsQ0FBRSxHQUFHLENBQ2hCLFlBQVksQ0FBRSxJQUFJLEFBQ3BCLENBQUMifQ== */";
	Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(style, document.head);
}

function create_main_fragment(component, ctx) {
	var text, text_1, div, div_1, ul, li, a, text_2, li_1, a_1, text_3, li_2, a_2, text_4, text_6, div_2, form, input, input_updating = false, text_7, button, text_8, text_10;

	var title_initial_data = { title: "Search" };
	var title = new _components_Title_html__WEBPACK_IMPORTED_MODULE_3__["default"]({
		root: component.root,
		store: component.store,
		data: title_initial_data
	});

	function input_input_handler() {
		input_updating = true;
		component.set({ searchQuery: input.value });
		input_updating = false;
	}

	function submit_handler(event) {
		component.search(event);
	}

	var if_block = (resultsLength(ctx.results)) && create_if_block(component, ctx);

	return {
		c: function create() {
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n\n");
			title._fragment.c();
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n");
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			div_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("ul");
			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("li");
			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("a");
			text_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("About");
			li_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("li");
			a_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("a");
			text_3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("Support");
			li_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("li");
			a_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("a");
			text_4 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("Search");
			text_6 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n  ");
			div_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			form = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("form");
			input = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("input");
			text_7 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n      ");
			button = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("button");
			text_8 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("→");
			text_10 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n    ");
			if (if_block) if_block.c();
			this.h()
		},

		l: function claim(nodes) {
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(nodes, "\n\n");
			title._fragment.l(nodes);
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(nodes, "\n");

			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			div_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "DIV", { class: true }, false);
			var div_1_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div_1);

			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_1_nodes, "UL", {}, false);
			var ul_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(ul_nodes, "LI", {}, false);
			var li_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(li);

			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(li_nodes, "A", { rel: true, href: true }, false);
			var a_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			text_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(a_nodes, "About");
			a_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			li_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);

			li_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(ul_nodes, "LI", {}, false);
			var li_1_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(li_1);

			a_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(li_1_nodes, "A", { rel: true, href: true }, false);
			var a_1_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(a_1);

			text_3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(a_1_nodes, "Support");
			a_1_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			li_1_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);

			li_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(ul_nodes, "LI", {}, false);
			var li_2_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(li_2);

			a_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(li_2_nodes, "A", { rel: true, href: true }, false);
			var a_2_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(a_2);

			text_4 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(a_2_nodes, "Search");
			a_2_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			li_2_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			ul_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			div_1_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_6 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_nodes, "\n  ");

			div_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "DIV", { class: true }, false);
			var div_2_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div_2);

			form = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_2_nodes, "FORM", { class: true }, false);
			var form_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(form);

			input = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(form_nodes, "INPUT", { class: true, type: true }, false);
			var input_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(input);

			input_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_7 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(form_nodes, "\n      ");

			button = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(form_nodes, "BUTTON", { type: true }, false);
			var button_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(button);

			text_8 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(button_nodes, "→");
			button_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			form_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_10 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_2_nodes, "\n    ");
			if (if_block) if_block.l(div_2_nodes);
			div_2_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			div_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			document.title = "Search";
			a.rel = "prefetch";
			a.href = "/about";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(a, file, 8, 10, 144);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(li, file, 8, 6, 140);
			a_1.rel = "prefetch";
			a_1.href = "/support";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(a_1, file, 9, 10, 201);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(li_1, file, 9, 6, 197);
			a_2.rel = "prefetch";
			a_2.href = "/search";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(a_2, file, 10, 10, 262);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(li_2, file, 10, 6, 258);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(ul, file, 7, 4, 129);
			div_1.className = "dn sm-db c2 p1";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div_1, file, 6, 2, 96);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addListener"])(input, "input", input_input_handler);
			input.className = "c10 sm-c8 svelte-kncznk";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["setAttribute"])(input, "type", "text");
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(input, file, 15, 6, 415);
			button.type = "submit";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(button, file, 16, 6, 480);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addListener"])(form, "submit", submit_handler);
			form.className = "mb3";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(form, file, 14, 4, 364);
			div_2.className = "c12 sm-c10 p1";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div_2, file, 13, 2, 332);
			div.className = "x";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div, file, 5, 0, 78);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(text, target, anchor);
			title._mount(target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(text_1, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(div, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(div_1, div);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(ul, div_1);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(li, ul);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(a, li);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_2, a);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(li_1, ul);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(a_1, li_1);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_3, a_1);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(li_2, ul);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(a_2, li_2);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_4, a_2);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_6, div);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(div_2, div);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(form, div_2);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(input, form);

			input.value = ctx.searchQuery;

			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_7, form);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(button, form);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_8, button);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_10, div_2);
			if (if_block) if_block.i(div_2, null);
		},

		p: function update(changed, ctx) {
			if (!input_updating) input.value = ctx.searchQuery;

			if (resultsLength(ctx.results)) {
				if (if_block) {
					if_block.p(changed, ctx);
				} else {
					if_block = create_if_block(component, ctx);
					if (if_block) if_block.c();
				}

				if_block.i(div_2, null);
			} else if (if_block) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["groupOutros"])();
				if_block.o(function() {
					if_block.d(1);
					if_block = null;
				});
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(text);
			}

			title.destroy(detach);
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(text_1);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(div);
			}

			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["removeListener"])(input, "input", input_input_handler);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["removeListener"])(form, "submit", submit_handler);
			if (if_block) if_block.d();
		}
	};
}

// (25:12) {#each results.post as result}
function create_each_block(component, ctx) {
	var li, h1, a, raw_value = ctx.result.title.rendered, a_href_value;

	return {
		c: function create() {
			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("li");
			h1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h1");
			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("a");
			this.h()
		},

		l: function claim(nodes) {
			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "LI", {}, false);
			var li_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(li);

			h1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(li_nodes, "H1", {}, false);
			var h1_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);

			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(h1_nodes, "A", { rel: true, href: true }, false);
			var a_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			a_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			h1_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			li_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			a.rel = "prefetch";
			a.href = a_href_value = "articles/" + ctx.result.slug;
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(a, file, 25, 22, 805);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(h1, file, 25, 18, 801);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(li, file, 25, 14, 797);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(li, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(h1, li);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(a, h1);
			a.innerHTML = raw_value;
		},

		p: function update(changed, ctx) {
			if ((changed.results) && raw_value !== (raw_value = ctx.result.title.rendered)) {
				a.innerHTML = raw_value;
			}

			if ((changed.results) && a_href_value !== (a_href_value = "articles/" + ctx.result.slug)) {
				a.href = a_href_value;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(li);
			}
		}
	};
}

// (21:8) {#if results.post && results.post.length}
function create_if_block_1(component, ctx) {
	var div, h1, text, text_1, ul;

	var each_value = ctx.results.post;

	var each_blocks = [];

	for (var i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(component, get_each_context(ctx, each_value, i));
	}

	return {
		c: function create() {
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			h1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h1");
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("Articles");
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n          ");
			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("ul");

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}
			this.h()
		},

		l: function claim(nodes) {
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			h1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "H1", {}, false);
			var h1_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);

			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(h1_nodes, "Articles");
			h1_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_nodes, "\n          ");

			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "UL", {}, false);
			var ul_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(ul_nodes);
			}

			ul_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			div_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(h1, file, 22, 10, 707);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(ul, file, 23, 10, 735);
			div.className = "c12 sm-c4";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div, file, 21, 8, 673);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(div, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(h1, div);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text, h1);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_1, div);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(ul, div);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(ul, null);
			}
		},

		p: function update(changed, ctx) {
			if (changed.results) {
				each_value = ctx.results.post;

				for (var i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(changed, child_ctx);
					} else {
						each_blocks[i] = create_each_block(component, child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(ul, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}
				each_blocks.length = each_value.length;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(div);
			}

			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["destroyEach"])(each_blocks, detach);
		}
	};
}

// (35:12) {#each results.fold as result}
function create_each_block_1(component, ctx) {
	var li, h1, a, raw_value = ctx.result.title.rendered, a_href_value;

	return {
		c: function create() {
			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("li");
			h1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h1");
			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("a");
			this.h()
		},

		l: function claim(nodes) {
			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "LI", {}, false);
			var li_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(li);

			h1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(li_nodes, "H1", {}, false);
			var h1_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);

			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(h1_nodes, "A", { rel: true, href: true }, false);
			var a_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			a_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			h1_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			li_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			a.rel = "prefetch";
			a.href = a_href_value = "folds/" + ctx.result.meta.volume + "-" + ctx.result.meta.number;
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(a, file, 35, 22, 1150);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(h1, file, 35, 18, 1146);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(li, file, 35, 14, 1142);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(li, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(h1, li);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(a, h1);
			a.innerHTML = raw_value;
		},

		p: function update(changed, ctx) {
			if ((changed.results) && raw_value !== (raw_value = ctx.result.title.rendered)) {
				a.innerHTML = raw_value;
			}

			if ((changed.results) && a_href_value !== (a_href_value = "folds/" + ctx.result.meta.volume + "-" + ctx.result.meta.number)) {
				a.href = a_href_value;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(li);
			}
		}
	};
}

// (31:8) {#if results.fold && results.fold.length}
function create_if_block_2(component, ctx) {
	var div, h1, text, text_1, ul;

	var each_value_1 = ctx.results.fold;

	var each_blocks = [];

	for (var i = 0; i < each_value_1.length; i += 1) {
		each_blocks[i] = create_each_block_1(component, get_each_context_1(ctx, each_value_1, i));
	}

	return {
		c: function create() {
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			h1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h1");
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("Folds");
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n          ");
			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("ul");

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}
			this.h()
		},

		l: function claim(nodes) {
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			h1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "H1", {}, false);
			var h1_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);

			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(h1_nodes, "Folds");
			h1_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_nodes, "\n          ");

			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "UL", {}, false);
			var ul_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(ul_nodes);
			}

			ul_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			div_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(h1, file, 32, 10, 1055);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(ul, file, 33, 10, 1080);
			div.className = "c12 sm-c4";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div, file, 31, 8, 1021);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(div, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(h1, div);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text, h1);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_1, div);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(ul, div);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(ul, null);
			}
		},

		p: function update(changed, ctx) {
			if (changed.results) {
				each_value_1 = ctx.results.fold;

				for (var i = 0; i < each_value_1.length; i += 1) {
					const child_ctx = get_each_context_1(ctx, each_value_1, i);

					if (each_blocks[i]) {
						each_blocks[i].p(changed, child_ctx);
					} else {
						each_blocks[i] = create_each_block_1(component, child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(ul, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}
				each_blocks.length = each_value_1.length;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(div);
			}

			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["destroyEach"])(each_blocks, detach);
		}
	};
}

// (45:12) {#each results.contributor as result}
function create_each_block_2(component, ctx) {
	var li, h1, a, raw_value = ctx.result.title.rendered, a_href_value;

	return {
		c: function create() {
			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("li");
			h1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h1");
			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("a");
			this.h()
		},

		l: function claim(nodes) {
			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "LI", {}, false);
			var li_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(li);

			h1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(li_nodes, "H1", {}, false);
			var h1_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);

			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(h1_nodes, "A", { rel: true, href: true }, false);
			var a_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			a_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			h1_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			li_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			a.rel = "prefetch";
			a.href = a_href_value = "contributors/" + ctx.result.slug;
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(a, file, 45, 22, 1548);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(h1, file, 45, 18, 1544);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(li, file, 45, 14, 1540);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(li, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(h1, li);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(a, h1);
			a.innerHTML = raw_value;
		},

		p: function update(changed, ctx) {
			if ((changed.results) && raw_value !== (raw_value = ctx.result.title.rendered)) {
				a.innerHTML = raw_value;
			}

			if ((changed.results) && a_href_value !== (a_href_value = "contributors/" + ctx.result.slug)) {
				a.href = a_href_value;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(li);
			}
		}
	};
}

// (41:8) {#if results.contributor && results.contributor.length}
function create_if_block_3(component, ctx) {
	var div, h1, text, text_1, ul;

	var each_value_2 = ctx.results.contributor;

	var each_blocks = [];

	for (var i = 0; i < each_value_2.length; i += 1) {
		each_blocks[i] = create_each_block_2(component, get_each_context_2(ctx, each_value_2, i));
	}

	return {
		c: function create() {
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			h1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h1");
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("Contributors");
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n          ");
			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("ul");

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}
			this.h()
		},

		l: function claim(nodes) {
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			h1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "H1", {}, false);
			var h1_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);

			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(h1_nodes, "Contributors");
			h1_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_nodes, "\n          ");

			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "UL", {}, false);
			var ul_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(ul_nodes);
			}

			ul_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			div_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(h1, file, 42, 10, 1439);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(ul, file, 43, 10, 1471);
			div.className = "c12 sm-c4";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div, file, 41, 8, 1405);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(div, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(h1, div);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text, h1);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_1, div);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(ul, div);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(ul, null);
			}
		},

		p: function update(changed, ctx) {
			if (changed.results) {
				each_value_2 = ctx.results.contributor;

				for (var i = 0; i < each_value_2.length; i += 1) {
					const child_ctx = get_each_context_2(ctx, each_value_2, i);

					if (each_blocks[i]) {
						each_blocks[i].p(changed, child_ctx);
					} else {
						each_blocks[i] = create_each_block_2(component, child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(ul, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}
				each_blocks.length = each_value_2.length;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(div);
			}

			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["destroyEach"])(each_blocks, detach);
		}
	};
}

// (19:4) {#if resultsLength(results)}
function create_if_block(component, ctx) {
	var div, text, text_1, div_transition, current;

	var if_block = (ctx.results.post && ctx.results.post.length) && create_if_block_1(component, ctx);

	var if_block_1 = (ctx.results.fold && ctx.results.fold.length) && create_if_block_2(component, ctx);

	var if_block_2 = (ctx.results.contributor && ctx.results.contributor.length) && create_if_block_3(component, ctx);

	return {
		c: function create() {
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			if (if_block) if_block.c();
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n        ");
			if (if_block_1) if_block_1.c();
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n        ");
			if (if_block_2) if_block_2.c();
			this.h()
		},

		l: function claim(nodes) {
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			if (if_block) if_block.l(div_nodes);
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_nodes, "\n        ");
			if (if_block_1) if_block_1.l(div_nodes);
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_nodes, "\n        ");
			if (if_block_2) if_block_2.l(div_nodes);
			div_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			div.className = "results c12 xw";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div, file, 19, 6, 562);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(div, target, anchor);
			if (if_block) if_block.m(div, null);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text, div);
			if (if_block_1) if_block_1.m(div, null);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_1, div);
			if (if_block_2) if_block_2.m(div, null);
			current = true;
		},

		p: function update(changed, ctx) {
			if (ctx.results.post && ctx.results.post.length) {
				if (if_block) {
					if_block.p(changed, ctx);
				} else {
					if_block = create_if_block_1(component, ctx);
					if_block.c();
					if_block.m(div, text);
				}
			} else if (if_block) {
				if_block.d(1);
				if_block = null;
			}

			if (ctx.results.fold && ctx.results.fold.length) {
				if (if_block_1) {
					if_block_1.p(changed, ctx);
				} else {
					if_block_1 = create_if_block_2(component, ctx);
					if_block_1.c();
					if_block_1.m(div, text_1);
				}
			} else if (if_block_1) {
				if_block_1.d(1);
				if_block_1 = null;
			}

			if (ctx.results.contributor && ctx.results.contributor.length) {
				if (if_block_2) {
					if_block_2.p(changed, ctx);
				} else {
					if_block_2 = create_if_block_3(component, ctx);
					if_block_2.c();
					if_block_2.m(div, null);
				}
			} else if (if_block_2) {
				if_block_2.d(1);
				if_block_2 = null;
			}
		},

		i: function intro(target, anchor) {
			if (current) return;
			if (component.root._intro) {
				if (div_transition) div_transition.invalidate();

				component.root._aftercreate.push(() => {
					if (!div_transition) div_transition = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["wrapTransition"])(component, div, svelte_transitions_fly__WEBPACK_IMPORTED_MODULE_2__["default"], {y:20}, true);
					div_transition.run(1);
				});
			}
			this.m(target, anchor);
		},

		o: function outro(outrocallback) {
			if (!current) return;

			if (!div_transition) div_transition = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["wrapTransition"])(component, div, svelte_transitions_fly__WEBPACK_IMPORTED_MODULE_2__["default"], {y:20}, false);
			div_transition.run(0, () => {
				outrocallback();
				div_transition = null;
			});

			current = false;
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(div);
			}

			if (if_block) if_block.d();
			if (if_block_1) if_block_1.d();
			if (if_block_2) if_block_2.d();
			if (detach) {
				if (div_transition) div_transition.abort();
			}
		}
	};
}

function get_each_context(ctx, list, i) {
	const child_ctx = Object.create(ctx);
	child_ctx.result = list[i];
	child_ctx.each_value = list;
	child_ctx.result_index = i;
	return child_ctx;
}

function get_each_context_1(ctx, list, i) {
	const child_ctx = Object.create(ctx);
	child_ctx.result = list[i];
	child_ctx.each_value_1 = list;
	child_ctx.result_index_1 = i;
	return child_ctx;
}

function get_each_context_2(ctx, list, i) {
	const child_ctx = Object.create(ctx);
	child_ctx.result = list[i];
	child_ctx.each_value_2 = list;
	child_ctx.result_index_2 = i;
	return child_ctx;
}

function Search(options) {
	this._debugName = '<Search>';
	if (!options || (!options.target && !options.root)) throw new Error("'target' is a required option");
	Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options);
	this._state = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])(data(), options.data);
	this._recompute({ lunrResults: 1, resources: 1 }, this._state);
	if (!('lunrResults' in this._state)) console.warn("<Search> was created without expected data property 'lunrResults'");
	if (!('resources' in this._state)) console.warn("<Search> was created without expected data property 'resources'");
	if (!('searchQuery' in this._state)) console.warn("<Search> was created without expected data property 'searchQuery'");
	this._intro = true;

	if (!document.getElementById("svelte-kncznk-style")) add_css();

	if (!options.root) {
		this._oncreate = [];
		this._beforecreate = [];
		this._aftercreate = [];
	}

	this._fragment = create_main_fragment(this, this._state);

	if (options.target) {
		var nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(options.target);
		options.hydrate ? this._fragment.l(nodes) : this._fragment.c();
		nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
		this._mount(options.target, options.anchor);

		this._lock = true;
		Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["callAll"])(this._beforecreate);
		Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["callAll"])(this._oncreate);
		Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["callAll"])(this._aftercreate);
		this._lock = false;
	}
}

Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])(Search.prototype, svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["protoDev"]);
Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])(Search.prototype, methods);

Search.prototype._checkReadOnly = function _checkReadOnly(newState) {
	if ('results' in newState && !this._updatingReadonlyProperty) throw new Error("<Search>: Cannot set read-only property 'results'");
};

Search.prototype._recompute = function _recompute(changed, state) {
	if (changed.lunrResults || changed.resources) {
		if (this._differs(state.results, (state.results = results(state)))) changed.results = true;
	}
}

Search.preload = preload;

if (true) {
	const { configure, register, reload } = __webpack_require__(/*! ./node_modules/svelte-loader/lib/hot-api.js */ "./node_modules/svelte-loader/lib/hot-api.js");

	module.hot.accept();

	if (!module.hot.data) {
		// initial load
		configure({});
		Search = register("src/routes/search.html", Search);
	} else {
		// hot update
		Search = reload("src/routes/search.html", Search);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Search);


/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9jb21wb25lbnRzL1RpdGxlLmh0bWwiLCJ3ZWJwYWNrOi8vLy4vc3JjL3JvdXRlcy9zZWFyY2guaHRtbCJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztzQkFDeUMsS0FBSzs7Ozs7dUJBQUwsS0FBSzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7aUJDa0g5QixFQUFFLFdBQVcsRUFBRSxTQUFTLEVBQUUsRUFBSztBQUN6QyxFQUFFLFNBQVMsR0FBRyxXQUFXLENBQUMsR0FBRyxDQUFDLE1BQU0sSUFBSTtBQUN4QyxJQUFJLE1BQU0sUUFBUSxHQUFHLFNBQVMsQ0FBQyxNQUFNLENBQUMsUUFBUSxJQUFJO0FBQ2xELE1BQU0sT0FBTyxRQUFRLENBQUMsRUFBRSxJQUFJLE1BQU0sQ0FBQyxHQUFHO0FBQ3RDLEtBQUssQ0FBQyxDQUFDLENBQUMsQ0FBQztBQUNULElBQUksT0FBTyxRQUFRO0FBQ25CLEdBQUcsQ0FBQztBQUNKLEVBQUUsSUFBSSxHQUFHLEdBQUcsRUFBRTtBQUNkLEVBQUUsS0FBSyxJQUFJLFFBQVEsSUFBSSxTQUFTLEVBQUU7QUFDbEMsSUFBSSxJQUFJLENBQUMsR0FBRyxDQUFDLFFBQVEsQ0FBQyxJQUFJLENBQUMsRUFBRSxHQUFHLENBQUMsUUFBUSxDQUFDLElBQUksQ0FBQyxHQUFHLEVBQUU7QUFDcEQsSUFBSSxHQUFHLENBQUMsUUFBUSxDQUFDLElBQUksQ0FBQyxDQUFDLElBQUksQ0FBQyxRQUFRLENBQUM7QUFDckMsR0FBRztBQUNILEVBQUUsT0FBTyxHQUFHO0FBQ1osQ0FBQzs7YUFqQ0MsR0FBRztBQUNQLEVBQUUsT0FBTztBQUNULElBQUksV0FBVyxFQUFFLEVBQUU7QUFDbkIsSUFBSSxXQUFXLEVBQUUsRUFBRTtBQUNuQixHQUFHO0FBQ0gsQ0FBQzs7dUJBN0JpQixPQUFPLEVBQUs7QUFDNUIsRUFBRSxJQUFJLENBQUMsT0FBTyxFQUFFLE9BQU8sS0FBSztBQUM1QixFQUFFLElBQUksR0FBRyxHQUFHLENBQUMsT0FBTyxDQUFDLElBQUksSUFBSSxPQUFPLENBQUMsSUFBSSxDQUFDLE1BQU07QUFDaEQsS0FBSyxPQUFPLENBQUMsSUFBSSxJQUFJLE9BQU8sQ0FBQyxJQUFJLENBQUMsTUFBTSxDQUFDO0FBQ3pDLEtBQUssT0FBTyxDQUFDLFdBQVcsSUFBSSxPQUFPLENBQUMsV0FBVyxDQUFDLE1BQU0sQ0FBQztBQUN2RCxFQUFFLE9BQU8sR0FBRztBQUNaLENBQUM7O2NBS007QUFDVCxFQUFFLE1BQU0sQ0FBQyxDQUFDLEVBQUU7QUFDWixJQUFJLENBQUMsQ0FBQyxjQUFjLEVBQUUsQ0FBQztBQUN2QixJQUFJLE1BQU0sRUFBRSxXQUFXLEVBQUUsS0FBSyxFQUFFLEdBQUcsSUFBSSxDQUFDLEdBQUcsRUFBRSxDQUFDO0FBQzlDLElBQUksSUFBSSxNQUFNLEdBQUcsV0FBVyxDQUFDLEtBQUssQ0FBQyxHQUFHLENBQUM7QUFDdkMsSUFBSSxJQUFJLE1BQU0sQ0FBQyxDQUFDLENBQUMsRUFBRSxNQUFNLEdBQUcsTUFBTSxDQUFDLEdBQUcsQ0FBQyxLQUFLLElBQUksS0FBSyxHQUFHLElBQUksQ0FBQztBQUM3RCxJQUFJLE1BQU0sV0FBVyxHQUFHLEtBQUssQ0FBQyxNQUFNLENBQUMsTUFBTSxDQUFDLElBQUksQ0FBQyxHQUFHLENBQUMsQ0FBQztBQUN0RCxJQUFJLElBQUksQ0FBQyxHQUFHLENBQUM7QUFDYixNQUFNLFdBQVc7QUFDakIsS0FBSyxDQUFDO0FBQ04sR0FBRztBQUNILENBQUM7O3NCQVFZLENBQUMsRUFBRSxNQUFNLEVBQUUsS0FBSyxFQUFFLEVBQUU7QUFDakMsRUFBRSxNQUFNLFVBQVUsR0FBRyxrRUFBa0U7QUFDdkYsRUFBRSxNQUFNLEdBQUcsR0FBRyxNQUFNLElBQUksQ0FBQyxLQUFLLENBQUMsQ0FBQyxtQkFBbUIsRUFBRSxVQUFVLENBQUMsQ0FBQyxDQUFDO0FBQ2xFLEVBQUUsSUFBSSxDQUFDLEdBQUcsQ0FBQyxFQUFFLEVBQUU7QUFDZixJQUFJLE1BQU0sT0FBTyxHQUFHLE1BQU0sR0FBRyxDQUFDLElBQUksRUFBRTtBQUNwQyxJQUFJLE9BQU8sSUFBSSxDQUFDLEtBQUssQ0FBQyxHQUFHLENBQUMsTUFBTSxFQUFFLE9BQU8sQ0FBQyxDQUFDO0FBQzNDLEdBQUc7QUFDSCxFQUFFLE1BQU0sSUFBSSxHQUFHLE1BQU0sR0FBRyxDQUFDLElBQUksRUFBRTtBQUMvQixFQUFFLE9BQU87QUFDVCxJQUFJLFNBQVMsRUFBRSxJQUFJLENBQUMsU0FBUztBQUM3QixJQUFJLEtBQUssRUFBRSwyQ0FBSSxDQUFDLEtBQUssQ0FBQyxJQUFJLENBQUMsSUFBSSxDQUFDLEtBQUssQ0FBQztBQUN0QyxHQUFHO0FBQ0gsQ0FBQzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztZQW5HNEIsT0FBTyxLQUFLLENBQUM7OztpQkFJckMsYUFBYSxLQUFDLE9BQU8sQ0FBQzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3FCQUhXLFdBQVc7Ozs7Ozs7Ozs7MENBQVgsV0FBVzs7T0FHNUMsYUFBYSxLQUFDLE9BQU8sQ0FBQzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Z0NBTzhDLE1BQU0sQ0FBQyxLQUFLLENBQUMsUUFBUTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs2Q0FBMUMsTUFBTSxDQUFDLElBQUk7Ozs7Ozs7Ozs7Ozs7OzJEQUFVLE1BQU0sQ0FBQyxLQUFLLENBQUMsUUFBUTs7OzsrRUFBMUMsTUFBTSxDQUFDLElBQUk7Ozs7Ozs7Ozs7Ozs7Ozs7O3NCQURoRCxPQUFPLENBQUMsSUFBSTs7OztnQ0FBakI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3FCQUFLLE9BQU8sQ0FBQyxJQUFJOzttQ0FBakI7Ozs7Ozs7Ozs7Ozs7OztvQ0FBQTs7Ozs7Ozs7Ozs7Ozs7OztnQ0FXd0YsTUFBTSxDQUFDLEtBQUssQ0FBQyxRQUFROzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzBDQUF0RSxNQUFNLENBQUMsSUFBSSxDQUFDLE1BQU0sYUFBRyxNQUFNLENBQUMsSUFBSSxDQUFDLE1BQU07Ozs7Ozs7Ozs7Ozs7OzJEQUFVLE1BQU0sQ0FBQyxLQUFLLENBQUMsUUFBUTs7Ozs0RUFBdEUsTUFBTSxDQUFDLElBQUksQ0FBQyxNQUFNLGFBQUcsTUFBTSxDQUFDLElBQUksQ0FBQyxNQUFNOzs7Ozs7Ozs7Ozs7Ozs7Ozt3QkFEekUsT0FBTyxDQUFDLElBQUk7Ozs7a0NBQWpCOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt1QkFBSyxPQUFPLENBQUMsSUFBSTs7cUNBQWpCOzs7Ozs7Ozs7Ozs7Ozs7c0NBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Z0NBV21FLE1BQU0sQ0FBQyxLQUFLLENBQUMsUUFBUTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztpREFBMUMsTUFBTSxDQUFDLElBQUk7Ozs7Ozs7Ozs7Ozs7OzJEQUFVLE1BQU0sQ0FBQyxLQUFLLENBQUMsUUFBUTs7OzttRkFBMUMsTUFBTSxDQUFDLElBQUk7Ozs7Ozs7Ozs7Ozs7Ozs7O3dCQURwRCxPQUFPLENBQUMsV0FBVzs7OztrQ0FBeEI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3VCQUFLLE9BQU8sQ0FBQyxXQUFXOztxQ0FBeEI7Ozs7Ozs7Ozs7Ozs7OztzQ0FBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7O3FCQXhCRCxPQUFPLENBQUMsSUFBSSxRQUFJLE9BQU8sQ0FBQyxJQUFJLENBQUMsTUFBTTs7dUJBVW5DLE9BQU8sQ0FBQyxJQUFJLFFBQUksT0FBTyxDQUFDLElBQUksQ0FBQyxNQUFNOzt1QkFVbkMsT0FBTyxDQUFDLFdBQVcsUUFBSSxPQUFPLENBQUMsV0FBVyxDQUFDLE1BQU07Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztXQXBCakQsT0FBTyxDQUFDLElBQUksUUFBSSxPQUFPLENBQUMsSUFBSSxDQUFDLE1BQU07Ozs7Ozs7Ozs7Ozs7V0FVbkMsT0FBTyxDQUFDLElBQUksUUFBSSxPQUFPLENBQUMsSUFBSSxDQUFDLE1BQU07Ozs7Ozs7Ozs7Ozs7V0FVbkMsT0FBTyxDQUFDLFdBQVcsUUFBSSxPQUFPLENBQUMsV0FBVyxDQUFDLE1BQU07Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O21NQXJCWixDQUFDLENBQUMsQ0FBQyxFQUFFLENBQUM7Ozs7Ozs7Ozs7aU1BQU4sQ0FBQyxDQUFDLENBQUMsRUFBRSxDQUFDIiwiZmlsZSI6IjgxYmRjMzU0MDQwZjI0OTQxYjNkL3NlYXJjaC5zZWFyY2guanMiLCJzb3VyY2VzQ29udGVudCI6WyI8ZGl2IGNsYXNzPVwiYzEyIHoyXCI+XG4gIDxoMSBjbGFzcz1cImNvMiBjOCBzbS1jbzQgc20tYzRcIj57QGh0bWwgdGl0bGV9PC9oMT5cbjwvZGl2PlxuXG48c3R5bGU+XG4gIGgxIHtcbiAgICBmb250LXNpemU6IDNyZW07XG4gICAgbGluZS1oZWlnaHQ6IDAuOTtcbiAgICBmb250LXdlaWdodDogNDAwO1xuICAgIG1hcmdpbi1ib3R0b206IDNyZW07XG4gIH1cbiAgQG1lZGlhIChtaW4td2lkdGg6IDc2OHB4KSB7XG4gICAgaDEge1xuICAgICAgZm9udC1zaXplOiA0cmVtO1xuICAgIH1cbiAgfVxuPC9zdHlsZT4iLCI8c3ZlbHRlOmhlYWQ+XG4gIDx0aXRsZT5TZWFyY2g8L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cblxuPFRpdGxlIHRpdGxlPVwiU2VhcmNoXCIvPlxuPGRpdiBjbGFzcz1cInhcIj5cbiAgPGRpdiBjbGFzcz1cImRuIHNtLWRiIGMyIHAxXCI+XG4gICAgPHVsPlxuICAgICAgPGxpPjxhIHJlbD1cInByZWZldGNoXCIgaHJlZj1cIi9hYm91dFwiPkFib3V0PC9hPjwvbGk+XG4gICAgICA8bGk+PGEgcmVsPVwicHJlZmV0Y2hcIiBocmVmPVwiL3N1cHBvcnRcIj5TdXBwb3J0PC9hPjwvbGk+XG4gICAgICA8bGk+PGEgcmVsPVwicHJlZmV0Y2hcIiBocmVmPVwiL3NlYXJjaFwiPlNlYXJjaDwvYT48L2xpPlxuICAgIDwvdWw+XG4gIDwvZGl2PlxuICA8ZGl2IGNsYXNzPVwiYzEyIHNtLWMxMCBwMVwiPlxuICAgIDxmb3JtIGNsYXNzPVwibWIzXCIgb246c3VibWl0PVwic2VhcmNoKGV2ZW50KVwiPlxuICAgICAgPGlucHV0IGNsYXNzPVwiYzEwIHNtLWM4XCIgYmluZDp2YWx1ZT1zZWFyY2hRdWVyeSB0eXBlPXRleHQ+XG4gICAgICA8YnV0dG9uIHR5cGU9c3VibWl0PuKGkjwvYnV0dG9uPlxuICAgIDwvZm9ybT5cbiAgICB7I2lmIHJlc3VsdHNMZW5ndGgocmVzdWx0cyl9XG4gICAgICA8ZGl2IGNsYXNzPVwicmVzdWx0cyBjMTIgeHdcIiB0cmFuc2l0aW9uOmZseT0ne3k6MjB9Jz5cbiAgICAgICAgeyNpZiByZXN1bHRzLnBvc3QgJiYgcmVzdWx0cy5wb3N0Lmxlbmd0aH1cbiAgICAgICAgPGRpdiBjbGFzcz1cImMxMiBzbS1jNFwiPlxuICAgICAgICAgIDxoMT5BcnRpY2xlczwvaDE+XG4gICAgICAgICAgPHVsPlxuICAgICAgICAgICAgeyNlYWNoIHJlc3VsdHMucG9zdCBhcyByZXN1bHR9XG4gICAgICAgICAgICAgIDxsaT48aDE+PGEgcmVsPSdwcmVmZXRjaCcgaHJlZj0nYXJ0aWNsZXMve3Jlc3VsdC5zbHVnfSc+e0BodG1sIHJlc3VsdC50aXRsZS5yZW5kZXJlZCB9PC9hPjwvaDE+PC9saT5cbiAgICAgICAgICAgIHsvZWFjaH1cbiAgICAgICAgICA8L3VsPlxuICAgICAgICA8L2Rpdj5cbiAgICAgICAgey9pZn1cbiAgICAgICAgeyNpZiByZXN1bHRzLmZvbGQgJiYgcmVzdWx0cy5mb2xkLmxlbmd0aH1cbiAgICAgICAgPGRpdiBjbGFzcz1cImMxMiBzbS1jNFwiPlxuICAgICAgICAgIDxoMT5Gb2xkczwvaDE+XG4gICAgICAgICAgPHVsPlxuICAgICAgICAgICAgeyNlYWNoIHJlc3VsdHMuZm9sZCBhcyByZXN1bHR9XG4gICAgICAgICAgICAgIDxsaT48aDE+PGEgcmVsPSdwcmVmZXRjaCcgaHJlZj0nZm9sZHMve3Jlc3VsdC5tZXRhLnZvbHVtZX0te3Jlc3VsdC5tZXRhLm51bWJlcn0nPntAaHRtbCByZXN1bHQudGl0bGUucmVuZGVyZWQgfTwvYT48L2gxPjwvbGk+XG4gICAgICAgICAgICB7L2VhY2h9XG4gICAgICAgICAgPC91bD5cbiAgICAgICAgPC9kaXY+XG4gICAgICAgIHsvaWZ9XG4gICAgICAgIHsjaWYgcmVzdWx0cy5jb250cmlidXRvciAmJiByZXN1bHRzLmNvbnRyaWJ1dG9yLmxlbmd0aH1cbiAgICAgICAgPGRpdiBjbGFzcz1cImMxMiBzbS1jNFwiPlxuICAgICAgICAgIDxoMT5Db250cmlidXRvcnM8L2gxPlxuICAgICAgICAgIDx1bD5cbiAgICAgICAgICAgIHsjZWFjaCByZXN1bHRzLmNvbnRyaWJ1dG9yIGFzIHJlc3VsdH1cbiAgICAgICAgICAgICAgPGxpPjxoMT48YSByZWw9J3ByZWZldGNoJyBocmVmPSdjb250cmlidXRvcnMve3Jlc3VsdC5zbHVnfSc+e0BodG1sIHJlc3VsdC50aXRsZS5yZW5kZXJlZCB9PC9hPjwvaDE+PC9saT5cbiAgICAgICAgICAgIHsvZWFjaH1cbiAgICAgICAgICA8L3VsPlxuICAgICAgICA8L2Rpdj5cbiAgICAgICAgey9pZn1cbiAgICAgIDwvZGl2PlxuICAgIHsvaWZ9XG4gIDwvZGl2PlxuPC9kaXY+XG5cbjxzdHlsZT5cbiAgaW5wdXQge1xuICAgIGJvcmRlci1ib3R0b206IDAuMnJlbSBzb2xpZCBibGFjaztcbiAgICBmb250LXNpemU6IDRyZW07XG4gICAgbGluZS1oZWlnaHQ6IDAuOTtcbiAgICBmb250LXdlaWdodDogNDAwO1xuICAgIG1hcmdpbi1yaWdodDogMXJlbTtcbiAgfVxuPC9zdHlsZT5cblxuPHNjcmlwdD5cbiAgaW1wb3J0IGx1bnIgZnJvbSAnbHVucidcbiAgaW1wb3J0IGZseSBmcm9tICdzdmVsdGUtdHJhbnNpdGlvbnMtZmx5JztcblxuICBleHBvcnQgZGVmYXVsdCB7XG4gICAgaGVscGVyczoge1xuICAgICAgcmVzdWx0c0xlbmd0aDogKHJlc3VsdHMpID0+IHtcbiAgICAgICAgaWYgKCFyZXN1bHRzKSByZXR1cm4gZmFsc2VcbiAgICAgICAgbGV0IG91dCA9IChyZXN1bHRzLnBvc3QgJiYgcmVzdWx0cy5wb3N0Lmxlbmd0aCkgfHxcbiAgICAgICAgICAocmVzdWx0cy5mb2xkICYmIHJlc3VsdHMuZm9sZC5sZW5ndGgpIHx8XG4gICAgICAgICAgKHJlc3VsdHMuY29udHJpYnV0b3IgJiYgcmVzdWx0cy5jb250cmlidXRvci5sZW5ndGgpXG4gICAgICAgIHJldHVybiBvdXRcbiAgICAgIH1cbiAgICB9LFxuICAgIGNvbXBvbmVudHM6IHtcbiAgICAgIFRpdGxlOiAnLi4vLi4vY29tcG9uZW50cy9UaXRsZS5odG1sJ1xuICAgIH0sXG4gICAgbWV0aG9kczoge1xuICAgICAgc2VhcmNoKGUpIHtcbiAgICAgICAgZS5wcmV2ZW50RGVmYXVsdCgpO1xuICAgICAgICBjb25zdCB7IHNlYXJjaFF1ZXJ5LCBpbmRleCB9ID0gdGhpcy5nZXQoKTtcbiAgICAgICAgbGV0IHRva2VucyA9IHNlYXJjaFF1ZXJ5LnNwbGl0KCcgJylcbiAgICAgICAgaWYgKHRva2Vuc1swXSkgdG9rZW5zID0gdG9rZW5zLm1hcCh0b2tlbiA9PiB0b2tlbiArICd+MScpXG4gICAgICAgIGNvbnN0IGx1bnJSZXN1bHRzID0gaW5kZXguc2VhcmNoKHRva2Vucy5qb2luKCcgJykpXG4gICAgICAgIHRoaXMuc2V0KHtcbiAgICAgICAgICBsdW5yUmVzdWx0c1xuICAgICAgICB9KVxuICAgICAgfVxuICAgIH0sXG4gICAgdHJhbnNpdGlvbnM6IHsgZmx5IH0sXG4gICAgZGF0YSgpIHtcbiAgICAgIHJldHVybiB7XG4gICAgICAgIGx1bnJSZXN1bHRzOiBbXSxcbiAgICAgICAgc2VhcmNoUXVlcnk6ICcnXG4gICAgICB9XG4gICAgfSxcbiAgICBhc3luYyBwcmVsb2FkKHsgcGFyYW1zLCBxdWVyeSB9KSB7XG4gICAgICBjb25zdCBtYXNrRmllbGRzID0gJ3Jlc291cmNlcyhpZCx0aXRsZS9yZW5kZXJlZCxzbHVnLHR5cGUsbWV0YSh2b2x1bWUsbnVtYmVyKSksaW5kZXgnXG4gICAgICBjb25zdCByZXMgPSBhd2FpdCB0aGlzLmZldGNoKGBzZWFyY2guanNvbj9maWVsZHM9JHttYXNrRmllbGRzfWApXG4gICAgICBpZiAoIXJlcy5vaykge1xuICAgICAgICBjb25zdCBtZXNzYWdlID0gYXdhaXQgcmVzLnRleHQoKVxuICAgICAgICByZXR1cm4gdGhpcy5lcnJvcihyZXMuc3RhdHVzLCBtZXNzYWdlKTtcbiAgICAgIH1cbiAgICAgIGNvbnN0IGRhdGEgPSBhd2FpdCByZXMuanNvbigpXG4gICAgICByZXR1cm4ge1xuICAgICAgICByZXNvdXJjZXM6IGRhdGEucmVzb3VyY2VzLFxuICAgICAgICBpbmRleDogbHVuci5JbmRleC5sb2FkKGRhdGEuaW5kZXgpXG4gICAgICB9XG4gICAgfSxcbiAgICBjb21wdXRlZDoge1xuICAgICAgcmVzdWx0czogKHsgbHVuclJlc3VsdHMsIHJlc291cmNlcyB9KSA9PiB7XG4gICAgICAgIHJlc291cmNlcyA9IGx1bnJSZXN1bHRzLm1hcChyZXN1bHQgPT4ge1xuICAgICAgICAgIGNvbnN0IHJlc291cmNlID0gcmVzb3VyY2VzLmZpbHRlcihyZXNvdXJjZSA9PiB7XG4gICAgICAgICAgICByZXR1cm4gcmVzb3VyY2UuaWQgPT0gcmVzdWx0LnJlZlxuICAgICAgICAgIH0pWzBdXG4gICAgICAgICAgcmV0dXJuIHJlc291cmNlXG4gICAgICAgIH0pXG4gICAgICAgIGxldCBvdXQgPSB7fVxuICAgICAgICBmb3IgKGxldCByZXNvdXJjZSBvZiByZXNvdXJjZXMpIHtcbiAgICAgICAgICBpZiAoIW91dFtyZXNvdXJjZS50eXBlXSkgb3V0W3Jlc291cmNlLnR5cGVdID0gW11cbiAgICAgICAgICBvdXRbcmVzb3VyY2UudHlwZV0ucHVzaChyZXNvdXJjZSlcbiAgICAgICAgfVxuICAgICAgICByZXR1cm4gb3V0XG4gICAgICB9XG4gICAgfVxuICB9O1xuPC9zY3JpcHQ+Il0sInNvdXJjZVJvb3QiOiIifQ==