(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["support"],{

/***/ "./components/Title.html":
/*!*******************************!*\
  !*** ./components/Title.html ***!
  \*******************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/shared.js */ "./node_modules/svelte/shared.js");
/* components/Title.html generated by Svelte v2.9.9 */


const file = "components/Title.html";

function add_css() {
	var style = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("style");
	style.id = 'svelte-quv5ds-style';
	style.textContent = "h1.svelte-quv5ds{font-size:3rem;line-height:0.9;font-weight:400;margin-bottom:3rem}@media(min-width: 768px){h1.svelte-quv5ds{font-size:4rem}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiVGl0bGUuaHRtbCIsInNvdXJjZXMiOlsiVGl0bGUuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyI8ZGl2IGNsYXNzPVwiYzEyIHoyXCI+XG4gIDxoMSBjbGFzcz1cImNvMiBjOCBzbS1jbzQgc20tYzRcIj57QGh0bWwgdGl0bGV9PC9oMT5cbjwvZGl2PlxuXG48c3R5bGU+XG4gIGgxIHtcbiAgICBmb250LXNpemU6IDNyZW07XG4gICAgbGluZS1oZWlnaHQ6IDAuOTtcbiAgICBmb250LXdlaWdodDogNDAwO1xuICAgIG1hcmdpbi1ib3R0b206IDNyZW07XG4gIH1cbiAgQG1lZGlhIChtaW4td2lkdGg6IDc2OHB4KSB7XG4gICAgaDEge1xuICAgICAgZm9udC1zaXplOiA0cmVtO1xuICAgIH1cbiAgfVxuPC9zdHlsZT4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBS0UsRUFBRSxjQUFDLENBQUMsQUFDRixTQUFTLENBQUUsSUFBSSxDQUNmLFdBQVcsQ0FBRSxHQUFHLENBQ2hCLFdBQVcsQ0FBRSxHQUFHLENBQ2hCLGFBQWEsQ0FBRSxJQUFJLEFBQ3JCLENBQUMsQUFDRCxNQUFNLEFBQUMsWUFBWSxLQUFLLENBQUMsQUFBQyxDQUFDLEFBQ3pCLEVBQUUsY0FBQyxDQUFDLEFBQ0YsU0FBUyxDQUFFLElBQUksQUFDakIsQ0FBQyxBQUNILENBQUMifQ== */";
	Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(style, document.head);
}

function create_main_fragment(component, ctx) {
	var div, h1;

	return {
		c: function create() {
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			h1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h1");
			this.h()
		},

		l: function claim(nodes) {
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			h1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "H1", { class: true }, false);
			var h1_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);

			h1_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			div_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			h1.className = "co2 c8 sm-co4 sm-c4 svelte-quv5ds";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(h1, file, 1, 2, 23);
			div.className = "c12 z2";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div, file, 0, 0, 0);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(div, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(h1, div);
			h1.innerHTML = ctx.title;
		},

		p: function update(changed, ctx) {
			if (changed.title) {
				h1.innerHTML = ctx.title;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(div);
			}
		}
	};
}

function Title(options) {
	this._debugName = '<Title>';
	if (!options || (!options.target && !options.root)) throw new Error("'target' is a required option");
	Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options);
	this._state = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])({}, options.data);
	if (!('title' in this._state)) console.warn("<Title> was created without expected data property 'title'");
	this._intro = true;

	if (!document.getElementById("svelte-quv5ds-style")) add_css();

	this._fragment = create_main_fragment(this, this._state);

	if (options.target) {
		var nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(options.target);
		options.hydrate ? this._fragment.l(nodes) : this._fragment.c();
		nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
		this._mount(options.target, options.anchor);
	}
}

Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])(Title.prototype, svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["protoDev"]);

Title.prototype._checkReadOnly = function _checkReadOnly(newState) {
};

if (true) {
	const { configure, register, reload } = __webpack_require__(/*! ./node_modules/svelte-loader/lib/hot-api.js */ "./node_modules/svelte-loader/lib/hot-api.js");

	module.hot.accept();

	if (!module.hot.data) {
		// initial load
		configure({});
		Title = register("components/Title.html", Title);
	} else {
		// hot update
		Title = reload("components/Title.html", Title);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Title);


/***/ }),

/***/ "./src/routes/support.html":
/*!*********************************!*\
  !*** ./src/routes/support.html ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/shared.js */ "./node_modules/svelte/shared.js");
/* harmony import */ var _components_Title_html__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../../components/Title.html */ "./components/Title.html");
/* src/routes/support.html generated by Svelte v2.9.9 */



async function preload({ params, query }) {
  const maskFields = 'content/rendered'
  const res = await this.fetch(`/support.json?fields=${maskFields}`)
  if (!res.ok) {
    const message = await res.text()
    return this.error(res.status, message);
  }
  const data = await res.json()
  return { page: data }
};

const file = "src/routes/support.html";

function add_css() {
	var style = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("style");
	style.id = 'svelte-4vur6y-style';
	style.textContent = "input[type=email].svelte-4vur6y{color:black;border-bottom:0.2rem solid black;font-size:2rem;line-height:0.9;font-weight:400;margin-right:1rem}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic3VwcG9ydC5odG1sIiwic291cmNlcyI6WyJzdXBwb3J0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiPHN2ZWx0ZTpoZWFkPlxuICA8dGl0bGU+U3VwcG9ydDwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuXG48VGl0bGUgdGl0bGU9XCJTdXBwb3J0XCIvPlxuPGRpdiBjbGFzcz1cInhcIj5cbiAgPGRpdiBjbGFzcz1cImRuIHNtLWRiIGMyIHAxXCI+XG4gICAgPHVsPlxuICAgICAgPGxpPjxhIHJlbD1cInByZWZldGNoXCIgaHJlZj1cIi9hYm91dFwiPkFib3V0PC9hPjwvbGk+XG4gICAgICA8bGk+PGEgcmVsPVwicHJlZmV0Y2hcIiBocmVmPVwiL3N1cHBvcnRcIj5TdXBwb3J0PC9hPjwvbGk+XG4gICAgICA8bGk+PGEgcmVsPVwicHJlZmV0Y2hcIiBocmVmPVwiL3NlYXJjaFwiPlNlYXJjaDwvYT48L2xpPlxuICAgIDwvdWw+XG4gIDwvZGl2PlxuICA8ZGl2IGNsYXNzPVwiYzEyIHNtLWM0IHAxXCI+XG4gICAge0BodG1sIHBhZ2UuY29udGVudC5yZW5kZXJlZH1cbiAgPC9kaXY+XG4gIDwhLS0gQmVnaW4gTWFpbGNoaW1wIFNpZ251cCBGb3JtIC0tPlxuICA8ZGl2IGNsYXNzPVwiYzEyIHNtLWM0IHAxXCIgaWQ9XCJtY19lbWJlZF9zaWdudXBcIj5cbiAgICA8Zm9ybSBhY3Rpb249XCJodHRwczovL3lhbGVwYXByaWthLnVzMS5saXN0LW1hbmFnZS5jb20vc3Vic2NyaWJlL3Bvc3Q/dT00Y2E5NjZhMTMyZDExMGNkM2Y0NGE1ZDQ3JmFtcDtpZD01MjgxYWEyNjg1XCIgbWV0aG9kPVwicG9zdFwiIGlkPVwibWMtZW1iZWRkZWQtc3Vic2NyaWJlLWZvcm1cIiBuYW1lPVwibWMtZW1iZWRkZWQtc3Vic2NyaWJlLWZvcm1cIiBjbGFzcz1cInZhbGlkYXRlXCIgdGFyZ2V0PVwiX2JsYW5rXCIgbm92YWxpZGF0ZT5cbiAgICAgICAgPGRpdiBpZD1cIm1jX2VtYmVkX3NpZ251cF9zY3JvbGxcIj5cbiAgICAgIDxsYWJlbCBmb3I9XCJtY2UtRU1BSUxcIj5TdWJzY3JpYmUgdG8gcmVjZWl2ZSBuZXcgUGFwcmlrYSEgaXNzdWVzIGJ5IGVtYWlsPC9sYWJlbD5cbiAgICAgIDxpbnB1dCB0eXBlPVwiZW1haWxcIiB2YWx1ZT1cIlwiIG5hbWU9XCJFTUFJTFwiIGNsYXNzPVwiZW1haWxcIiBpZD1cIm1jZS1FTUFJTFwiIHJlcXVpcmVkPlxuICAgICAgICA8IS0tIHJlYWwgcGVvcGxlIHNob3VsZCBub3QgZmlsbCB0aGlzIGluIGFuZCBleHBlY3QgZ29vZCB0aGluZ3MgLSBkbyBub3QgcmVtb3ZlIHRoaXMgb3IgcmlzayBmb3JtIGJvdCBzaWdudXBzLS0+XG4gICAgICAgIDxkaXYgc3R5bGU9XCJwb3NpdGlvbjogYWJzb2x1dGU7IGxlZnQ6IC01MDAwcHg7XCIgYXJpYS1oaWRkZW49XCJ0cnVlXCI+PGlucHV0IHR5cGU9XCJ0ZXh0XCIgbmFtZT1cImJfNGNhOTY2YTEzMmQxMTBjZDNmNDRhNWQ0N181MjgxYWEyNjg1XCIgdGFiaW5kZXg9XCItMVwiIHZhbHVlPVwiXCI+PC9kaXY+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJjbGVhclwiPjxpbnB1dCB0eXBlPVwic3VibWl0XCIgdmFsdWU9XCJTdWJzY3JpYmVcIiBuYW1lPVwic3Vic2NyaWJlXCIgaWQ9XCJtYy1lbWJlZGRlZC1zdWJzY3JpYmVcIiBjbGFzcz1cImJ1dHRvblwiPjwvZGl2PlxuICAgICAgICA8L2Rpdj5cbiAgICA8L2Zvcm0+XG4gIDwvZGl2PlxuXG4gIDwhLS1FbmQgbWNfZW1iZWRfc2lnbnVwLS0+XG48L2Rpdj5cblxuPHN0eWxlPlxuICBpbnB1dFt0eXBlPWVtYWlsXSB7XG4gICAgY29sb3I6IGJsYWNrO1xuICAgIGJvcmRlci1ib3R0b206IDAuMnJlbSBzb2xpZCBibGFjaztcbiAgICBmb250LXNpemU6IDJyZW07XG4gICAgbGluZS1oZWlnaHQ6IDAuOTtcbiAgICBmb250LXdlaWdodDogNDAwO1xuICAgIG1hcmdpbi1yaWdodDogMXJlbTtcbiAgfVxuPC9zdHlsZT5cblxuPHNjcmlwdD5cbiAgZXhwb3J0IGRlZmF1bHQge1xuICAgIGNvbXBvbmVudHM6IHtcbiAgICAgIFRpdGxlOiAnLi4vLi4vY29tcG9uZW50cy9UaXRsZS5odG1sJ1xuICAgIH0sXG4gICAgYXN5bmMgcHJlbG9hZCh7IHBhcmFtcywgcXVlcnkgfSkge1xuICAgICAgY29uc3QgbWFza0ZpZWxkcyA9ICdjb250ZW50L3JlbmRlcmVkJ1xuICAgICAgY29uc3QgcmVzID0gYXdhaXQgdGhpcy5mZXRjaChgL3N1cHBvcnQuanNvbj9maWVsZHM9JHttYXNrRmllbGRzfWApXG4gICAgICBpZiAoIXJlcy5vaykge1xuICAgICAgICBjb25zdCBtZXNzYWdlID0gYXdhaXQgcmVzLnRleHQoKVxuICAgICAgICByZXR1cm4gdGhpcy5lcnJvcihyZXMuc3RhdHVzLCBtZXNzYWdlKTtcbiAgICAgIH1cbiAgICAgIGNvbnN0IGRhdGEgPSBhd2FpdCByZXMuanNvbigpXG4gICAgICByZXR1cm4geyBwYWdlOiBkYXRhIH1cbiAgICB9XG4gIH07XG48L3NjcmlwdD4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBaUNFLEtBQUssQ0FBQyxJQUFJLENBQUMsS0FBSyxDQUFDLGNBQUMsQ0FBQyxBQUNqQixLQUFLLENBQUUsS0FBSyxDQUNaLGFBQWEsQ0FBRSxNQUFNLENBQUMsS0FBSyxDQUFDLEtBQUssQ0FDakMsU0FBUyxDQUFFLElBQUksQ0FDZixXQUFXLENBQUUsR0FBRyxDQUNoQixXQUFXLENBQUUsR0FBRyxDQUNoQixZQUFZLENBQUUsSUFBSSxBQUNwQixDQUFDIn0= */";
	Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(style, document.head);
}

function create_main_fragment(component, ctx) {
	var text, text_1, div, div_1, ul, li, a, text_2, li_1, a_1, text_3, li_2, a_2, text_4, text_6, div_2, raw_value = ctx.page.content.rendered, text_8, div_3, form, div_4, label, text_9, text_10, input, text_11, div_5, input_1, text_12, div_6, input_2;

	var title_initial_data = { title: "Support" };
	var title = new _components_Title_html__WEBPACK_IMPORTED_MODULE_1__["default"]({
		root: component.root,
		store: component.store,
		data: title_initial_data
	});

	return {
		c: function create() {
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n\n");
			title._fragment.c();
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n");
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			div_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("ul");
			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("li");
			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("a");
			text_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("About");
			li_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("li");
			a_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("a");
			text_3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("Support");
			li_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("li");
			a_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("a");
			text_4 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("Search");
			text_6 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n  ");
			div_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			text_8 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n  \n  ");
			div_3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			form = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("form");
			div_4 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			label = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("label");
			text_9 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("Subscribe to receive new Paprika! issues by email");
			text_10 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n      ");
			input = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("input");
			text_11 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n        \n        ");
			div_5 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			input_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("input");
			text_12 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n        ");
			div_6 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			input_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("input");
			this.h()
		},

		l: function claim(nodes) {
			text = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(nodes, "\n\n");
			title._fragment.l(nodes);
			text_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(nodes, "\n");

			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			div_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "DIV", { class: true }, false);
			var div_1_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div_1);

			ul = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_1_nodes, "UL", {}, false);
			var ul_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			li = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(ul_nodes, "LI", {}, false);
			var li_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(li);

			a = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(li_nodes, "A", { rel: true, href: true }, false);
			var a_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			text_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(a_nodes, "About");
			a_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			li_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);

			li_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(ul_nodes, "LI", {}, false);
			var li_1_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(li_1);

			a_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(li_1_nodes, "A", { rel: true, href: true }, false);
			var a_1_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(a_1);

			text_3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(a_1_nodes, "Support");
			a_1_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			li_1_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);

			li_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(ul_nodes, "LI", {}, false);
			var li_2_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(li_2);

			a_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(li_2_nodes, "A", { rel: true, href: true }, false);
			var a_2_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(a_2);

			text_4 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(a_2_nodes, "Search");
			a_2_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			li_2_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			ul_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			div_1_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_6 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_nodes, "\n  ");

			div_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "DIV", { class: true }, false);
			var div_2_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div_2);

			div_2_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_8 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_nodes, "\n  \n  ");

			div_3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "DIV", { class: true, id: true }, false);
			var div_3_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div_3);

			form = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_3_nodes, "FORM", { action: true, method: true, id: true, name: true, class: true, target: true, novalidate: true }, false);
			var form_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(form);

			div_4 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(form_nodes, "DIV", { id: true }, false);
			var div_4_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div_4);

			label = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_4_nodes, "LABEL", { for: true }, false);
			var label_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(label);

			text_9 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(label_nodes, "Subscribe to receive new Paprika! issues by email");
			label_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_10 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_4_nodes, "\n      ");

			input = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_4_nodes, "INPUT", { type: true, value: true, name: true, class: true, id: true, required: true }, false);
			var input_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(input);

			input_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_11 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_4_nodes, "\n        \n        ");

			div_5 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_4_nodes, "DIV", { style: true, "aria-hidden": true }, false);
			var div_5_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div_5);

			input_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_5_nodes, "INPUT", { type: true, name: true, tabindex: true, value: true }, false);
			var input_1_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(input_1);

			input_1_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			div_5_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_12 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_4_nodes, "\n        ");

			div_6 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_4_nodes, "DIV", { class: true }, false);
			var div_6_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div_6);

			input_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_6_nodes, "INPUT", { type: true, value: true, name: true, id: true, class: true }, false);
			var input_2_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(input_2);

			input_2_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			div_6_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			div_4_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			form_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			div_3_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			div_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			document.title = "Support";
			a.rel = "prefetch";
			a.href = "/about";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(a, file, 8, 10, 146);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(li, file, 8, 6, 142);
			a_1.rel = "prefetch";
			a_1.href = "/support";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(a_1, file, 9, 10, 203);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(li_1, file, 9, 6, 199);
			a_2.rel = "prefetch";
			a_2.href = "/search";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(a_2, file, 10, 10, 264);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(li_2, file, 10, 6, 260);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(ul, file, 7, 4, 131);
			div_1.className = "dn sm-db c2 p1";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div_1, file, 6, 2, 98);
			div_2.className = "c12 sm-c4 p1";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div_2, file, 13, 2, 334);
			label.htmlFor = "mce-EMAIL";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(label, file, 20, 6, 786);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["setAttribute"])(input, "type", "email");
			input.value = "";
			input.name = "EMAIL";
			input.className = "email svelte-4vur6y";
			input.id = "mce-EMAIL";
			input.required = true;
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(input, file, 21, 6, 873);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["setAttribute"])(input_1, "type", "text");
			input_1.name = "b_4ca966a132d110cd3f44a5d47_5281aa2685";
			input_1.tabIndex = "-1";
			input_1.value = "";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(input_1, file, 23, 75, 1150);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["setStyle"])(div_5, "position", "absolute");
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["setStyle"])(div_5, "left", "-5000px");
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["setAttribute"])(div_5, "aria-hidden", "true");
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div_5, file, 23, 8, 1083);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["setAttribute"])(input_2, "type", "submit");
			input_2.value = "Subscribe";
			input_2.name = "subscribe";
			input_2.id = "mc-embedded-subscribe";
			input_2.className = "button";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(input_2, file, 24, 27, 1272);
			div_6.className = "clear";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div_6, file, 24, 8, 1253);
			div_4.id = "mc_embed_signup_scroll";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div_4, file, 19, 8, 746);
			form.action = "https://yalepaprika.us1.list-manage.com/subscribe/post?u=4ca966a132d110cd3f44a5d47&id=5281aa2685";
			form.method = "post";
			form.id = "mc-embedded-subscribe-form";
			form.name = "mc-embedded-subscribe-form";
			form.className = "validate";
			form.target = "_blank";
			form.noValidate = true;
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(form, file, 18, 4, 497);
			div_3.className = "c12 sm-c4 p1";
			div_3.id = "mc_embed_signup";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div_3, file, 17, 2, 445);
			div.className = "x";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div, file, 5, 0, 80);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(text, target, anchor);
			title._mount(target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(text_1, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(div, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(div_1, div);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(ul, div_1);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(li, ul);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(a, li);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_2, a);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(li_1, ul);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(a_1, li_1);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_3, a_1);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(li_2, ul);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(a_2, li_2);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_4, a_2);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_6, div);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(div_2, div);
			div_2.innerHTML = raw_value;
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_8, div);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(div_3, div);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(form, div_3);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(div_4, form);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(label, div_4);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_9, label);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_10, div_4);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(input, div_4);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_11, div_4);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(div_5, div_4);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(input_1, div_5);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_12, div_4);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(div_6, div_4);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(input_2, div_6);
		},

		p: function update(changed, ctx) {
			if ((changed.page) && raw_value !== (raw_value = ctx.page.content.rendered)) {
				div_2.innerHTML = raw_value;
			}
		},

		d: function destroy(detach) {
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(text);
			}

			title.destroy(detach);
			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(text_1);
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(div);
			}
		}
	};
}

function Support(options) {
	this._debugName = '<Support>';
	if (!options || (!options.target && !options.root)) throw new Error("'target' is a required option");
	Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options);
	this._state = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])({}, options.data);
	if (!('page' in this._state)) console.warn("<Support> was created without expected data property 'page'");
	this._intro = true;

	if (!document.getElementById("svelte-4vur6y-style")) add_css();

	if (!options.root) {
		this._oncreate = [];
		this._beforecreate = [];
		this._aftercreate = [];
	}

	this._fragment = create_main_fragment(this, this._state);

	if (options.target) {
		var nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(options.target);
		options.hydrate ? this._fragment.l(nodes) : this._fragment.c();
		nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
		this._mount(options.target, options.anchor);

		this._lock = true;
		Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["callAll"])(this._beforecreate);
		Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["callAll"])(this._oncreate);
		Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["callAll"])(this._aftercreate);
		this._lock = false;
	}
}

Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])(Support.prototype, svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["protoDev"]);

Support.prototype._checkReadOnly = function _checkReadOnly(newState) {
};

Support.preload = preload;

if (true) {
	const { configure, register, reload } = __webpack_require__(/*! ./node_modules/svelte-loader/lib/hot-api.js */ "./node_modules/svelte-loader/lib/hot-api.js");

	module.hot.accept();

	if (!module.hot.data) {
		// initial load
		configure({});
		Support = register("src/routes/support.html", Support);
	} else {
		// hot update
		Support = reload("src/routes/support.html", Support);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Support);


/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9jb21wb25lbnRzL1RpdGxlLmh0bWwiLCJ3ZWJwYWNrOi8vLy4vc3JjL3JvdXRlcy9zdXBwb3J0Lmh0bWwiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7c0JBQ3lDLEtBQUs7Ozs7O3VCQUFMLEtBQUs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztzQkMrQzdCLENBQUMsRUFBRSxNQUFNLEVBQUUsS0FBSyxFQUFFLEVBQUU7QUFDakMsRUFBRSxNQUFNLFVBQVUsR0FBRyxrQkFBa0I7QUFDdkMsRUFBRSxNQUFNLEdBQUcsR0FBRyxNQUFNLElBQUksQ0FBQyxLQUFLLENBQUMsQ0FBQyxxQkFBcUIsRUFBRSxVQUFVLENBQUMsQ0FBQyxDQUFDO0FBQ3BFLEVBQUUsSUFBSSxDQUFDLEdBQUcsQ0FBQyxFQUFFLEVBQUU7QUFDZixJQUFJLE1BQU0sT0FBTyxHQUFHLE1BQU0sR0FBRyxDQUFDLElBQUksRUFBRTtBQUNwQyxJQUFJLE9BQU8sSUFBSSxDQUFDLEtBQUssQ0FBQyxHQUFHLENBQUMsTUFBTSxFQUFFLE9BQU8sQ0FBQyxDQUFDO0FBQzNDLEdBQUc7QUFDSCxFQUFFLE1BQU0sSUFBSSxHQUFHLE1BQU0sR0FBRyxDQUFDLElBQUksRUFBRTtBQUMvQixFQUFFLE9BQU8sRUFBRSxJQUFJLEVBQUUsSUFBSSxFQUFFO0FBQ3ZCLENBQUM7Ozs7Ozs7Ozs7Ozt1SEEzQ00sSUFBSSxDQUFDLE9BQU8sQ0FBQyxRQUFROzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7d0RBQXJCLElBQUksQ0FBQyxPQUFPLENBQUMsUUFBUSIsImZpbGUiOiI4MWJkYzM1NDA0MGYyNDk0MWIzZC9zdXBwb3J0LnN1cHBvcnQuanMiLCJzb3VyY2VzQ29udGVudCI6WyI8ZGl2IGNsYXNzPVwiYzEyIHoyXCI+XG4gIDxoMSBjbGFzcz1cImNvMiBjOCBzbS1jbzQgc20tYzRcIj57QGh0bWwgdGl0bGV9PC9oMT5cbjwvZGl2PlxuXG48c3R5bGU+XG4gIGgxIHtcbiAgICBmb250LXNpemU6IDNyZW07XG4gICAgbGluZS1oZWlnaHQ6IDAuOTtcbiAgICBmb250LXdlaWdodDogNDAwO1xuICAgIG1hcmdpbi1ib3R0b206IDNyZW07XG4gIH1cbiAgQG1lZGlhIChtaW4td2lkdGg6IDc2OHB4KSB7XG4gICAgaDEge1xuICAgICAgZm9udC1zaXplOiA0cmVtO1xuICAgIH1cbiAgfVxuPC9zdHlsZT4iLCI8c3ZlbHRlOmhlYWQ+XG4gIDx0aXRsZT5TdXBwb3J0PC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG5cbjxUaXRsZSB0aXRsZT1cIlN1cHBvcnRcIi8+XG48ZGl2IGNsYXNzPVwieFwiPlxuICA8ZGl2IGNsYXNzPVwiZG4gc20tZGIgYzIgcDFcIj5cbiAgICA8dWw+XG4gICAgICA8bGk+PGEgcmVsPVwicHJlZmV0Y2hcIiBocmVmPVwiL2Fib3V0XCI+QWJvdXQ8L2E+PC9saT5cbiAgICAgIDxsaT48YSByZWw9XCJwcmVmZXRjaFwiIGhyZWY9XCIvc3VwcG9ydFwiPlN1cHBvcnQ8L2E+PC9saT5cbiAgICAgIDxsaT48YSByZWw9XCJwcmVmZXRjaFwiIGhyZWY9XCIvc2VhcmNoXCI+U2VhcmNoPC9hPjwvbGk+XG4gICAgPC91bD5cbiAgPC9kaXY+XG4gIDxkaXYgY2xhc3M9XCJjMTIgc20tYzQgcDFcIj5cbiAgICB7QGh0bWwgcGFnZS5jb250ZW50LnJlbmRlcmVkfVxuICA8L2Rpdj5cbiAgPCEtLSBCZWdpbiBNYWlsY2hpbXAgU2lnbnVwIEZvcm0gLS0+XG4gIDxkaXYgY2xhc3M9XCJjMTIgc20tYzQgcDFcIiBpZD1cIm1jX2VtYmVkX3NpZ251cFwiPlxuICAgIDxmb3JtIGFjdGlvbj1cImh0dHBzOi8veWFsZXBhcHJpa2EudXMxLmxpc3QtbWFuYWdlLmNvbS9zdWJzY3JpYmUvcG9zdD91PTRjYTk2NmExMzJkMTEwY2QzZjQ0YTVkNDcmYW1wO2lkPTUyODFhYTI2ODVcIiBtZXRob2Q9XCJwb3N0XCIgaWQ9XCJtYy1lbWJlZGRlZC1zdWJzY3JpYmUtZm9ybVwiIG5hbWU9XCJtYy1lbWJlZGRlZC1zdWJzY3JpYmUtZm9ybVwiIGNsYXNzPVwidmFsaWRhdGVcIiB0YXJnZXQ9XCJfYmxhbmtcIiBub3ZhbGlkYXRlPlxuICAgICAgICA8ZGl2IGlkPVwibWNfZW1iZWRfc2lnbnVwX3Njcm9sbFwiPlxuICAgICAgPGxhYmVsIGZvcj1cIm1jZS1FTUFJTFwiPlN1YnNjcmliZSB0byByZWNlaXZlIG5ldyBQYXByaWthISBpc3N1ZXMgYnkgZW1haWw8L2xhYmVsPlxuICAgICAgPGlucHV0IHR5cGU9XCJlbWFpbFwiIHZhbHVlPVwiXCIgbmFtZT1cIkVNQUlMXCIgY2xhc3M9XCJlbWFpbFwiIGlkPVwibWNlLUVNQUlMXCIgcmVxdWlyZWQ+XG4gICAgICAgIDwhLS0gcmVhbCBwZW9wbGUgc2hvdWxkIG5vdCBmaWxsIHRoaXMgaW4gYW5kIGV4cGVjdCBnb29kIHRoaW5ncyAtIGRvIG5vdCByZW1vdmUgdGhpcyBvciByaXNrIGZvcm0gYm90IHNpZ251cHMtLT5cbiAgICAgICAgPGRpdiBzdHlsZT1cInBvc2l0aW9uOiBhYnNvbHV0ZTsgbGVmdDogLTUwMDBweDtcIiBhcmlhLWhpZGRlbj1cInRydWVcIj48aW5wdXQgdHlwZT1cInRleHRcIiBuYW1lPVwiYl80Y2E5NjZhMTMyZDExMGNkM2Y0NGE1ZDQ3XzUyODFhYTI2ODVcIiB0YWJpbmRleD1cIi0xXCIgdmFsdWU9XCJcIj48L2Rpdj5cbiAgICAgICAgPGRpdiBjbGFzcz1cImNsZWFyXCI+PGlucHV0IHR5cGU9XCJzdWJtaXRcIiB2YWx1ZT1cIlN1YnNjcmliZVwiIG5hbWU9XCJzdWJzY3JpYmVcIiBpZD1cIm1jLWVtYmVkZGVkLXN1YnNjcmliZVwiIGNsYXNzPVwiYnV0dG9uXCI+PC9kaXY+XG4gICAgICAgIDwvZGl2PlxuICAgIDwvZm9ybT5cbiAgPC9kaXY+XG5cbiAgPCEtLUVuZCBtY19lbWJlZF9zaWdudXAtLT5cbjwvZGl2PlxuXG48c3R5bGU+XG4gIGlucHV0W3R5cGU9ZW1haWxdIHtcbiAgICBjb2xvcjogYmxhY2s7XG4gICAgYm9yZGVyLWJvdHRvbTogMC4ycmVtIHNvbGlkIGJsYWNrO1xuICAgIGZvbnQtc2l6ZTogMnJlbTtcbiAgICBsaW5lLWhlaWdodDogMC45O1xuICAgIGZvbnQtd2VpZ2h0OiA0MDA7XG4gICAgbWFyZ2luLXJpZ2h0OiAxcmVtO1xuICB9XG48L3N0eWxlPlxuXG48c2NyaXB0PlxuICBleHBvcnQgZGVmYXVsdCB7XG4gICAgY29tcG9uZW50czoge1xuICAgICAgVGl0bGU6ICcuLi8uLi9jb21wb25lbnRzL1RpdGxlLmh0bWwnXG4gICAgfSxcbiAgICBhc3luYyBwcmVsb2FkKHsgcGFyYW1zLCBxdWVyeSB9KSB7XG4gICAgICBjb25zdCBtYXNrRmllbGRzID0gJ2NvbnRlbnQvcmVuZGVyZWQnXG4gICAgICBjb25zdCByZXMgPSBhd2FpdCB0aGlzLmZldGNoKGAvc3VwcG9ydC5qc29uP2ZpZWxkcz0ke21hc2tGaWVsZHN9YClcbiAgICAgIGlmICghcmVzLm9rKSB7XG4gICAgICAgIGNvbnN0IG1lc3NhZ2UgPSBhd2FpdCByZXMudGV4dCgpXG4gICAgICAgIHJldHVybiB0aGlzLmVycm9yKHJlcy5zdGF0dXMsIG1lc3NhZ2UpO1xuICAgICAgfVxuICAgICAgY29uc3QgZGF0YSA9IGF3YWl0IHJlcy5qc29uKClcbiAgICAgIHJldHVybiB7IHBhZ2U6IGRhdGEgfVxuICAgIH1cbiAgfTtcbjwvc2NyaXB0PiJdLCJzb3VyY2VSb290IjoiIn0=